### ISSUE TITLE
failures in pure code are not propagated

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#1018]
On current 0.10 head:
```scala
val f = Failure("failure-in-pure-code", Stream.emit(42).map(_ => throw Err))
f.get.drain.run.attempt.map { r => println(s"THROWS: $r"); r}.unsafeRunSync.isLeft
//>> THROWS: Right(())
//>> res0: Boolean = false

```
expected is result on left side catching the exception Err

**Comment by pchlupacek** [comment]
Update: 

```
f.get.run.attempt.map { r => println(s"THROWS: $r"); r}.unsafeRunSync.isLeft
THROWS: Left(fs2.TestUtil$Err$: oh noes!!)
res1: Boolean = true
```

works as expected. There is definitely something very wrong with `Stream.drain`

**Comment by mpilquist** [comment]
Consider this example which doesn't use `drain`:
```scala
@ Stream(1,2,3).mapSegments(_ => Segment.empty).map(_ => sys.error("oh no")).toList
res0: List[Nothing] = List()
```
Now flip the order of `mapSegments` and `map`:
```scala
@ Stream(1,2,3).map(_ => sys.error("oh no")).mapSegments(_ => Segment.empty).toList
res1: List[Nothing] = List()
```

**Comment by pchlupacek** [comment]
ok in first example, I would expect this to not fail, in the second example however I would expact the evaluation to fail.

**Comment by pchlupacek** [comment]
what you saying is that mapSegments will efectivelyl skip the evaluation of the `f` right? If that's so we shall redefine drain I guess.

**Comment by mpilquist** [comment]
I'm not sure if we should redefine `drain` or not -- certainly open to proposals though.

`mapSegments` lets you manipulate the underlying segment structure of the team whereas `map` simply "registers" a lazy map operation to the segment structure.

**Comment by mpilquist** [comment]
To clarify a little, it's not that the `drain` is failing to propagate an exception but rather that the exception never occurred because we replaced every output segment with an empty segment, avoiding the exception entirely.

**Comment by pchlupacek** [comment]
ah yes, I see what do you mean. hm. 
So the 
```Stream(1,2,3) evalMap { i => F.raiseError(Err)  }.evalMap(identity).drain ```
works obviously as expected.

Having said that you think that perfromance penalty of defining drain as flatMap { _  => Stream.empty } is really so unbearable ?

**Comment by mpilquist** [comment]
IIRC, I originally defined `drain` that way in early 0.10 prototypes but @pchiusano convinced me we needed to change it to what you see now. Perhaps it was only related to performance but perhaps not -- sorry, I don't recall. I checked git history but the change wasn't explained in detail.

Let me approach a little differently -- why is it desirable to cause this exception to occur instead of letting the lazy/fused nature of `Stream` prevent it from occurring?

**Comment by pchlupacek** [comment]
I found that with `concurrently` tests failing with an interruption, and really, took ma quite long time to figure out whats going on there, surprisingly the stream that was supposed to fail, did not, and is used there as the `example` in test, which now with my interruption propagates fixes correctly, and suddently that amkes test to fail. 

No problem to fix that test, but i think it is very weird from user perspective, i.e. 

```
      Failure("failure-in-pure-code", Stream.emit(42).map(_ => throw Err)),
      Failure("failure-in-pure-code(2)", Stream.emit(42).flatMap(_ => throw Err)),
      Failure("failure-in-pure-pull", Stream.emit(42).pull.uncons.map(_ => throw Err).stream),
```
all these three shall always fail (as we have in tests) but the first one will never fail

**Comment by pchlupacek** [comment]
So sum up, we can say, that (1) is unsound and remove it from tests allthogether, and say that drained streams behave sort of strangely. 
Or we can fix that perhaps costing a bit of cpu. 
I don't see a big usecase for drains, now when we have concurrently, so perhpas is not big issue as it was before ? I would likely trade correctness fro perfromance here.

**Comment by pchlupacek** [comment]
I am not really suggesting we shall handle exception in pure code. Pure code is pure and that is. Having said that let me dig deeper onto that concurrently issue to see whats going on there.

**Comment by mpilquist** [comment]
Sure, I'm simply suggesting in the concurrently test, where you *need* `f.get.drain` to fail for all `f`, instead use `(f.get ++ Stream.fail(...)).drain` to guarantee that drain doesn't change stream structure such that the exception is never encountered.

**Comment by pchlupacek** [comment]
yeh, thats the isue actually. The concurrently(f.get) did not changed the issue, whereas f.get.drain did. so I just get rid of drain for this case, that easy. So far, I am convinced, so lets close this ok ?

**Comment by mpilquist** [comment]
OK sounds good
