### ISSUE TITLE
ByteVector interop no longer can be directly used in Stream.

### ISSUE THREAD

**Issue by AdamChlupacek** [functional-streams-for-scala/fs2#1020]
With the decoupling of `Chunk` from `Segment`, we can no longer directly use a ByteVector as an underlying data structure for Stream.  It is possible to make a segment out of chunk but I feel like thats unnecessary boxing. 

I propose introducing a `ByteVectorSegment`, which would in turn emit 'Chunks' of `ByteVectorChunk`.

**Comment by mpilquist** [comment]
I'm not sure how that would work in practice as `Chunk[O]` is in contravariant position in `Segment[O,R]`. I don't think the extra wrapper per chunk will show up in profiling results -- while it is an extra object allocation per chunk, performance will be dominated by other things.

**Comment by AdamChlupacek** [comment]
Oh, okay, did not notice that. Well I mostly created this just to keep it consistent with how the `ByteVectorChunk` was used before. I will close this then.
