### ISSUE TITLE
join on EitherT hangs forever

### ISSUE THREAD

**Issue by FrancoAra** [functional-streams-for-scala/fs2#1023]
From gitter: our program hangs (appears to be an infinite recursion) when joining streams which effect monad is not IO. More specifically a monad that has more than 1 error type (like EitherT[IO, E, A]), the EitherT effect implementation does not handle the left error type, so our guess is that that is causing it.

```scala
test("hangs forever on left") {

    val test: EitherT[IO, Throwable, Int] = EitherT {
      IO.pure {
        Left(new Exception("test exception")): Either[Throwable, Int]
      }
    }

    val inner: Stream[EitherT[IO, Throwable, ?], Int] = Stream.eval(test)

    val result = Stream(1, 2, 3)
      .map(_ ⇒ inner)
      .joinUnbounded
      .runLog
      .value
      .unsafeRunSync()

    println(result)

    1 == 1
  }
```

`EitherT` in here is just to exemplify, our real use case is with [this monad](https://github.com/FrancoAra/purity/blob/master/core/src/main/scala/purity/script/ScriptT.scala) which as well has 2 layers of errors/failures, the one in the type and the one inside IO.

**Comment by pchlupacek** [comment]
Is the `EitherT[IO, Throwable, Int] stack safe?

**Comment by SystemFw** [comment]
I was able to reproduce this. Things work fine if the `EitherT` is successful. Things also work fine if one does `ApplicativeError[EitherT[IO, Throwable, ?], Throwable].raiseError(new Exception("yo"))`, which translates however to `EitherT(IO(throw java.lang.Exception))`

**Comment by pchlupacek** [comment]
Aha, so seems always the failure need to be in Effect type?

**Comment by SystemFw** [comment]
if you try `inner.handleErrorWith` (or `onError` depending on the version), you see that that an error in `EitherT` expressed as a Left is not caught (one coming from a failed IO is). 
In the case of `join`, I think this prevents an `interruptWhen` from triggering, which causes the hang (haven't checked this latter detail)

**Comment by mpilquist** [comment]
@SystemFw Can you remind me where we are with this situation? Will the new cats-effect laws prohibit transformer instances that have multiple levels of error types?

**Comment by SystemFw** [comment]
@mpilquist I'm actually not sure, but my impression is that this hasn't changed, but I'll have to double check

**Comment by mpilquist** [comment]
This still occurs with 1.0.0-SNAPSHOT. Closing as this is really more of an issue with `ApplicativeError[EitherT[...], ...]` than with FS2.

**Comment by wedens** [comment]
Still reproduces with any `L` in `EitherT[IO, L, ?]`.

**Comment by grouzen** [comment]
We have the same issue. Starting several streams by mapAsync(Unordered) ends up with some of them hanging.
