### ISSUE TITLE
Unable to close `WatchService`  if file never changed

### ISSUE THREAD

**Issue by jilen** [functional-streams-for-scala/fs2#1030]
```scala
val s = file.watch[IO](Paths.get("/tmp/foo.txt")).takeWhile(e => xxx)
s.run.unsafeRunSync
```
Once the stream `s` is run, there seems no chance to stop  polling if the file is never changed.

**Comment by wedens** [comment]
I'm pretty sure you can use `interruptWhen` to stop polling at any point.

**Comment by pchlupacek** [comment]
@jilen @wedens unfortunately, even `interruptWhen` won't help in this situation likely. This is current flaw in interruption of 0.10 series on which we are working actively to resolve.

**Comment by mpilquist** [comment]
The current definition of `interruptWhen` works fine for this use case (b/c the watcher polls for events with a timeout).

```scala
Scheduler[IO](1).flatMap { scheduler =>
    Stream.eval(async.signalOf[IO,Boolean](false)).flatMap { signal =>
      io.file.watch[IO](Paths.get("/tmp/foo.txt")).map(_.toString).to(Sink.showLinesStdOut[IO,String]).interruptWhen(signal).concurrently {
        scheduler.sleep[IO](20.seconds).append(Stream.eval(signal.set(true))).drain
      }
    }
  }.run.unsafeRunAsync(println)
```

Feel free to reopen if you run in to any issues (or alternatively, post in Gitter).
