### ISSUE TITLE
Create micro-site

### ISSUE THREAD

**Issue by keirlawson** [functional-streams-for-scala/fs2#1041]
I'm new to FS2 and whilst it seems to be a really handy library I've found the documentation a little sparse which has made using/learning FS2 a bit intimidating.  Being unfamiliar with the library at this point I'm not in a good place to start helping with said documentation, however I figured what I could do is set up the various bits-and-bobs for an FS2 micro-site, as mentioned in #748 that hopefully others more knowledgeable that I could then help to populate.  Let me know if this would be helpful and if so, any particular requirements etc.

**Comment by SystemFw** [comment]
:+1: :)

**Comment by mpilquist** [comment]
This would be great! Looking forward to seeing what you come up with.
