### ISSUE TITLE
abstract fs2.io.Watcher so the jvm dependent parts are separated out

### ISSUE THREAD

**Issue by aappddeevv** [functional-streams-for-scala/fs2#1042]
This would allow a js implementation based on node.

As near as I can tell this would only require moving Watcher.fromWatchService and DefaultWatcher to a platform specific directory and abstracting Path i.e. `Watcher[Path, F[_]]`.

**Comment by mpilquist** [comment]
I think we'd need a Node compatible version of `fs2.io.file` or perhaps all of `fs2.io`. I'm not really convinced we should abstract only `fs2.io.file.Watcher`.

I suspect that FS2 Node.js file/network APIs would need to be different than the FS2 JVM file/network APIs.

**Comment by aappddeevv** [comment]
The top level part looks compatible as I wrote a watcher for scala.js using chokidar. Yes, we would need the plumbing underneath but I think that part should be a separate project for now. As it is, the upper layer of the watcher part cannot be reused directly so the request is merely to put the upper layer into a shared part of the io library and the rest into a jvm specific one.At least some reuse could occur.
