### ISSUE TITLE
Sbt `test` runs off Metaspace

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#1046]
After running couple of tests in sbt (~ 5), then CallSiteInitialization and MetaspaceOOM are thrown. My suspicion is that StreamApp tests seems to hold JVM Exit Hooks, that cause classes to be held in memory between `test` invocations.

**Comment by guersam** [comment]
Just a workaround, but `fork in Test` for jvm projects works for repeated test invocations (scala-js doesn't run in a forked jvm.)

**Comment by pchlupacek** [comment]
I think is ok to close this. Don't see any harm to fork the tests always and I think is not worth of doing something dramatic here. Thanks @guersam for help there. Closed by #1047
