### ISSUE TITLE
Release 0.10 final

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#1054]
I'd like to get a 0.10 final build out in the next few days if possible. Here's what's left:

https://github.com/functional-streams-for-scala/fs2/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.10

There's also an intermittent test failure in `asynchronous resource allocation (6)` which only happens on Travis. Next time it happens, I'll open a bug for it with captured output. Is there anything else?

**Comment by pchlupacek** [comment]
@mpilquist I have come with much stable interruption mechanics, I will put PR for that tomorrow. I think you will like it, essentially, everything is resolved in algebra, no more special `fby` `++` or repeat. Also solves the (6).  
So please give me some time to clean this up, because I think this has to go to 0.10

**Comment by mpilquist** [comment]
@pchlupacek Wow that's great news! Definitely want to get that in for 0.10. Let me know if there's anything else.

**Comment by pchlupacek** [comment]
Also I will enable some issues that I think we shall get in, and if you want pls review them.

**Comment by pchlupacek** [comment]
@mpilquist @SystemFw where do you think we are with this? I have some other ideas for features to add, but I think we shall release final asap? Any blocking issues?  #1063 didn't show up in some time, and not sure what to do about #1071 and #1075

**Comment by SystemFw** [comment]
I think the http4s people we'll be looking at #1075, which however iiuc should only affect REPL usage.
I also couldn't exactly pinpoint the issue with #1071, although I suspect it's just lack of thread safety in the Java InputStream.

**Comment by pchlupacek** [comment]
re #1071 you have tried with RC2? still the same issue ?

**Comment by SystemFw** [comment]
no, haven't tried yet, will do so today

**Comment by mpilquist** [comment]
I looked in to #1075 and confirmed that it is not a problem with `Stream` but rather an SBT limitation coupled with a feature we can add to `StreamApp` later. I'm good with 0.10 final today.

**Comment by wedens** [comment]
I think I'd be good to know what's going on in #1071. Whether it is a bug or some expected unobvious behaviour (in which case it'd be good to understand why exactly it behaves this way).

**Comment by pchlupacek** [comment]
ok I think this can be closed now :-)
