### ISSUE TITLE
Optimize interruption of Eval

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#1058]
Currently when eval is interpreted in interruptible stream, every eval races with interruption signal to assure that it will be interrupted in case of the interruption signalled. 

However for synchronous `F`, this can be optimized, so the `F` that is known to not contain asynchronous code, may not be raced with interruption signal and rather checked before // after if the stream is interrupted. That will make overhead of interruption almost negligible. 

This requires https://github.com/typelevel/cats-effect/issues/104 to be resolved.

**Comment by mpilquist** [comment]
I think we can defer this one to post 0.10 -- it wouldn't involved an API change so we can easily pick it up in 0.10.1 or something.

**Comment by pchlupacek** [comment]
sure

**Comment by mpilquist** [comment]
If cats-effect gets the requisite support in the next few days, then I'm fine with including this. I just don't want to hold 0.10 for it.

**Comment by pchlupacek** [comment]
makes sense

**Comment by mpilquist** [comment]
@pchlupacek Once #1149 is merged, this can be implemented via `Effect#runSyncStep`. Do you want to take a shot at implementing this PR?

**Comment by pchlupacek** [comment]
yes. I will do this.

**Comment by pchlupacek** [comment]
@mpilquist I just tried to implement it, but I am quite surprised that `runSyncStep` lives on Effect, which will require ConcurrentEffect on interrupt instead of Concurrent. I am sort of puzzled why this requires Effect?

What do you think is the course action we have to set ?

**Comment by mpilquist** [comment]
That makes sense - Effect and ConcurrentEffect represent the ability to run an F. Not sure what course to take here.

**Comment by pchlupacek** [comment]
Would the ConcurrentEffect be a problem as implicit to most Concurrent operators?

**Comment by mpilquist** [comment]
Ehhh, I prefer only having a Concurrent bound. I’d like to hear from @systemfw and @alexandru

**Comment by pchlupacek** [comment]
hm, sort of feel bad for @alexandru here. That feature is what we have requested to optimize eval, and now, we won't be able to use it :-(

**Comment by alexandru** [comment]
The argument against `Effect` and `ConcurrentEffect` is that these restrictions are not very generic. At that point you're essentially working with `IO` or `Task` and this matters even for the monad transformers.

I don't mind having a `runSyncStep` in `Effect`. It will prove useful, as I've been using it with `Task` for some optimizations.

But yes, I would rather keep the `Concurrent` restriction instead of this optimization.

**Comment by SystemFw** [comment]
I'd rather keep `Concurrent` as well

**Comment by pchlupacek** [comment]
ok

**Comment by pchlupacek** [comment]
so we are closing this for now ?

**Comment by SystemFw** [comment]
sooo... can we close this for the time being?

**Comment by pchlupacek** [comment]
yeah. Is shame we cannot do any better. I hope I can do something with that new IO synchronous cancel. But yeh lets close this.
