### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#1063]
`ToInputStream.upstream.is.closed` fails rarely on Travis.

```
[info] - upstream.is.closed *** FAILED *** (85 milliseconds)
[info]   false was not equal to true (JavaInputOutputStreamSpec.scala:60)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
[info]   at fs2.io.JavaInputOutputStreamSpec.$anonfun$new$10(JavaInputOutputStreamSpec.scala:60)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```

https://travis-ci.org/functional-streams-for-scala/fs2/jobs/326382839#L2383

**Comment by mpilquist** [comment]
`ResourceSafetySpec.asynchronous resource allocation (6)` fails rarely on Travis.

```
[info] - asynchronous resource allocation (6) *** FAILED *** (5 seconds, 57 milliseconds)
[info]   The test did not complete within the specified 5000000000 nanoseconds time limit. (ResourceSafetySpec.scala:240)
[info]   org.scalatest.exceptions.TestFailedDueToTimeoutException:
[info]   at org.scalatest.concurrent.Eventually$class.tryTryAgain$1(Eventually.scala:421)
[info]   at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:439)
[info]   at fs2.ResourceSafetySpec.eventually(ResourceSafetySpec.scala:10)
[info]   at org.scalatest.concurrent.Eventually$class.eventually(Eventually.scala:337)
[info]   at fs2.ResourceSafetySpec.eventually(ResourceSafetySpec.scala:10)
[info]   at fs2.ResourceSafetySpec$$anonfun$1$$anonfun$apply$mcV$sp$17.apply(ResourceSafetySpec.scala:240)
[info]   at fs2.ResourceSafetySpec$$anonfun$1$$anonfun$apply$mcV$sp$17.apply(ResourceSafetySpec.scala:214)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
```

https://travis-ci.org/functional-streams-for-scala/fs2/jobs/326811208#L1513

This was with revision 9a556e4e88fcc9792a4d0a67f78e150f4ec3207e

**Comment by pchlupacek** [comment]
@mpilquist I didn't see any of these in while. Should we somehow run travis for like 100 times ?

**Comment by mpilquist** [comment]
Here's an attempt at running the resource allocation 6 test 100x on Travis:

https://github.com/functional-streams-for-scala/fs2/compare/wip/async-resource-allocation-6-test?expand=1
https://travis-ci.org/functional-streams-for-scala/fs2/builds/327241397

**Comment by pchlupacek** [comment]
@mpilquist how did you do that?

**Comment by pchlupacek** [comment]
ah ok I see this is just branch. Was hoping there is travis command for that :-)

**Comment by mpilquist** [comment]
Travis will build every branch on this repo so I just pushed a new (temporary) branch where the test case has a `(0 until 100).foreach` wrapped around its body. Not fancy but should do the trick.

**Comment by pchlupacek** [comment]
perhaps we could have this to be done in more genric form, perhaps we could alter the spec so when -DRELEASE_CHECK=1 is defined, then specs will do more iterations of every tests, perhaps 100. And we could only run this before release ? Because that will take like 30-40 mins to complete likely ?

**Comment by mpilquist** [comment]
@pchlupacek Good idea -- should be pretty trivial to implement. Just need to allow overriding the following parameters via system property: https://github.com/functional-streams-for-scala/fs2/blob/b1c4b304680ddb6f8266a880be16061aa6ad9e34/core/shared/src/test/scala/fs2/Fs2Spec.scala#L34

**Comment by mpilquist** [comment]
@pchlupacek Looks like the async 6 test failed after 28 iterations: https://travis-ci.org/functional-streams-for-scala/fs2/jobs/327241399#L1103

**Comment by pchlupacek** [comment]
@mpilquist I have a limited bandwidth now, but I think the interruptWhen(stream) is suffering from the same issue the concurrently had. Perhaps we can define it in terms of concurrently? I mean something like promise –> self.concurrently(setPromise) ?

**Comment by SethTisue** [comment]
I've seen `ToInputStream.upstream.is.closed` fail in the Scala community build, e.g. at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2581/consoleFull

**Comment by mpilquist** [comment]
@pchlupacek Isn't the failure in `JavaInputOutputStreamSpec` a result of no longer blocking on async finalizers?

```
[fs2] [info] ToInputStream
[fs2] [info] - arbitrary.streams (160 milliseconds)
[fs2] [info] - upstream.is.closed *** FAILED *** (16 milliseconds)
[fs2] [info]   false was not equal to true (JavaInputOutputStreamSpec.scala:61)
```

That is, should we fix this just by wrapping that assertion with an `eventually`?

**Comment by pchlupacek** [comment]
to be honest didn't look into that. Certainly any code that has interruption (that is join, merge, ...) and expects the finalisers to be done when the stream completes is subject of race condition. So yeah, if we check any finalizers after `run` completes, we shall wrap them in eventually. 
Another option would be having `Sync` based finalizer and just block when it is signalled.

**Comment by mpilquist** [comment]
@pchlupacek I pushed the `eventually` fix. Note we still get a rare test failure in `asynchronous resource allocation (6)`.

**Comment by mpilquist** [comment]
Here's a new one:

```
[info] - merge (left/right failure) *** FAILED *** (81 milliseconds)
[info]   TestFailedException was thrown during property evaluation.
[info]     Message: Expected exception fs2.TestUtil$Err$ to be thrown, but no exception was thrown
[info]     Location: (MergeJoinSpec.scala:68)
[info]     Occurred when passed generated values (
[info]       arg0 = PureStream(right-associated : 0 List(),Stream(..)),
[info]       arg1 = Failure(failure-inside-effect,Stream(..))
[info]     )
```

https://travis-ci.org/functional-streams-for-scala/fs2/jobs/334997442#L643

**Comment by mpilquist** [comment]
`upstream.is.closed` is still failing even with eventually: https://travis-ci.org/functional-streams-for-scala/fs2/jobs/334999878#L2790

**Comment by pchlupacek** [comment]
@mpilquist ok that needs more thorough investigation. I'll take a look on merge. I seen that too, and seems it exhibits itself when cpu is slower // system is under load.

**Comment by mpilquist** [comment]
@pchlupacek Do you think we should hold on 0.10 final until you've had time to investigate the failures in `merge (left/right failure)` and `asynchronous resource allocation (6)`?

**Comment by SethTisue** [comment]
`upstream.is.closed ` failed again recently at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2728/consoleFull

**Comment by mpilquist** [comment]
@pchlupacek `merge (left/right failure)` still fails intermittently. I just reproduced it with this change:
```
diff --git a/core/shared/src/test/scala/fs2/Fs2Spec.scala b/core/shared/src/test/scala/fs2/Fs2Spec.scala
index 9a6841b5..ba95dbc1 100644
--- a/core/shared/src/test/scala/fs2/Fs2Spec.scala
+++ b/core/shared/src/test/scala/fs2/Fs2Spec.scala
@@ -31,7 +31,7 @@ trait Fs2SpecLike extends Suite
   lazy val verbose: Boolean = sys.props.get("fs2.test.verbose").isDefined

   implicit override val generatorDrivenConfig: PropertyCheckConfiguration =
-    PropertyCheckConfiguration(minSuccessful = 25, workers = 1)
+    PropertyCheckConfiguration(minSuccessful = 10000, workers = 1)

   override def runTest(testName: String, args: Args): Status = {
     if (verbose) println("Starting " + testName)
```

and then from coreJVM project, running this a few times until it failed: `testOnly *Pipe2Spec -- -z "merge (left/right failure)"`

```
[info] - merge (left/right failure) *** FAILED *** (808 milliseconds)
[info]   TestFailedException was thrown during property evaluation.
[info]     Message: Expected exception fs2.TestUtil$Err$ to be thrown, but no exception was thrown
[info]     Location: (Pipe2Spec.scala:181)
[info]     Occurred when passed generated values (
[info]       arg0 = PureStream(randomly-chunked: 0 Vector(),Stream(..)),
[info]       arg1 = Failure(pure-failure,Stream(..))
[info]     )
```

**Comment by pchlupacek** [comment]
interresting. seems like there is still subtle detail. I'll take a look on it.

**Comment by SethTisue** [comment]
`upstream.is.closed` failed again at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3120/

`upstream.is.force-closed` failed again at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3119/ and also https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3118/ and https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3117/

these are all on the `series/0.10` branch

this is becoming a frequent enough annoyance for the community build that I'm going to just stop running these tests: scala/community-builds@a934e66b519f92fe6bf53e886aeb1038035b6331

**Comment by mpilquist** [comment]
`upstream.is.closed` and `upstream.is.force-closed` are both disabled until the intermittent failures can be addressed.

**Comment by pchlupacek** [comment]
I am not sure of the status now in 1.0. I would suggest to close this, and track now individually?
