### ISSUE TITLE
concurrently or merge* and toInputStream never terminates

### ISSUE THREAD

**Issue by wedens** [functional-streams-for-scala/fs2#1071]
This code never terminates (hangs) in 0.10.0-RC1:

```scala
import fs2._
import cats.effect.IO
import scala.concurrent.ExecutionContext.global

val in: Stream[IO, Option[Byte]] = Stream(Some(1 : Byte), None)

val s: Stream[IO, Byte] =
  Stream.eval(async.unboundedQueue[IO, Option[Byte]]).flatMap { q =>
    val write = in.to(q.enqueue)
    val read = q.dequeue.unNoneTerminate
    read concurrently write // or `read merge write`
  }

s.through(io.toInputStream).compile.drain.unsafeRunSync()
```
It worked fine in 0.10.0-M5.

It successfully terminates if `concurrently` is replaced with ~~`merge*` or~~   `join`. It also successfully terminates with `concurrently` but without `toInputStream` (e.g. if `toInputStream` is replaced by `io.file.writeAll`).

**Comment by wedens** [comment]
I'm not sure how it worked with `merge*` (perhaps I launched it with unsaved file?) but now it also consistently hangs. Still works fine with `join`.

**Comment by wedens** [comment]
I've found some interesting comment in `prefetchN` implementation. Perhaps it's related to the issue (and it doesn't use `toInputStream`)?

```scala
    def prefetchN(n: Int)(implicit ec: ExecutionContext, F: Effect[F]): Stream[F, O] =
      Stream.eval(async.boundedQueue[F, Option[Segment[O, Unit]]](n)).flatMap { queue =>
        // TODO Replace the join-based implementation with this one based on concurrently when it passes tests
        // queue.dequeue.unNoneTerminate
        //   .flatMap(Stream.segment(_))
        //   .concurrently(self.segments.noneTerminate.to(queue.enqueue))
        Stream(queue.dequeue.unNoneTerminate.flatMap(Stream.segment(_)),
               self.segments.noneTerminate.to(queue.enqueue).drain).joinUnbounded
      }
```

**Comment by SystemFw** [comment]
I'm seeing all sorts of weird behaviour on this one (weirder than your initial example seems to imply). Trying to figure out what's going on

**Comment by SystemFw** [comment]
Although the doc say:
```
/**
    * Pipe that converts a stream of bytes to a stream that will emits a single `java.io.InputStream`,
    * that is closed whenever the resulting stream terminates.
    *
    * If the `close` of resulting input stream is invoked manually, then this will await until the
    * original stream completely terminates.
    *
    * Because all `InputStream` methods block (including `close`), the resulting `InputStream`
    * should be consumed on a different thread pool than the one that is backing the `ExecutionContext`.
    *
    * Note that the implementation is not thread safe -- only one thread is allowed at any time
    * to operate on the resulting `java.io.InputStream`.
```

I need to see if this is relevant or not, given that we aren't directly operating in the `InputStream`

**Comment by wedens** [comment]
Still hangs in 0.10.0-RC2 :(

**Comment by pchlupacek** [comment]
@wedens @SystemFw could we confirm that we are not able to minimize this, i.e. remove `io. toInputStream` from example?

**Comment by wedens** [comment]
Sorry, I forgot about [SI-9076](https://issues.scala-lang.org/browse/SI-9076) and tested it in REPL.

It doesn't hang in RC2 with both `concurrently` and `merge`.

**Comment by mpilquist** [comment]
Does adding `-Ydelambdafy:inline` also fix?

https://github.com/functional-streams-for-scala/fs2/blob/series/0.10/docs/faq.md#why-does-stream-evaluation-sometimes-hang-in-the-repl

**Comment by wedens** [comment]
No, it doesn't. I think using `async.unsafeRunAsync` did it (in REPL). So, it may not be related to  SI-9076 now that I think of it (sorry for confusion).

**Comment by SystemFw** [comment]
you should also test with `join`, and not just that it doesnt' hang.
With the first code you posted, `join` wasn't working either, it won't execute anything (that's why it didn't hang). You'll see it by prinltn through a Sink on enqueue and dequeue

**Comment by SystemFw** [comment]
I very stupidly lost the test case I had :(

**Comment by SystemFw** [comment]
emacs saves the day once more!

```scala

  val in: Stream[IO, Option[Byte]] = Stream(Some(1: Byte), None)

  val s: Stream[IO, Byte] =
    Stream.eval(async.unboundedQueue[IO, Option[Byte]]).flatMap { q =>
      val write = in.observe(_.evalMap(put)).to(q.enqueue)
      val read = q.dequeue.observe(_.evalMap(put)).unNoneTerminate
      read.concurrently(write)
    }

  
  val ss: Stream[IO, Byte] =
    Stream.eval(async.unboundedQueue[IO, Option[Byte]]).flatMap { q =>
      val write = in.observe(_.evalMap(put)).to(q.enqueue)
      val read = q.dequeue.observe(_.evalMap(put)).unNoneTerminate
      
      Stream(read,write.drain).join(2)
    }

  def a = ss.through(io.toInputStream).compile.drain
  def b = s.through(io.toInputStream).compile.drain
````

**Comment by SystemFw** [comment]
They are still both broken, but now they are in a uniform way.
They both will immediately complete without doing anything most of the time, and sometimes print something (a partial result), and I think also deadlock sometimes. 
This is the behaviour I've observed with `join` previously, and now `concurrently` behaves the same

**Comment by pchlupacek** [comment]
@wedens @SystemFw not sure If I am following correctly, issue still persist yes/no?

**Comment by wedens** [comment]
@SystemFw yes, you're right. It doesn't execute anything with any of `join`/`merge`/`concurrently` (I haven't seen even partial results). Manually doint `close` on `InputStream` achieves nothing.

@pchiusano Yes. Slightly differently but it's still broken. I don't think 0.10 final can be released with such issue :/

**Comment by wedens** [comment]
@SystemFw I think works with `concurrently` and `merge` (but not `join`) if `InputStream` is consumed using `io.readInputStreamAsync` (but not `io.readInputStream`).

**Comment by SystemFw** [comment]
So, the thing is the my broken example above did not do nothing _all_ the time. One in every 50 runs it would print something, so I'd still like to know what's going on (because your working code might then still be broken in subtle ways)

**Comment by mpilquist** [comment]
@SystemFw @wedens I'm having trouble understanding what's wrong here. Is it that one in 50 runs you see something on std out but most times you don't? Isn't that explained by concurrency in the implementation of `observe`?

**Comment by SystemFw** [comment]
the original problem reported does not have `observe` in it. I can simplify my example to just use `.evalMap(F.println)` and we'll see what happens.

Anyway yes, most of the time nothing happens, with all combinators. (in the previous version `join` behaved identically, and `concurrently` and `merged` deadlocked)

**Comment by mpilquist** [comment]
OK, a simpler example that demonstrates an issue would be great. I'd like to release 0.10 tonight if possible but I'd also like to first determine if there's a bug here.

**Comment by SystemFw** [comment]
```scala
  import scala.concurrent.ExecutionContext.Implicits.global

  val in: Stream[IO, Option[Byte]] = Stream(Some(1: Byte), None)

  val s: Stream[IO, Byte] =
    Stream.eval(async.unboundedQueue[IO, Option[Byte]]).flatMap { q =>
      val write = in.evalMap(x => IO { println(x); x }).to(q.enqueue)
      val read = q.dequeue.evalMap(x => IO { println(x); x }).unNoneTerminate
      read.concurrently(write)
    }
   def b = s.through(io.toInputStream).compile.drain.unsafeRunSync
````
```
 scala> b
 Some(1)
 Some(1)
 None

 scala> b

 scala> b

 scala> b

 scala> b

 scala> b

 scala> b

 scala> b

 scala> b

 scala> b

 scala> b

 scala> b
 Some(1)

 scala> b

 scala> b

 scala> b
````

**Comment by SystemFw** [comment]
Still unsure if this is a bug, or just expected behaviour since `InputStream` is not thread safe

**Comment by mpilquist** [comment]
That output looks correct to me and it is unrelated to thread safety of toInputStream. The overall stream emits a single input stream which is then ignored and the end of stream is reached. We then subsequently shut down the stream, which terminates the concurrent “fill” stream which makes data available to the InputStream. The output varies because of timing differences in execution — essentially there’s an expected race between shutdown and filling.

**Comment by SystemFw** [comment]
Wow, all this time and I hadn't even looked at the fact that the `InputStream` wasn't actually being used :(

**Comment by mpilquist** [comment]
Note The example from @wedens does read the InputStream to completion.

**Comment by SystemFw** [comment]
adding a `flatMap(s => io.readInputStream(s.pure[IO], 10))` gives expected behaviour, so you're right.

**Comment by SystemFw** [comment]
But that's good, it means there's no blockers for 0.10 :smile:

**Comment by SystemFw** [comment]
working code:
```scala
  import scala.concurrent.ExecutionContext.Implicits.global

  val in: Stream[IO, Option[Byte]] = Stream.range(1, 100).map(_.toByte).covary[IO].noneTerminate

  val s: Stream[IO, Byte] =
    Stream.eval(async.unboundedQueue[IO, Option[Byte]]).flatMap { q =>
      val write = in.evalMap(x => IO { println(x); x }).to(q.enqueue)
      val read = q.dequeue.evalMap(x => IO { println(x); x }).unNoneTerminate
      read.concurrently(write)
    }

  def b = s.through(io.toInputStream).flatMap(s => io.readInputStream(s.pure[IO], 10)).compile.drain.unsafeRunSync
```

**Comment by mpilquist** [comment]
Okay excellent. I’m going to build tonight I think then. I’ll leave this open pending an update from @wedens. If we’re wrong and there’s some bug lurking here, we can always release 0.10.1.

**Comment by wedens** [comment]
Ok, let's close it for now.
