### ISSUE TITLE
Promise.timedGet throws PromiseAlreadyCompleted exception

### ISSUE THREAD

**Issue by SystemFw** [functional-streams-for-scala/fs2#1077]
Minimal example so far:

```scala
import fs2._
import cats._, implicits
import cats.effect._

  import scala.concurrent.ExecutionContext.Implicits.global

  def timed[A](io: IO[A])(timeout: FiniteDuration)(implicit s: Scheduler, ec: ExecutionContext) =
    for {
    promise <- async.promise[IO, A]
    _ <- async.fork(io.flatMap(promise.complete))
    a <- promise.timedGet(timeout, s)
  } yield a

  val n = 10

  def yo =
    Scheduler[IO](2).flatMap { implicit s =>
      Stream.repeatEval(timed(1.pure[IO])(1.millis)).take(n)
    }.compile.drain.unsafeRunSync
```

I'm fairly certain the bug is actually in `race` (called by `timedGet`), but haven't minimised yet

**Comment by ChristopherDavenport** [comment]
Commenting to stay in the loop. Thank you for looking into this.

**Comment by SystemFw** [comment]
Right, first clue:
The Promise getting set twice is not in `race`, nor in the code above, but in `Scheduler.delayCancellable`. Quite late now, but I'll keep investigating this tomorrow morning.

**Comment by SystemFw** [comment]
I think I've narrowed it down to the specific line now. The rest will be tomorrow.
