### ISSUE TITLE
Status of 0.8 series

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#1091]
What we will do with 0.8 series? There are still some open issues, not sure if anyone is working on them. Shouldn't we just say it is EOL and we won't do any fix for it whilst users are free to migrate to 0.10?

**Comment by mpilquist** [comment]
👍 for 0.8 being EOL. I don't know of anyone working on fixes for 0.8. If someone wants to contribute fixes, I'm happy to do releases but I'm not planning on doing any other work on 0.8.
