### ISSUE TITLE
Rename compile.drain to compile.void

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#1092]
Currently the `drain` result of compile is sort of confusing with Stream.drain. Also F[A] -> F[Unit] function in cats is `.void`. As such I would propose to rename `compile.drain` to `compile.void`

**Comment by mpilquist** [comment]
I kind of like `drain` as it signals that we're ignoring the output elements completely and instead running the stream purely for its effects. The similarity to `Stream#drain` is intentional, despite the difference in returning a single `Unit` vs `Nothing`.

**Comment by pchlupacek** [comment]
ok, no prob, closing this now.
