### ISSUE TITLE
Support cats-effect 0.10 and 1.0

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#1100]
There are some major new features coming to cats-effect shortly: https://github.com/typelevel/cats-effect/milestones

Notably:
 - A new [Timer](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/Timer.scala) type (0.10)
 - Cancelation support in `IO` and in the type class hierarchy (in the `Concurrent` type class) (0.10)
 - Bracket support in `IO` and in the type class hierarchy (1.0)

I've started the [topic/cats-effect-0.10](https://github.com/functional-streams-for-scala/fs2/tree/topic/cats-effect-0.10) branch to track changes in support of the 0.10 preview builds. That branch includes:
 - removal of `fs2.Scheduler` in favor of `cats.effect.Timer`
 - changing async data structures to take a `Concurrent[F]` constraint instead of an `Effect[F]` constraint
 - changing async data structures to utilize cancelation via `Concurrent` instead of ad-hoc solutions like `cancellableGet`, `timedGet`, etc.

I'm not sure if there's anything we'd like the change in FS2 once `bracket` lands in cats-effect 1.0.

I'm currently thinking we should release a binary compatible version of FS2 0.10 against cats-effect 0.10 with none of the above mentioned changes -- simply rebuild FS2 against cats-effect 0.10. Then we should release FS2 0.11 against cats-effect 1.0 when it is ready in May. Alternatively, we could release FS2 0.11 against cats-effect 0.10 with the above mentioned changes and then FS2 0.12 (or 1.0!) against cats-effect 1.0. Thoughts?

**Comment by pchlupacek** [comment]
+1 to 0.11 / 0.10 and 1.0 with 1.0 
also @mpilquist  I would like to get resolution on https://github.com/typelevel/cats-effect/issues/104 before 0.11 release, as this may be necessary for any _Interruptible_ merge in fs2, so basically any concurrent primitive.

**Comment by SystemFw** [comment]
> I'm currently thinking we should release a binary compatible version of FS2 0.10 against cats-effect 0.10 with none of the above mentioned changes -- simply rebuild FS2 against cats-effect 0.10. 

I like this one better, mostly because every time we break things the whole ecosystem has to do so as well. Since the changes in cats effect _might_ end up being significant, I'd err on the side of caution and avoid breaking things twice.

Not too hung up on it though.

**Comment by pchlupacek** [comment]
@SystemFw ah aha, I sort if misunderstood. Yeah, we perhaps shall leave 0.10 agains 0.10 no changes and put rest towards 1.0

**Comment by mpilquist** [comment]
Works for me
