### ISSUE TITLE
Evaluate need for ExecutionContext and thread shifting throughout API

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#1104]
Now that we have `cats.effect.Concurrent`, our dependency on `ExecutionContext` can be reduced quite a bit. `Promise` no longer depends on an `ExecutionContext` at all. `Signal` depends on an `ec` only for completing an internal promise asynchronously.

We should analyze our current uses of `ExecutionContext` and see if there are any that should be removed.

Also, we should consider whether we really want `async.shiftStart` and `async.unsafeRunAsync` or whether these should be deprecated / moved to cats-effect.

**Comment by SystemFw** [comment]
I'll be taking a closer look at this soon. However my view has shifted a bit and I think that something like `shiftStart` (renamed to `fork`) would be quite useful. The fact that `shifting` and `starting` are separated is imho a bit too confusing for beginners. In any case, I'll hopefully be able be more precise soon.

**Comment by notxcain** [comment]
As discussed on gitter with @SystemFw, it's probably possible to replace `ExecutionContext` with `Timer[F]`

**Comment by Daenyth** [comment]
Can this now be closed since #1149 is merged?
