### ISSUE TITLE
Add Queue "isEmpty" signal

### ISSUE THREAD

**Issue by Daenyth** [functional-streams-for-scala/fs2#1116]
It would be nice to have a `def empty: Signal[F, Boolean]` with semantics being `true when the queue is empty, and false otherwise`.

You can get there from `available` with bounded queues, except that for unbounded queues, available is MaxInt

**Comment by SystemFw** [comment]
queue has:
```scala
def size: immutable.Signal[F, Int]
```
Which you can manipulate to get what you want.
However note that anything like this can't be reliably used to modify state concurrently (without further checks), and also that quick enqueues-dequeues might not result in updates to the Signal.
