### ISSUE TITLE
Improve queue

### ISSUE THREAD

**Issue by SystemFw** [functional-streams-for-scala/fs2#1117]
Queue is quite an essential structure, and it works fairly to very well already, but there are a few ideas floating around on how to flesh it out/improve it.
I'm opening this issue to keep track of things to be explored before 1.0

- Adding a `tryDequeue: F[Option[A]]`
- Adding a `drainQueue: F[Option[Vector[A]]`
- Explore extracting the queue strategy from the queue implementation itself
- Evaluate solutions to the problem of expressing "this queue will not receive any elements anymore". This is currently encoded with `Option` and `dequeue.unNoneTerminate`, is this solution ok? Can it be improved?

**Comment by paul-lysak** [comment]
Hi. `complete` and `fail` methods like in `akka.stream.scaladsl.SourceQueueWithComplete` would be quite useful, to my oppinion.

**Comment by mpilquist** [comment]
@SystemFw Any thoughts on what's left here for 1.0?

**Comment by SystemFw** [comment]
@pchlupacek I'm not too hung on the specific type (`Vector` or whatever else).
I guess what I was going for with `tryDequeue` and `drainQueue` was:
Try to give me an element, and immediately return is none is available `tryDequeue` (hard to express this with the current combinators) and, try to give me all the elements there, and immediately return if there's none (`drainQueue`). On further thought, maybe `drainQueue` is not safe, so perhaps we should only have `tryDequeue` and `tryDequeueBatch1`? But tbh, I'm not too hung up on either since I don't have a use case anymore, and I would probably build a custom structure if I need that behaviour.

So, unless either of you really wants that, we can proceed without I think. Thoughts?
