### ISSUE TITLE
Incorrect OSGI JRE version restriction

### ISSUE THREAD

**Issue by sourya7** [functional-streams-for-scala/fs2#1127]
Currently, the released versions of fs2 includes a 'Require-Capability' header in the manifest as 

`Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8.0_162))"` which fails because that version string seems to be incompatible with what the osgi framework was expecting (I'm using Karaf). I believe that it should be more of a `Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"` which will allow the framework to consider JavaEE `version >= 1.8` as something that matches that filter.  

Something from the sbt-osgi documentation about the `requireCapability` setting might be related: `requireCapability: value for Require-Capability header, defaults to osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=*PROJECT JAVAC VERSION*))"`

**Comment by mpilquist** [comment]
Yeah that looks like the culprit. I think we could just override `requireCapability := """osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))""""`

**Comment by mpilquist** [comment]
Fixed by upgrading to sbt-osgi 0.9.3 due to this upstream bugfix: https://github.com/sbt/sbt-osgi/pull/46
