### ISSUE TITLE
Memory leak with 'flatMap', 'zip', 'fixedDelay'...

### ISSUE THREAD

**Issue by epellizzer** [functional-streams-for-scala/fs2#1151]
After spending a day at work doing various experiments to fix a memory leak in the long-lived stream that makes up one of my applications, I think streams shaped around some combinations of `flatMap`, `zip`, `joinUnbounded` and `Scheduler.fixedDelay` create an accumulation of FS2 objects.

I have observed the problem in both versions 0.10.2 and 0.10.4.

My stream's shape is pretty complex, and I can disclose some of it if really needed, but I have a small example that shows the problem. It probably deserves some explanation to map it with my real case.

The core logic is that I have an application that handles so-called processes, each of which consists in picking files from a dedicated directory, reading each of them and sending their contents as a message in a Kafka topic. To support a dynamic set of processes, at each 'heartbeat' (every second for example), I read a set of process definitions that is fed from an external administration web service, and for each of them, create a stream that consists in doing all that. Those streams are then joined. Those sub-streams are not long-lived; they end as soon as one file is processed, so that the joined stream ends as soon as possible, and another heartbeat can take place, with possibly a different set of processes, or with different configurations. In particular, this set can be empty.

```
import cats.effect.IO
import fs2.{Scheduler, Stream}

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration._

object SandboxApp extends App {
  // The inner stream embodies the set of processes, always empty in this example
  private val sources: Stream[IO, Stream[IO, Int]] = Stream(Stream.empty.covaryAll).repeat

  Scheduler[IO](8)
    .flatMap { sched =>
      sched.fixedDelay[IO](10.milliseconds) // At each heartbeat...
        .zip(sources) // ... obtain the set of 'processes'
        .flatMap { case (_, s) =>
          s.map(Stream.constant(_).covary) // ... create a stream that does something with each (irrelevant here)...
           .joinUnbounded // ... and join all processes
        }
    }
    .compile
    .drain
    .unsafeRunSync()
}
```

In the example, the set of processes is always empty, and the infinite stream created with `Stream.constant` is never executed, but the memory leak is already present at this point.

I initially thought `joinUnbounded` was the only culprit because when replacing `s.map(Stream.constant(_).covary).joinUnbounded` with `s.flatMap(Stream.constant(_).covary)`, the problem is gone in this example. However, in my real stream it is still there, though more subtle. So maybe there are several issues after all.

Here are the memory usage charts for my real application: https://imgur.com/a/h0brZbS, as well as a link to the complete snapshots that you can open in JVisualVM to check the heap dumps I took and compare them. The link is only valid until June 5th: https://www.transfernow.net/314kp1x23v2q. Before each heap dump, I forced a GC.

All of my tests are done with `-Xms64m -Xmx64m`, and the data I provide here is for the tests done with version 0.10.4. Note also that in the real cases, the heartbeat frequency is a hundred times lower than in the example.

I have tried to change a bit my stream's shape hoping to find a workaround, but to no avail. Sometimes I made it even worse, though I haven't kept track of all my attempts. This is probably subjective, but sometimes I found the problem to be a bit less serious in version 0.10.2.

This is a serious issue for me and I hope you guys will be able to at least find a workaround.

Aside from that, great library ;)!

**Comment by mpilquist** [comment]
Thanks for the comprehensive bug report. I'll take a look soon, though I'm curious if the problem disappears if you replace `zip(sources)` with `.map(u => (u, Stream.empty.covaryAll))`.

**Comment by epellizzer** [comment]
Thanks for that quick answer.

I just tried that and the results are the same. For the real case, I took care of replacing all the occurrences of `zip`, because I had several.

I too was inclined to suspect `zip`, seeing how its implementation seems not trivial and knowing the issues it suffered from in some previous releases.

**Comment by pchlupacek** [comment]
@epellizzer as a side done, I wouldn't use zip if you do not need resource management or if the stream does not have some complex stateful logic in it. Zip introduces not negligible overhead, your example will be much better performing with simple `s.evalMap { x => IO{ x -> now () } }`

**Comment by epellizzer** [comment]
@pchlupacek ok I see, thanks for the advice.

**Comment by mpilquist** [comment]
The leak appears to be somewhere in resource management, perhaps in CompileScope. This is a telling memory delta:
<img width="969" alt="image" src="https://user-images.githubusercontent.com/118078/40753285-554f1232-6441-11e8-84c9-4a8a6a03140c.png">

Note the leak reproduces much faster with this program:

```scala
object SandboxApp extends App {
  import scala.concurrent.ExecutionContext.Implicits.global

  // The inner stream embodies the set of processes, always empty in this example
  private val sources: Stream[IO, Stream[IO, Int]] = Stream(Stream.empty.covaryAll).repeat
    Stream.constant(()) // At each heartbeat...
    .zip(sources) // ... obtain the set of 'processes'
    .flatMap {
      case (_, s) =>
        s.map(Stream.constant(_).covary) // ... create a stream that does something with each (irrelevant here)...
          .joinUnbounded // ... and join all processes
    }
    .compile
    .drain
    .unsafeRunSync()
}
```

Continuing minimization...

**Comment by mpilquist** [comment]
Here's an interesting update...

This program exhibits the same leak:
```scala
  Stream(Stream.empty.covaryAll[IO, Stream[IO, Int]])
    .repeat
    .flatMap(s => s.joinUnbounded)
    .compile
    .drain
    .unsafeRunSync()
```

This one does *not* leak (only difference is the introduction of the scope):
```scala
  Stream(Stream.empty.covaryAll[IO, Stream[IO, Int]])
    .scope
    .repeat
    .flatMap(s => s.joinUnbounded)
    .compile
    .drain
    .unsafeRunSync()
```

This also does *not* leak, show the issue isn't solely with `join` but rather the way it interacts with parent scope:

```scala
val sources: Stream[IO, Stream[IO, Int]] = Stream(Stream.empty.covaryAll).repeat
sources.joinUnbounded.compile.drain.unsafeRunSync
```

**Comment by epellizzer** [comment]
Regarding your last remark, remember that in my real app, the leak is there even when `join` is not used at all, and replaced with `flatMap`. I have just checked again and I have no other place in my code that uses `join`.

With `flatMap`, the resulting heap dump diff is very different (https://imgur.com/M2fnKQt) than the one with `join` (https://imgur.com/1xK32Fw), but hopefully the root issue is the same.

Would it be possible that `flatMap` itself is the culprit?

**Comment by mpilquist** [comment]
Here's another example which leaks with `join` but doesn't leak with `merge`.

Does leak:
```scala
  Stream(Stream(0).covary[IO]).repeat
    .flatMap(s => Stream(Stream(1).covary[IO], Stream(2).covary[IO]).joinUnbounded)
    .compile
    .drain
    .unsafeRunSync()
```

Doesn't leak:
```scala
  Stream(Stream(0).covary[IO]).repeat
    .flatMap(s => Stream(1).covary[IO].merge(Stream(2).covary[IO]))
    .compile
    .drain
    .unsafeRunSync()
```

@epellizzer Yep, I suspect the underlying issue will fix both the join based examples and your original code that doesn't use join. Basically, there's something happening in the join examples that causes resources to get promoted to a parent scope. In these examples, that parent scope is the root scope of the stream, so the resources accumulate and never get cleaned up.

**Comment by mpilquist** [comment]
Update: I suspect the bug is really in `Signal#discrete`, where the finalizer that unregisters a given ID can happen *before* the ID has ever been registered. Here's a program that leaks using `merge` and `Signal#discrete`:

```scala
  Stream
    .eval(async.signalOf[IO, Int](0))
    .flatMap { signal =>
      Stream(Stream(0).covary[IO]).repeat
        .flatMap(s => signal.discrete.mergeHaltBoth(Stream.empty.covary[IO]))
    }
    .compile
    .drain
    .unsafeRunSync()
```

Note `join` is implemented with a `Signal#discrete` whereas `merge` isn't, which explains the earlier observations.

**Comment by pchlupacek** [comment]
@mpilquist Any chance this could be related to `leasing` resources in .join?

**Comment by mpilquist** [comment]
@pchlupacek Yeah maybe. Some things I've found:

1) `repeat` should really introduce a new scope, as without scope introduction, it's way too easy to end up with finalizers that live forever. Consider this example:
```scala
val l = Stream.eval(IO.never).covary[IO].onFinalize(IO(println("Left finalized")))
val r = Stream.empty.covary[IO].onFinalize(IO(println("Right finalized")))
l.mergeHaltBoth(r).repeat.compile.drain.unsafeRunSync
```
This example has a resource leak b/c the left finalizers all end up registered on the root scope. If we introduce a new scope in `repeat`, this goes away.

2) `join` and `zip` work together in a way I don't quite understand. Specifically, streams of the shape `l.zip(r).flatMap(t => blah.joinUnbounded)` results in finalizers getting promoted to a parent scope. However, introducing a new scope on the output of join, before its internal finalizer registered, fixes this.

3) I don't know why `merge` doesn't lease scopes whereas `join` does.

**Comment by AdamChlupacek** [comment]
@mpilquist Those finalisers should not register to the root scope in this case (1), that is for sure. There is a scope introduced in side of merge for both sides (when making them interruptible), the finalisers should be registered to those scopes. 

As per leasing, merge does not need to do so, as we only have 2 streams that are known form the start, and they are not produced by a stream that could actually have resources acquired.

**Comment by mpilquist** [comment]
@AdamChlupacek I don't see a scope being introduced in `interruptWhen`.

**Comment by AdamChlupacek** [comment]
@mpilquist An interrupt scope has to be added with any kind of interruption we have at the moment, as that is how interruption is done.

**Comment by mpilquist** [comment]
I'm talking about `scope` though -- not interruption scopes.

**Comment by AdamChlupacek** [comment]
They should be completely the same, except for the fact that interrupt scope can be interrupted and adds an race for each `eval`.

**Comment by mpilquist** [comment]
OK I don't know then, but the left/right mergeHaltBoth test definitely shows an issue with the left finalizers getting delayed past the call to `repeat` and redefining `repeat` as `this.scope ++ repeat` fixes that at least.

**Comment by pchlupacek** [comment]
just as an observation 0.10.3 opened scope with every `onFinalize`, 0.10.4 removed that, thus I believe this is why <0.10.4 exhibits lesser memory leak as @epellizzer observed. 

This seems like we are generally leaking resource closure, and are relying on `scope` for cleanup.

would be interesting to observe if we somehow do not skip `Resource.release' on some scenarios

**Comment by pchlupacek** [comment]
One idea here. CompileScope#releaseResource releases only resources that are related to the scope where they were acquired. What if, Release(token) is interpreted at time, when active scope is different than one that acquired particular resource (i.e. child scope). I think in that case we are unable to find that resource and thus release won't happen, until the parent scope terminates. 

Shall be quite easy to confirm this theory and made fix.

**Comment by pchlupacek** [comment]
As a side note we are just discussing with @AdamChlupacek that we shall perhaps consider to change signature of `Stream#bracket` for 1.0 release. 
Idea would be that bracket will use the `flatMap` to provide resource guarantee, so essentially we will not have `use` anymore, hence that is in most cases `emit` anyhow (i.e. your newly added `def resource`). Essentially it will be sort of similar to what we do with scope, i.e. 
```scala

def bracket[A](acquire: F[A], release: A => F[Unit]) = ???

s1.bracket(get, release).flatMap { a => /* use `A` */ }

```

**Comment by mpilquist** [comment]
@pchlupacek I like the suggested change to bracket. I also like your theory as to what's going wrong here. Let me know how you make out. :)

**Comment by SystemFw** [comment]
Re bracket, I've had the same idea several times. It would also IMHO make
the distinction with F.bracket clearer

**Comment by epellizzer** [comment]
As an outsider, I concur with this idea of changing `bracket`'s signature.

Most of the time in my case, the code that uses it doesn't know what to do with the acquired resource except simply emitting it. The calling code then flatmaps over it.

Furthermore, the presence of two closures in the same parameter list makes it very awkward to write cleanly indented code and prevents from using the simple curly-braces style.

**Comment by mpilquist** [comment]
@pchlupacek I tried this change in CompileScope.scala:
```scala
  def releaseResource(id: Token): F[Either[Throwable, Unit]] =
    F.flatMap(state.modify2 { _.unregisterResource(id) }) {
      case (c, mr) =>
        mr match {
          case Some(resource) =>
            resource.release
          case None =>
            println("No-op release")
            F.pure(Right(())) // resource does not exist in scope any more.
        }
    }
```

No luck with the original program -- never prints "no-op release"

**Comment by epellizzer** [comment]
Is there a snapshot I can try to check if everything is fixed on my side?

**Comment by mpilquist** [comment]
@epellizzer Yep, try 0.10.5-SNAPSHOT from https://oss.sonatype.org/snapshots/content/repositories/snapshots

**Comment by epellizzer** [comment]
Ok apparently the leak is gone with 0.10.5-SNAPSHOT. Can I expect 0.10.5 to be out soon?

Thanks!

**Comment by mpilquist** [comment]
@epellizzer Yep, it's out now. Maven Central may not have synchronized with Sonatype yet but you can point directly to the Sonatype public repository in the meantime.

**Comment by epellizzer** [comment]
Cool thanks!
