### ISSUE TITLE
Find a way to reduce amount of insertion of scopes

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#1156]
Recent updates #1151 and subsequently #1154 introduced scopes about any Pull/Stream. I believe this is not necessary and this issue shall investigate if we could somehow safely guarantee that certain combinators do not need introduction of the scope (i.e. all that recurse infinitely around tail, i.e. map)

@mpilquist @AdamChlupacek @SystemFw  any thoughts?

**Comment by mpilquist** [comment]
@pchlupacek This would be great, though I feel like I finally understand why we added a scope to every `Pull` in 0.9 and it seems like a pretty fundamental issue.

**Comment by pchlupacek** [comment]
I am quite convinced that for combinators like map, mapAcummulate, find, collect,  etc, that do not interrupt the stream, and thus have no chance to throw away tail, we don't have to insert scope. For others like take, we shall likely insert scope.

**Comment by mpilquist** [comment]
@pchlupacek Oh I misunderstood you. Yes, I agree -- as long as the pull evaluates the entire source stream, we can use `Pull#streamNoScope` instead of `Pull#stream`.

**Comment by pchlupacek** [comment]
Yes, I am thinking of modifying the API, so the one with #streamNoScope will be available only when user will have no access to tail, in which case the operation will just operate on chunk. On the variant which will have access to tail, I think we shall in contrary always require scope to be inserted.

**Comment by pchlupacek** [comment]
I dont think anymore  so there is reasonable gain in the scope optimalization. With recent changes to interruption I think scopes are much more cheaper that they were before. So for now I am closing this
