### ISSUE TITLE
Stream#groupAdjacentBy can error calling Chunk.empty.apply

### ISSUE THREAD

**Issue by Daenyth** [functional-streams-for-scala/fs2#1162]
I'm not sure of the reproduction case yet - as soon as I can I'll attach one.

Based on reading the code, the way to hit this code path is if `unconsChunk` returns `Some((Chunk.empty, rest))`

**Comment by mpilquist** [comment]
https://github.com/functional-streams-for-scala/fs2/blob/86451701b309728cf364426a4679cff9c0aacca3/core/shared/src/main/scala/fs2/Stream.scala#L596

This assumes the chunk is non-empty (probably a carry-over from 0.9 where chunks were guaranteed to be non-empty).

**Comment by mpilquist** [comment]
Right, it's not :) I'll post a sample stream that gives empty chunks there in a bit.

**Comment by mpilquist** [comment]
Here's an example that lets you observe an empty chunk:

```scala
@ Stream(1,2,3).map(identity).filter(_ > 1).chunks.toList
res2: List[Chunk[Int]] = List(empty, Chunk(2), Chunk(3))
```

**Comment by Daenyth** [comment]
Does this look right?
```scala
case Some((hd, tl)) =>
  if (hd.nonEmpty) {
    val (k1, out) = current.getOrElse((f(hd(0)), Segment.empty[O]))
    doChunk(hd, tl, k1, out, None)
  } else {
    go(current, tl)
  }
```

**Comment by mpilquist** [comment]
Yep

**Comment by Daenyth** [comment]
I'll PR in a fix with tests soon. The block above definitely fixes it
