### ISSUE TITLE
`.interruptWhen` sometimes prevents error handler in `.handleErrorWith` from running

### ISSUE THREAD

**Issue by vladimir-lu** [functional-streams-for-scala/fs2#1170]
This seems to be a concurrency issue introduced by `.interruptWhen`. This test reproduces the behavior: https://github.com/vladimir-lu/fs2-interruptwhen-concurrency-issue/blob/master/src/test/scala/com/example/InterruptHandleBug.scala

A simpler example: 

```scala
(1 to 50).foreach { _ =>
      val stopSignal = Signal.constant[IO, Boolean](false)
      val gotError = new AtomicBoolean()
      Stream(42)
        .covary[IO]
        .evalMap(_ => IO.raiseError(new RuntimeException("BOOOM")))
        .interruptWhen(stopSignal)
        .handleErrorWith { _ =>
          gotError.set(true); Stream.empty
        }
        .compile
        .drain
        .unsafeRunSync()

      gotError.get() should equal(true)
}
```

If you remove `.interruptWhen` the test always passes. Otherwise errors are intermittent.

To me this seems quite similar to the issues described in #1021 and some of the comments in #1063 

I would have a look at the implementation of `.interruptWhen` but I'm not familiar with internals yet.

**Comment by vladimir-lu** [comment]
Indeed, not using a constant `Signal` makes the issue disappear.

Out of curiosity, what fixes this in 1.0? Is it because `.discrete` is defined as a stream of a single element?

**Comment by pchlupacek** [comment]
Hm, interesting, I thought that fix was already merged there. Could you perhaps close this and make another issue that Signal.constant is buggy and link this reference to it ? 
Thanks a lot for this help and findings.

**Comment by vladimir-lu** [comment]
Closing in favour of #1171
