### ISSUE TITLE
`Signal.constant` is nondeterminstic, for example when used with `.interruptWhen`

### ISSUE THREAD

**Issue by vladimir-lu** [functional-streams-for-scala/fs2#1171]
In 0.10.5, `Signal.constant` seems to cause nondeterminstic behaviour when running in parallel with a stream. I haven't yet got a more minimal example - but this seems to be the cause of #1170

**Comment by mpilquist** [comment]
@vladimir-lu What version of FS2 did you experience this with? It looks like `Signal.constant` was fixed in 0.10.5.

**Comment by mpilquist** [comment]
@vladimir-lu Pinging on this one.

**Comment by mpilquist** [comment]
Closing this for now but if you experience the same issue with 0.10.6 or 1.0.0, please reopen with some more info.
