### ISSUE TITLE
`observe` five times slower than `observe1` for same trivial `F[Unit]`

### ISSUE THREAD

**Issue by seigert** [functional-streams-for-scala/fs2#1177]
I've found this during profiling of some strange delays in pipeline. The simplest example is following code:
```scala
import cats.effect.IO
import cats.effect.Timer
import fs2.{ Stream, StreamApp }

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration._

object ObserveTest extends StreamApp[IO] {
  override def stream(args: List[String], requestShutdown: IO[Unit]): Stream[IO, StreamApp.ExitCode] =
    (Stream.awakeEvery[IO](1.second).take(20) >>
      Stream
        .eval(Timer[IO].clockMonotonic(NANOSECONDS))
        .observe1 { t =>
          Timer[IO].clockMonotonic(NANOSECONDS).map(n => println(s"observe1: ${n - t}"))
        }
        .observe {
          _.flatMap { t =>
            Stream.eval_(Timer[IO].clockMonotonic(NANOSECONDS).map(n => println(s"observe: ${n - t}")))
          }
        }).drain ++ Stream.emit(StreamApp.ExitCode.Success)
}
```
When run on my laptop the results are:
```
observe1: 1882733
observe: 17148614
observe1: 190469
observe: 1075020
observe1: 223795
observe: 1113877
observe1: 245559
observe: 1131262
...
observe1: 75126
observe: 520642
observe1: 107880
observe: 648547
```
Even if we skip first few lines, results are pretty consistent. Not that `observe1` timings are very fast, but overhead from `observe` is just too big. 

From a library user point of view I consider every `*` and `*1` methods as something that should provide similar performance results and that choice between one and another should be mostly convenient and/or cosmetic.

Edit: I'm using scala 2.12.6 with cats 1.1.0, cats-effect 1.0.0-RC1 and fs2 1.0.0-M1.

**Comment by mpilquist** [comment]
`observe` is an alias for `observeAsync(1)`, which involves asynchronous execution managed by a queue.

**Comment by seigert** [comment]
Yep, I know it. But if simple change from
```scala
val src: Stream[F, A] = ???
val snk: Queue[F, A] = ???
src.observe(snk.enqueue).drain
```
to
```scala
src.observe1(snk.enqueue1).drain
```
gonna give me five times faster stream processing time, than something is not right. May be just the function name.

**Comment by mpilquist** [comment]
How about a performance disclaimer in the ScalaDoc for observe? Something about how it is much more performance to model a synchronous observation as a A => F[Unit] than a Sink?

**Comment by seigert** [comment]
Yes, it would be very good. Even better with some FAQ point/example where usage of `observe` would provide some benefits (not clear for me now :( ).

On a slight offtopic note: is there any plans to add `wireTap`-like method when observing sink is never blocking source stream and skips elements/segments when consuming is slow? For monitoring/logging purposes.

**Comment by pchlupacek** [comment]
@mpilquist I think whats confusing here is that both implementations are completely different in their nature, yet they share name. 
I am thinking if should not rename observe1 to some similar combinator from cats.effects? Like they have flatTap for `F` not sure if flatTapF or just simple `tap` would work.

**Comment by SystemFw** [comment]
`observe1` should be `flatTap` I think :) , just like it is in cats, and I think @mpilquist said the same thing a few months ago @pchlupacek 

@seigert 

> Even better with some FAQ point/example where usage of observe would provide some benefits (not clear for me now :( ).

Consider this, `observe1` takes an `A => F[Unit]`. There's little point in using `observe` If your Sink it's just `evalMap(...)`, you want `observe1` . However consider a `Sink` with a different shape, for example `.collect { ...}`. This can't be represented by an `A => F[Unit]` and therefore you _have_ to use `observe`

**Comment by pchlupacek** [comment]
@SystemFw in fact, what I do not like is that the other sink is also the pure code, and you will need to understand internals to understand that the second option is actually so much less performant. Event for experienced user that may be hard to spot, when debugging issues.  

I think our story with Sinks and Channels is bad atm, and I think we shall perhaps consider to remove them from 1.0 alltogether if we couldn't fix it.

**Comment by SystemFw** [comment]
I've just added that disclaimer :)

Do note however that when transforming that `Sink` into `A => F[Unit]` you've lost some compositionality, imagine a more complicated Sink and the tradeoff will be worse

**Comment by SystemFw** [comment]
> observe1 should be flatTap I think :) , just like it is in cats, and I think @mpilquist said the same thing a few months ago

I take this back, it was `evalTap` actually, which is consistent with the naming choices and doesn't conflict with cats
