### ISSUE TITLE
`innterruptWhen` resets `fold` to zero

### ISSUE THREAD

**Issue by seigert** [functional-streams-for-scala/fs2#1179]
After `interruptWhen` triggers, `fold` emits it's zero value, even when it was accumulating values before interruption:
```scala
import cats.effect.IO
import cats.instances.int._
import fs2.{ Sink, Stream, StreamApp }
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration._

object InterruptFold extends StreamApp[IO] {
  override def stream(args: List[String], requestShutdown: IO[Unit]): fs2.Stream[IO, StreamApp.ExitCode] =
    Stream
      .unfold(0)(i => Some((i, i + 1)))
      .flatMap(Stream.emit(_).delayBy[IO](1.second))
      .interruptWhen(Stream.emit(true).delayBy[IO](15.seconds))
      .fold(0) { (t, i) =>
        print(s"$i "); t + i
      }
      .to(Sink.showLinesStdOut)
      .drain ++ Stream.emit(StreamApp.ExitCode.Success)
}
```
will output: `0 1 2 3 4 5 6 7 8 9 10 11 12 13 0`.

If we surround emitting stream with another one and join afterwards:
```scala
    Stream(
      Stream
        .unfold(0)(i => Some((i, i + 1)))
        .flatMap(Stream.emit(_).delayBy[IO](1.second))
        .interruptWhen(Stream.emit(true).delayBy[IO](15.seconds))
    ).join(1)
      .fold(0) { (t, i) =>
        print(s"$i "); t + i
      }
```
results will be of 'normal' fold: `0 1 2 3 4 5 6 7 8 9 10 11 12 13 91`.

Is it intended? And if so, is there a way to signal 'graceful' interruption with `Stream` or `Signal`?

Edit: scala 2.12.6, cats 1.1.0, cats-effect 1.0.0-RC2, fs2 1.0.0-M1

**Comment by pchlupacek** [comment]
I think second example is correct and works as expected. No idea why 0 is printed at the very last in first example.  I would expect nothing to be output after 13. @mpilquist any thoughts? 

As or the other question not sure what do you mean by gracefull interruption? Every interruption is nondeterministic, however interruption will never fail your stream, so whatever is after ++ of the interrupted stream is guaranteed to run.

**Comment by seigert** [comment]
@pchlupacek 
By 'graceful' interruption I've meant interruption of, say, `take(14)` instead of `interruptWhen(..)`. Also I expect result to be consistent between `fold(0)(_ + _)`, `scan(0)(_ + _).last` and `mapAccumulate(0)((t, i) => (t + i, i)).last`.

Right now with `take(..)` they return `91`, `Some(91)` and `Some((91, 13))` (consistent), but with `interruptWhen(..)` results are `0`, `Some(0)` and (not consistent) `None`.

Also, accumulator function executing, but not returning any value is just plain confusing. Imagine
```scala
val fold: Pipe[F, Int, Int] = _.observe1(i => ...).fold(0)(_ + _)
```
Not only results of such pipe will depend on type of interruptor chosen by user, but also elements observed by another effect in `observe1` won't be folded, sometimes.

**Comment by mpilquist** [comment]
@pchlupacek No, that's very strange. The implementation of `fold` is just about as simple as it gets when it comes to a recursive pull. No idea how interruption could be causing a `0` to be emitted. It's almost like something in the interrupt logic is holding on to an earlier Stream value.

**Comment by pchlupacek** [comment]
@seigert could you please verify that behaviour is same with fs2 0.10.5?

**Comment by seigert** [comment]
Don't know if this is related issue, but `interruptWhen` used before `flatMap` to infinite stream also interrupts such stream:
```scala
  Stream
      .emit(())
      .interruptWhen(Stream.emit(true).delayBy[IO](15.seconds))
      .flatMap { _ =>
        Stream
          .unfold(0)(i => Some((i, i + 1)))
          .flatMap(Stream.emit(_).delayBy[IO](1.second))
      }
```
This will stop emitting after 15 seconds (with `fold` reset too). This behaviour straight up contradicts documentation for the method :(.

**Comment by pchlupacek** [comment]
This is actually correct behaviour. essentially by flatMap you construct the stream, and interrupt will interrupt such stream event when the resulting code is `after` interruptWhen. If you want to guarantee that stream will get executed even after interruption you need to write this in terms of `append` instead of `flatMap`

What part of the documentation is contradictory? 

Re the fold reset, could you try the 0.10.5?

**Comment by seigert** [comment]
> What part of the documentation is contradictory?

From scaladoc to `interruptWhen`:
```
  * Caution: interruption is checked as elements are pulled from the returned stream.
  * As a result, streams which stop pulling from the returned stream end up
  * uninterrubtible. For example, `s.interruptWhen(s2).flatMap(_ => infiniteStream)`
  * will not be interrupted when `s2` is true because `s1.interruptWhen(s2)` is
  * never pulled for another element after the first element has been  emitted.
  * To fix, consider `s.flatMap(_ => infiniteStream).interruptWhen(s2)`.
```

> If you want to guarantee that stream will get executed even after interruption you need to write this in terms of append instead of flatMap

Let's say that I have following construct:
```scala
val halt: Signal[F, Boolean] = ???
val pipe: Pipe[F, A, B] = 
  _.interruptWhen(halt)
    .flatMap { a => 
       initB(a) ++ processB(a).interruptWhen(halt) ++ tailB(a)
    }
```
And due to specifics of protocol, I need to allow to `tailB(a)` to emit before total stream termination. How this can be achieved in terms of `append`? Will `onComplete` trigger for the inner stream?

> Re the fold reset, could you try the 0.10.5?

Yes I did, with the same results -- fold emits `0`:
```scala
Scheduler[IO](4)
  .flatMap { sch =>
  Stream
    .unfold(0)(i => Some((i, i + 1)))
    .flatMap(i => sch.delay(Stream.emit(i).covary[IO], 1.second))
    .interruptWhen(sch.delay(Stream.emit(true).covary[IO], 15.seconds))
  }
  .fold(0) { (t, i) =>
    print(s"$i "); t + i
  }
  .to(Sink.showLinesStdOut)
```

**Comment by pchlupacek** [comment]
cool thank you

**Comment by pchlupacek** [comment]
@seigert thanks for pointing out the discrepancy. It shall be clarified. In previous versions of fs2, this was actually the behaviour, which is not anymore.

**Comment by mpilquist** [comment]
@pchlupacek I think the problem with 0 being emitted is due to a bug in the interrupt context -- the stream is interrupted, we run through the code in `CompileScope.whenInterrupted`, and then we compute what to do next by calling `iCtx.whenInterrupted` -- at this point, we haven't yet emitted that weird 0. Just after this point though, the original `pull.uncons.flatMap { case None => emit(0); ... }` is executed.

**Comment by pchlupacek** [comment]
yeah would be something like that. I need to deep a bit in it to see a fix. I hope it won't be complicated

**Comment by pchlupacek** [comment]
yeah, `takeWhile` works completely differently than `interruptWhen`. The reason is as @mpilquist suggested that somehow we `rerun` head of the stream again.

**Comment by AdamChlupacek** [comment]
Hey, I have taken a look at this, In my opinion, everything is fine, the issue is print inside of a pure function. Due to some laziness etc the pure function gets called once again. I am curious what is the over all result of that is being print out with `.to(Sink.showLinesStdOut)`

**Comment by AdamChlupacek** [comment]
Never mind, I mean effect are certainly wrong to do in pure code, but this is another issue. 

The issue is with how uncons is implemented, ie the `StepLeg`, step leg sadly keeps its tail inside of the next `StepLeg`, and basically when we interrupt it, we do not have access to the `StepLeg` and instead we create completely new `fold` which does not get any data in it, thus it emits `0`. 

Will think about how to fix this.

**Comment by pchlupacek** [comment]
@mpilquist, @seigert what is the correct output you would like to see in case 1?

**Comment by mpilquist** [comment]
@pchlupacek Consider this pull:
```scala
def p: Pipe[IO, Int, Int] = {
  def loop(acc: Int, s: Stream[IO, Int]): Pull[IO, Int, Unit] =
    s.pull.uncons1.flatMap {
      case None => Pull.eval(IO(println("done, final: " + acc)))
      case Some((hd,tl)) => Pull.eval(IO(println("got: " + hd))) >> loop(acc + hd, tl)
    }
    in => loop(0, in).stream
}
```

Along with this stream:

```scala
Stream.unfold(0)(i => Some((i, i + 1))).
  flatMap(Stream.emit(_).delayBy[IO](1.second)).
  interruptWhen(Stream.emit(true).delayBy[IO](15.seconds)).
  through(p).
  drain
```

The output here is definitely wrong:
```
got: 0
got: 1
got: 2
got: 3
got: 4
got: 5
got: 6
got: 7
got: 8
got: 9
got: 10
got: 11
got: 12
got: 13
done, final: 0
```

The last line of output should either be `done, final: 91` or `got: 13` but definitely not `done, final: 0`.

**Comment by seigert** [comment]
@pchlupacek 
I think correct result is 91. But I also think that previous behaviour of `interruptWhen` was better and it should not interrupt stream nested in subsequent `flatMap` before it's exhaustion.

**Comment by pchlupacek** [comment]
@mpilquist @seigert thanks. 

I think we sort of figured the issue, and need to sleep over on it.

 It seems that current interruption implementation is unfortunately not compatible with any state that uses memory reference that is not guarded by `Ref`. 

The reason for this is, that we essentially (for various reasons) pre-compute the next stream in case of the interruption, and then continue with evaluation of the stream. 

When that stream get interrupted we sort of `emulate` termination of that stream with that precomputed step. 

This approach actually means that we lose the so far accumulated value, and start from the _beginning_, and that why you see the `0` like when stream was terminated. 

I am not sure now how hard is to fix that, doesn't look super easy. 

It will be our priority in next few days to somehow resolve this. 

@mpilquist @SystemFw any help// ideas appreciated.

**Comment by pchlupacek** [comment]
@mpilquist @SystemFw just from the first observation fix won't be easy. In fact we may need to completely reimplement interruption in fs2 interpreter, and I am not yet convinced what changes may be necessary (I think we may also need change encoding of FreeC to support interruption natively)

I am not sure if changes will be binary compatible (hopefully yes)

Given the amount of the work that may be needed, I just would like to know where we are at with FreeC-less interpreter, and would like to have opinion on next steps there as regard of 1.0 release and timing.

**Comment by mpilquist** [comment]
@pchlupacek That doesn't sound good. I'd first focus on a fix for series/1.0. We can backport to series/0.10 if possible. Supporting interruption in FreeC seems like a conflation of concerns but I'll wait to hear more about the proposed solution.

I haven't made any progress with the tagless interpreter. Kind of stuck on how to implement bracket. I don't think there's any chance that ends up in 1.0.

**Comment by pchlupacek** [comment]
@mpilquist ok so if I undestand correctly the core interpreter is amlost the same for 0.10 / 1.0 except with Segment removed right ? 

Now issue sort of goes down to architectural decision. We are throwing away currently any interrupted computation state on interrupt. Thats why we sort of start from the beginning and thats why we have that strange `0`. 

One way to fix this is also to have shared memory reference, that will get accesses on `None` case and as such will print out the correct summary so far accumulated by Pull. This may sort of sound strange, but in fact memory is a resource, and we are just not accessing it as resource when we are using recursion. So we could fix for now fold, mapAccumulate etc. implementations and just make sure that any accumulating stream that has `None` as the case shall hold its state in ref, instead in recursion. Thats easy fix, not sure how that is user friendly though. 

Other approach is to `inspect` running stream and find the point of interruption there. This is what we have been attempting several times pre 0.10final, and never went successful. The FreeC modification is just idea and may not actually help at all. 

Any thoughts?

**Comment by mpilquist** [comment]
> @mpilquist ok so if I undestand correctly the core interpreter is amlost the same for 0.10 / 1.0 except with Segment removed right ?

Yep

> One way to fix this is also to have shared memory reference, that will get accesses on None case and as such will print out the correct summary so far accumulated by Pull.

If I understand this correct, you are suggesting making such changes to each of these stateful combinators. If so, I'd rather not do so b/c recursive pulls are used extensively in user libraries and applications, and all such uses would need similar treatment. Instead we need a solution that works without changing recursive pulls.

**Comment by pchlupacek** [comment]
Yeah you get it correct.

**Comment by pchlupacek** [comment]
@seigert there is PR with fix. Would be excellent if you can give try to that branch. t/y.

**Comment by seigert** [comment]
@pchlupacek I've tried my cases against `1.0.0-M3`, everything looks good!

**Comment by pchlupacek** [comment]
cool, excellent
