### ISSUE TITLE
Inductive cats-effect typeclass instances for Stream

### ISSUE THREAD

**Issue by djspiewak** [functional-streams-for-scala/fs2#1180]
- [x] `Sync[Stream[F, ?]]` given `Sync[F]`
- [ ] `LiftIO[Stream[F, ?]]` given `LiftIO[F]`
- [ ] `Async[Stream[F, ?]]` given `Async[F]`
- [ ] `Effect[Stream[F, ?]]` given `Effect[F]`
- [ ] `Concurrent[Stream[F, ?]]` given `Concurrent[F]`
- [ ] `ConcurrentEffect[Stream[F, ?]]` given `ConcurrentEffect[F]`

Only the first exists. All are useful. It's very difficult for a third-party to provide these without caveats due to implicit prioritization and conflicts, so it's worth having them in the library if at all possible.

**Comment by mpilquist** [comment]
Note the Sync instance is gone on series/1.0 because I don’t know how to provide a lawful implementation of Bracket for Stream. If we can solve that issue, I’m on board with the full set of instances.

**Comment by djspiewak** [comment]
Oh right, because effect bracket is fundamentally different from stream bracket. :-/ I forgot about that.

**Comment by mpilquist** [comment]
Going to close this for now, as I don't know of a way to implement Bracket for Stream. If someone comes up with an implementation, please reopen or submit a PR.
