### ISSUE TITLE
Suggestion: njoin instead of join

### ISSUE THREAD

**Issue by djspiewak** [functional-streams-for-scala/fs2#1185]
The problem with `join` as a name is it's being added implicitly, meaning that anyone who is using fs2 with scalaz and shims in scope is going to be unable to access it without explicitly calling `new Stream.InvariantOps(...)`, which is less than ideal. Additionally, the word `join` has a particular meaning in the context of monadic functional programming, and while this function is *close* to that meaning, it's different in some important ways. `njoin` doesn't suffer from any of these issues.

Obviously this would be an incompatible change.

**Comment by djspiewak** [comment]
Ah, if it's not anymore added implicitly, then there's certainly less worry about it locking things out (as it does in 0.10). So this just reduces to whether or not `join = flatMap(identity)` is a strong enough association in Scala that it's worth using `njoin` instead. I don't have a *super* strong opinion on that front, though I have a slight preference for `njoin` on those grounds.

**Comment by mpilquist** [comment]
`parJoin`/`parJoinUnbounded`? Plays off `parTraverse`, etc.
