### ISSUE TITLE
Decide what to do with StreamApp

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#1194]
Cats-effect now defines [IOApp](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/IOApp.scala). We should decide whether we still need `StreamApp` in light of this.

**Comment by pchlupacek** [comment]
I am sort of inclining we shall leave it to cats.effects.

**Comment by SystemFw** [comment]
I'm also fine with having it in cats effect, I don't think a `compile.drain` is too much of an issue from the user perspective.

I do however wonder whether there are any interactions with #1140  wrt to the shutdown action

**Comment by mpilquist** [comment]
It looks like `IOApp` doesn't register a shutdown hook at all. If it did register one, it could cancel the main fiber upon receiving a shutdown signal, which would then trigger a stream that was compiled to shutdown correctly, releasing all resources.

**Comment by djspiewak** [comment]
@mpilquist Are we sure that cancelation propagated up from the compiled `IO` is going to maintained the appropriate properties in `Stream`'s cancelation? I'm thinking of the mismatch between `bracket` properties.

**Comment by mpilquist** [comment]
Yep, because we implement it by closing the root scope via an `F.bracket` registered finalizer. When the root scope is closed, the stream resources ends up getting finalized according to stream semantics, not Bracket[F] semantics. https://github.com/functional-streams-for-scala/fs2/blob/series/1.0/core/shared/src/main/scala/fs2/internal/Algebra.scala#L166-L167

**Comment by djspiewak** [comment]
In that case, then I'm 👍 for just relying on `IOApp` instead.
