### ISSUE TITLE
Create scalafix rules to implement as much of the 0.10 to 1.0 upgrade as possible

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#1196]
For starters, it would be nice to handle the various term and type renames described in https://github.com/functional-streams-for-scala/fs2/pull/1195/files.

I spent a few hours on getting a few simple renames working here: https://github.com/functional-streams-for-scala/fs2/compare/series/1.0...mpilquist:topic/scalafix?expand=1

I also added support for `Stream.bracket` changes.

**Comment by olafurpg** [comment]
Very cool! A few comments

* note that `ctx.replaceTree` replaces the full tree with new tokens. If you expect to run further rewrites for the subtrees inside `$aquire` and `$release` then this approach will produce unexpected results. Example case where this might be a problem (but I have no idea if that code makes sense): 
```scala
Stream.bracket(IO(1))(Stream(_), i =>  Stream.bracket(IO(1))(Stream(_), i => IO.unit))
```
* `case Term.Select(_, bracket(_)) =>` might be possible to simplify to `case bracket(_: Term.Name) =>`, I don't know if it works in v0.5.10 but it will work in v0.6 at least.
* heads ups, the method symbol format will change in the upcoming v0.6 release. Example, the method `_root_.fs2.Stream.InvariantOps#observe1(Lscala/Function1;Lcats/Functor;)Lfs2/internal/FreeC;.` becomes `fs2/Stream.InvariantOps#observe1().` instead. The new method symbols are both easier on the eye and also have the benefit of being possible to produce with only a parser (no compiler). The changelog will document further breaking changes, and there is also a migration script for scalafix.g8 generated project https://github.com/scalacenter/scalafix.g8/tree/master/scalafix

**Comment by olafurpg** [comment]
I hope to have a stable Scalafix v0.6 release out this August, with a revamp of the documentation both for end-users and rule authors. I'm happy to help migrating existing rules to the new API so don't hesitate to ping me.

**Comment by SystemFw** [comment]
Thanks Olaf :)
