### ISSUE TITLE
Performance Problem in Segment#splitAt

### ISSUE THREAD

**Issue by eikek** [functional-streams-for-scala/fs2#1200]
Hello, 
I'm experiencing strange performance problems in my app that I got now tracked down to code in `Segment`.  The scaladoc on `Segment` says it idoesn't define `equals`; but the `SingleChunk` class is defined as a case class and so there is an implicit equals method added.
Now, the line 1393 in `Segment` (current series/0.10) compares an segment against `Segment.empty`. Since `Segment.empty` is also defined as a `SingleChunk` the equals method goes down comparing the two chunk which run `toVector` on the other chunk that may not be empty. This makes the `Chunk.toVector` a very hot method in my use case.

I removed the `case` modifier and the code that took > 3s before is now down to 200ms.

**Comment by mpilquist** [comment]
#1202 bypasses the conversion to vector upon calling equals, though I still think it's wrong for `Segment` to be using `==` internally when we know `Segment` claims not to implement `equals`.

**Comment by mpilquist** [comment]
Fixed by #1203
