### ISSUE TITLE
Improve Stream#observe

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#1208]
Find the way how to improve current observe semantics and potentially its performance

**Comment by SystemFw** [comment]
https://github.com/functional-streams-for-scala/fs2/issues/1206#issuecomment-409979686

**Comment by pchlupacek** [comment]
@SystemFw sorry to not wait for you in this one :-) But I sort of felt guilty to bring up kill issue and then asking you open one issue for it :-) 

Anyhow, won't just simple fan-out of the sinks will be somehow useful? Do we really need to commit the chunks as they are observed by sinks ?

**Comment by SystemFw** [comment]
heh that's fine :P

> Anyhow, won't just simple fan-out of the sinks will be somehow useful? Do we really need to commit the chunks as they are observed by sinks ?

This is exactly the question I've been asking myself. My first instinct is to say that yes, fanout is enough, however then makes the whole thing very push-based, and I'm not sure that won't bring unexpected semantics as well. It's definitely an option though, I agree

**Comment by pchlupacek** [comment]
My point if we make observer `complex` enough, ppl would rather switch to evalTap and use sinks only in place where there is no other solution.

**Comment by pchlupacek** [comment]
How about this : 
```scala 
def observe(uncomitted: Int)(sinks: Sink[F, O]*):Stream[F, Unit] 

// then

s1.observe(100)(
 sink1
 , sink2
 , channel1 andThen sink3
 , .... 
)


```

Where individual sinks will be presented by maximum of `uncommitted` `O` in chunks, possibly splitting chunks as necessary. If there will be slower observers, the faster ones' won't get another batch until slow ones will ask for more....

**Comment by pchlupacek** [comment]
Advanatage of this is that you can write all programs like you have done today, just with very slight change in syntax, and these will be correct ones. 
Also, you will have configurable size of commit, and still with `Pull` semantics
Obviously when all sinks die, program terminates. When one sink die, program continues. On failure of one sink program fails

**Comment by pchlupacek** [comment]
I have thought about this a more, and I think we can keep observe signature as it is, and instead introduce new combinator lets call it `distribute` (with signature above and together) with Joint implement it: 

```

def observe(sink: Sink[F, O]):Stream[F,O] = {
  Stream.eval(async.joint).flatMap { join =>
    joint.stream concurrently(self.distribute(
      sink
     , joint.sink
    ))
  }
}
```

Also I don't think so (uncomitted : Long) is required in `distributed` signature, instead it will just operate on chunks, giving it much more great deal of flexibility and simpler implementation as well.

**Comment by mpilquist** [comment]
@SystemFw OK to close this one now?

**Comment by SystemFw** [comment]
I think it has probably bitrotten, yeah
