### ISSUE TITLE
Seq is a poor choice for the block value type.

### ISSUE THREAD

**Issue by nuttycom** [functional-streams-for-scala/fs2#121]
Using Seq as the block value type inhibits users from being able to reason about the performance characteristics of operations on blocks of data. I think it would be preferable to either choose a single, specific block type (say Vector) or else to use implicit typeclass constraints and/or explicit dictionaries to provide the operations that are available for block values. Seq is a very muddled type, and doesn't seem to me to really have a place in so principled a library as scalaz-stream.

**Comment by pchiusano** [comment]
Closing. In the new design, there is a separate `Chunk` type, which is strict and supports random access. If you want laziness / fusion, you use `Stream`. 

You can create a `Chunk` from a `Seq` of course, but if that `Seq` is not already `IndexedSeq` it will be copied. (The copying is done lazily though, on first random access. If only sequential access is used there's no need to copy.)

It might be interesting to play with different representations of `Chunk` that are lazier but we are punting on that for now.
