### ISSUE TITLE
Suggestion: Non-CPU ExecutionContexts should not be implicit

### ISSUE THREAD

**Issue by djspiewak** [functional-streams-for-scala/fs2#1219]
This is relevant to `fs2.io` in several places (e.g. `stdoutAsync`). I'm very much of the persuasion that the implicit `ExecutionContext` pattern is *good*, but only because there's always a sane default: the CPU pool. This is obviously not what is wanted or needed for the `stdinAsync` and `stdoutAsync` sinks. It's clearly no worse than `stdin` or `stdout`, but it's also not… great.

I think it would be better to remove the `implicit` modifier here, and anywhere else where we're taking a blocking pool. Non-CPU pools should be taken explicitly by convention, IMO, while the CPU pool alone gets the `implicit` treatment.

Thoughts?

**Comment by mpilquist** [comment]
I think it's already removed on series/1.0, though note we're about to make another change here - just waiting on https://github.com/typelevel/cats-effect/pull/289. In essence, we'll take a `ContextShift[F]` and call `cs.evalOn(taskThatBlocks)`.

**Comment by SystemFw** [comment]
in 1.0, the "sane default" is Timer, so you take an implicit Timer and an explicit Ec for blocking pools.

**Comment by djspiewak** [comment]
I'm a fan of all the things. Closing this since y'all are way ahead of me.
