### ISSUE TITLE
Slow parallel processing

### ISSUE THREAD

**Issue by jendakol** [functional-streams-for-scala/fs2#1226]
Hello guys, I'm afraid I've run into similar issue as was #977.
My scenario is actually very similar as there: streaming big data from sharded database, that means running multiple DB queries in parallel where each query returns some data (potentially GBs in production so we need to it have streamed).  
There is a huge difference between processing this data with `Observable` (Monix) and FS2 `Stream`, visible even in unit tests with some funny-small data. Based on the finding I've implemented a [repo](https://github.com/jendakol/streaming-benchmark) with benchmark and the scenario described more into deep.  
The actual code is quite short and naive but something has to be wrong there:
```scala
    Stream
      .range(1, items)
      .mapAsyncUnordered[IO, Array[Byte]](parallelism) { _ =>
        IO {
          DataGenerator.get(size)
        }
      }
      .map(_.length) // don't want to drain the stream so I "process" the data this way
      .reduce(_ + _)
      .compile
      .toList
      .runAndWait
```
The same implementation with `Observable` is about 30 times faster:
```scala
    Observable
      .range(1, items)
      .mapParallelUnordered[Array[Byte]](parallelism) { _ =>
        Task {
          DataGenerator.get(size)
        }
      }
      .map(_.length)
      .reduce(_ + _)
      .toListL
      .runAndWait
```

Results (shortened, see the repo):
```
[info] Benchmark                            (items)  (parallelism)  (size)  (threads)  Mode  Cnt    Score   Error  Units
[info] StreamingBenchmark.testFs2IO             500              5   10000         10  avgt    2   90,676          ms/op
[info] StreamingBenchmark.testMonix             500              5   10000         10  avgt    2    3,665          ms/op
```

What am I doing wrong? :-)

P.S. I am currently running full test with current setup (as is in the repo) but it will take few hours. I'll post it here later but intermediate results show no surprise.

**Comment by jendakol** [comment]
As I've promised, here are results for current test settings:
```
[info] Benchmark                            (items)  (parallelism)  (size)  (threads)  Mode  Cnt     Score    Error  Units
[info] StreamingBenchmark.testFs2FromMonix      500             10    1000         10  avgt   20    17,905 ±  0,248  ms/op
[info] StreamingBenchmark.testFs2FromMonix      500             10   10000         10  avgt   20    17,698 ±  0,165  ms/op
[info] StreamingBenchmark.testFs2FromMonix     1000             10    1000         10  avgt   20    36,730 ±  0,518  ms/op
[info] StreamingBenchmark.testFs2FromMonix     1000             10   10000         10  avgt   20    37,042 ±  0,369  ms/op
[info] StreamingBenchmark.testFs2FromMonix     5000             10    1000         10  avgt   20   181,284 ±  2,563  ms/op
[info] StreamingBenchmark.testFs2FromMonix     5000             10   10000         10  avgt   20   174,722 ±  1,155  ms/op
[info] StreamingBenchmark.testFs2IO             500             10    1000         10  avgt   20   171,731 ±  1,701  ms/op
[info] StreamingBenchmark.testFs2IO             500             10   10000         10  avgt   20   172,712 ±  1,802  ms/op
[info] StreamingBenchmark.testFs2IO            1000             10    1000         10  avgt   20   349,657 ±  4,402  ms/op
[info] StreamingBenchmark.testFs2IO            1000             10   10000         10  avgt   20   352,718 ±  2,779  ms/op
[info] StreamingBenchmark.testFs2IO            5000             10    1000         10  avgt   20  1730,664 ± 16,963  ms/op
[info] StreamingBenchmark.testFs2IO            5000             10   10000         10  avgt   20  1745,693 ± 22,126  ms/op
[info] StreamingBenchmark.testFs2Task           500             10    1000         10  avgt   20   207,058 ±  3,564  ms/op
[info] StreamingBenchmark.testFs2Task           500             10   10000         10  avgt   20   207,450 ±  4,449  ms/op
[info] StreamingBenchmark.testFs2Task          1000             10    1000         10  avgt   20   412,818 ±  4,315  ms/op
[info] StreamingBenchmark.testFs2Task          1000             10   10000         10  avgt   20   401,606 ±  6,903  ms/op
[info] StreamingBenchmark.testFs2Task          5000             10    1000         10  avgt   20  2052,445 ± 23,115  ms/op
[info] StreamingBenchmark.testFs2Task          5000             10   10000         10  avgt   20  2049,175 ± 31,826  ms/op
[info] StreamingBenchmark.testMonix             500             10    1000         10  avgt   20     2,278 ±  0,136  ms/op
[info] StreamingBenchmark.testMonix             500             10   10000         10  avgt   20     2,912 ±  0,093  ms/op
[info] StreamingBenchmark.testMonix            1000             10    1000         10  avgt   20     4,372 ±  0,086  ms/op
[info] StreamingBenchmark.testMonix            1000             10   10000         10  avgt   20     4,558 ±  0,194  ms/op
[info] StreamingBenchmark.testMonix            5000             10    1000         10  avgt   20    19,841 ±  0,527  ms/op
[info] StreamingBenchmark.testMonix            5000             10   10000         10  avgt   20    19,108 ±  0,298  ms/op
```
(I intentionally don't add HW configuration because it doesn't seem relevant to me - my point is not about absolute _time_ but about it's many times slower than it should be.)

**Comment by pchlupacek** [comment]
@jendakol I think this is related to fairly ineffective implementation of `mapAsyncUnordered` which is implemented as marge of single-streams with parJoin. Thanks for reporting this. 
We shall look on this before 1.x release to improve the implementation, to make this as fast as possible

**Comment by jendakol** [comment]
No stress but when do you expect to release it? :-) I guess the deadline presented at https://github.com/functional-streams-for-scala/fs2/milestone/13 is not valid anymore ;-)
BTW I'd be glad to help you with fixing this but it's far out of my skills :smiley:

**Comment by pchlupacek** [comment]
I hope this will make its way in 1.0. So guess like september 18

**Comment by pchlupacek** [comment]
@jendakol also if there is quick workaround required you can try something in these terms : 

```scala

val s: Stream[F, O] = ???
val def myWork(o: O): F[Unit] = ???

Stream.eval(Semaphore(MaxRunningInParallel)).flatMap { guard =>
 s.evalMap { o => 
  guard.acquire >>
  Concurrent[F].start(myWork.attempt >> guard.release) 
 }
}

```

That would likely give you the fastest implementation possible. 

If you will by chance end up with this solution, PR is always welcome :-)

**Comment by SystemFw** [comment]
I think that will only work properly if `myWork` is `F[Unit]`

**Comment by pchlupacek** [comment]
ah ok then this will require additional queue. : 

```
val s: Stream[F, O] = ???
val def myWork(o: O): F[Unit] = ???

Stream.eval(Semaphore(MaxRunningInParallel)).flatMap { guard =>
Stream.eval(async.unboundedQueue[A]).flatMap { queue =>
 queue.dequeue.concurrently(
   s.evalMap { o => 
    guard.acquire >>
    Concurrent[F].start(myWork(o).flatMap(queue.enqueue1).attempt >> guard.release) 
  }
 )
}}


```

still the performance will be "almost" identical to one with `F[Unit]`

**Comment by pchlupacek** [comment]
@SystemFw perhaps we shall introduce `Tap` version of the combinator for `F[Unit]` case that will be still a bit "faster" :-)

**Comment by SystemFw** [comment]
Yeah I thought so too but tbh I'd like to see more numbers justifying a proliferation of combinators :)

**Comment by pchlupacek** [comment]
@SystemFw yeh. I bet we can sort of believe that ppl did that already as a reasoning why cats have `traverse` and `traverse_` . By enqueuing to queue, we in fact create non-negligible contention point, that may be completely unnecessary :-) 

Now I have idea, if, we couldn't somehow use this new combinator to actually define parJoin :-)

**Comment by jendakol** [comment]
TBH I'm kind of a lost in your discussion however I tried proposed workaround:
```scala
    val s = Stream.range(1, items)

    import cats.syntax.all._

    Stream
      .eval(Semaphore[IO](parallelism))
      .flatMap { guard =>
        Stream.eval(fs2.async.unboundedQueue[IO, Array[Byte]]).flatMap { queue =>
          queue.dequeue.concurrently {
            s.evalMap { _ =>
              guard.decrement >>
                Concurrent[IO].start {
                  IO {
                    DataGenerator.get(size)
                  }.flatMap(queue.enqueue1).attempt >> guard.increment
                }
            }
          }
        }
      }
      .map(_.length)
      .reduce(_ + _)
      .compile
      .toList
      .runAndWait
```
Unfortunately the code never finished, I guess there is deadlock somewhere :smile:

**Comment by SystemFw** [comment]
there's no deadlock but you basically wait on the empty queue forever.

```scala
 Stream
      .eval(Semaphore[IO](parallelism))
      .flatMap { guard =>
        Stream.eval(fs2.async.unboundedQueue[IO, Option[Array[Byte]]]).flatMap { queue =>
          queue.dequeue.unNoneTerminate.concurrently {
            s.evalMap { _ =>
              guard.decrement >>
                Concurrent[IO].start {
                  IO {
                    DataGenerator.get(size)
                  }.flatMap(x => queue.enqueue1(x.some)).attempt >> guard.increment
                }
            }
          }
        }
      }
      .map(_.length)
      .reduce(_ + _)
      .compile
      .toList
      .runAndWait
```

try this

**Comment by pchlupacek** [comment]
@SystemFw the problem with join is that it has a lot of machinery, like interruption, resource / scope cleanup and cetera. And for one element Streams, this may be significant cost.

**Comment by SystemFw** [comment]
mm maybe you're right, we can experiment and see how much we can get away with for `mapAsyncUnordered`

**Comment by pchlupacek** [comment]
just a remark to your code, I think you have to add finalizer `.onFinlaize(queue.enqueue1(None))`

**Comment by SystemFw** [comment]
yeah, just realised that :joy:

**Comment by jendakol** [comment]
@SystemFw Yeah, that's what I thought - the queue generates an infinite stream. I'm not experienced enough with FS2 to know `unNoneTerminate` but it's great.

Thx guys, I've finally got it working. I've rewritten it to use for-comprehension (for my better understanding):
```scala
    val itemsStream: Stream[Pure, Int] = Stream.range(1, items)

    val resultsStream: Stream[IO, Int] = for {
      semaphore <- Stream.eval(Semaphore[IO](parallelism))
      queue <- Stream.eval(fs2.async.unboundedQueue[IO, Option[Array[Byte]]])
      results <- {
        queue.dequeue.unNoneTerminate.concurrently[Unit] {
          itemsStream
            .evalMap[IO, Unit] { _ =>
              for {
                _ <- semaphore.decrement
                _ <- {
                  Concurrent[IO].start {
                    for {
                      data <- IO { DataGenerator.get(size) }
                      _ <- queue.enqueue1(data.some)
                      _ <- semaphore.increment
                    } yield ()
                  }
                }
              } yield ()
            }
            .onFinalize(queue.enqueue1(None))
        }
      }
    } yield {
      results.length
    }

    resultsStream.reduce(_ + _).compile.toList.runAndWait
```
This works however results are still quite sad compared to `Observable`:
```
[info] Benchmark                             (items)  (parallelism)  (size)  (threads)  Mode  Cnt   Score   Error  Units
[info] StreamingBenchmark.testFs2FromMonix      1000             10    1000         10  avgt   10  33,436 ± 1,706  ms/op
[info] StreamingBenchmark.testFs2Workaround     1000             10    1000         10  avgt   10  38,476 ± 2,146  ms/op
[info] StreamingBenchmark.testMonix             1000             10    1000         10  avgt   10   5,949 ± 1,681  ms/op
```

**Comment by SystemFw** [comment]
I would recommend again `for` because very often you want to mix other combinators that aren't `flatMap`, which isn't well supported (I also think they add a lot of noise in this case, but that's up to you). 

Important: you need to handle errors in `data`, or you'll get stuck, you need to look at `guarantee` or at least `attempt` to make sure that the semaphore is `increment`ed regardless. (also in that form, errors are swallowed, you need more machinery to make sure they are propagated down-stream).

Tbh I think that if you compare to `Observable`, you'll often see a perf hit, for example it might be because Observable uses impure queues under the hood. I'm kinda more interested if the performance you are getting is good for your use case, or it's giving you problems.

**Comment by pchlupacek** [comment]
I think we could still do a bit better. There is still a lot of machinery involved with every  item. we will certainly get benefit if this will operate on chunks instead on individual elements.

**Comment by pchlupacek** [comment]
@SystemFw do you also know by chynce, if monix Observable is somehow controlling the concurrency? b/c that may account for a lot of overhead, including the fact that we again synchronize on resulting value.

**Comment by SystemFw** [comment]
Good point, but I don't know about that

**Comment by pchlupacek** [comment]
@SystemFw it seems that Observable doesn't do actually anything. I couldn't see anything to control flow, and docs says that back-pressure must be somehow controlled. So I suspect if you put 10G tasks on it, it will OOM w/o any external control.

**Comment by pchlupacek** [comment]
interesting. is your cpu btw fully spining when you do fs2 tests?

**Comment by pchlupacek** [comment]
I think we still can improve this a bit, but only when we will lift some constrains, i.e. concurrency limits, and collecting the results. you may experiment with where the actual bottleneck is further, i.e. by removing semaphore or by removing the result quueue. I bet queue will be bottleneck. do you somehow collect results in monix code ?

**Comment by jendakol** [comment]
No, it's far from "fully spinning", I have all cores cca 40% (after killing the benchmark it fell to 10%).

The monix code is almost identical to original FS2 one (see [original post](#issue-351593687)).

**Comment by jendakol** [comment]
I see, that's quite logical.
My use case is described in the original post as well as the Monix implementation.
I am not sure what are you asking about.
* The resulting library will not collect any results but provide stream of data to "user". Our own first usage counts with passing the stream to http4s (thus we need FS2 at the end).
* The benchmark does not collect the data directly too but tranforms them into some other form (_length_) which is the same from your POV I guess.
* If you mean "does your computation has any results" then the answer is **yes**, it's a query to DB (select)

**Comment by pchlupacek** [comment]
@jendakol thanks for the info. I'll think if there is something we can do about that.

**Comment by jendakol** [comment]
@pchlupacek It seems great but TBH this is what I expected `mapAsyncUnordered` to be :-) Could you please explain (maybe on examples) how these two methods differ?  

However, this improvement will be much more important for the benchmark than for my real use-case. In "reality" there will be IO operation (DB query) taking few seconds instead of immediate result so the overhead may be less relevant. But still, this needs to be fixed/improved :-)

**Comment by pchlupacek** [comment]
the new constructor allows you to sum chunks in parallel (10 threads) and then sum the results when each of them terminate. Whereas the solution with mapAsyncUnordered still basically synchronises you on one queue, as such you may not ever utilize full cpu potential. 

Is perfectly ok if you operation is just A => F[B], still you will do evalMap and as you do it in parallel, you may fine-tune precisely cpu utilization. 

As a side note, this also does much less context switching, so again, the CPU may be much better utilized.

**Comment by jendakol** [comment]
OK but what is point of existence of `mapAsyncUnordered` then? In which scenario it would be better?

**Comment by pchlupacek** [comment]
I think we may actually review that before 1.0 final :-)

**Comment by pchlupacek** [comment]
@jendakol balance/broadcast are in #1235. I will still work on implementation of mapAsyncUnordered, but perhaps you may try with RC1, which will be released with these, if you saw performance improvement.

**Comment by pchlupacek** [comment]
lets close this, @jendakol feel free to reopen, if you will see any perf. issues again :-)
