### ISSUE TITLE
publish site to fs2.io

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#1234]
Update pages so they can be used on fs2.io domain

**Comment by mpilquist** [comment]
Do we own that domain? Paul registered fs2.co a few years ago and that redirects to our github page.

**Comment by pchlupacek** [comment]
Yes we own fs2.io. We only need to fix the gh-pages to make it live. currently there are some issues with links and styles (the are absolute instead of relative). I am not perfect on gh-pages and all microsfite chain, perhaps @gvolpe could help there. Other than that fs2.io is already redirected, so once issues are resolved it can be referenced on the github.

**Comment by gvolpe** [comment]
I have a website running on Github pages with a custom domain (and thanks to this comment I realized it was broken :smile: ). 

All you have to do is setup a custom domain (prefer a CNAME file eg. [here](https://github.com/SmartBackpacker/website/blob/master/docs/CNAME)) and create the corresponding DNS records for Github pages (see [here](https://help.github.com/articles/setting-up-an-apex-domain/)).

Ping me here or on Gitter if I can help with anything :)

**Comment by pchlupacek** [comment]
I think we tested that already. Hey, how about we will do it again, you will see whats broken and we can find a way how to fix that ?

**Comment by gvolpe** [comment]
Sure, let me know @pchlupacek . The reason my website was broken was because Github changed the IP addresses that were set for the DNS, maybe you have the same issue?
