### ISSUE TITLE
Scheduler.retry/Stream.retry has misnamed parameter

### ISSUE THREAD

**Issue by drobert** [functional-streams-for-scala/fs2#1252]
In the 0.10.x line, `Scheduler.retry` has a parameter named `maxRetries` (same parameter in `Stream.retry` in the 1.0.x line). However:
1. it is actually operating as `maxAttempts`
2. has surprising behavior when zero is supplied

The parameter itself should be renamed to `maxAttempts` to reflect the true behavior.
For the latter, if a value < 1 is given, the error is ultimately `[fs2] impossible: empty stream in retry`. It would be valuable to be given a more accurate/understandable error message such as `cannot construct a retriable stream with maxAttempts < 1`

**Comment by SystemFw** [comment]
@drobert  Do you feel like opening a PR? :)

**Comment by SystemFw** [comment]
I guess we could also `assert` that it should be `> 0` like in e.g. `Semaphore`

**Comment by drobert** [comment]
I can probably do that, but I'm pretty unavailable before Tuesday. If this is something that should be in before 1.0 final (which it may given it's a parameter name change) I wouldn't block on me.
