### ISSUE TITLE
Consider make `Chunk.concat` use `SemigroupK` or something similar

### ISSUE THREAD

**Issue by jilen** [functional-streams-for-scala/fs2#1256]
So that one could customize the `concat` behavior for purpose 

For example, decoding very large `Chunk[Byte]`, user probably want to split the chunk into `frames` which involves lots of `concat` .

**Comment by mpilquist** [comment]
Thanks for the suggestion! Are you saying that any place in the library we use `Chunk.concat`, instead we should take a `SemigroupK[Chunk]` argument instead? I don't think this would help as we shouldn't be using type classes as mechanisms for arbitrary customization -- there should be a single `SemigroupK[Chunk]` instance -- not unique ones based on the use case.

Could you provide a sample program or use case where the current `Chunk.concat` behavior is problematic or requires customization? We might be able to provide an alternative that addresses your use case.

**Comment by jilen** [comment]
@mpilquist Actually what I did is decoding large length encode byte chunk like this
```scala
def decodePacket[F[_]](src: Stream[F, Byte]) = {

    @annotation.tailrec
    def splitPackets(packets: Vector[Packet], c: Chunk[Byte]): (Vector[Packet], Chunk[Byte]) = {
      if(c.size < 4) {
        (packets, c)
      } else {
        val lenBytes = c.take(4).toBytes
        val len = ((0xFF & lenBytes(0)) << 24) | ((0xFF & lenBytes(1)) << 16) |
        ((0xFF & lenBytes(2)) << 8) | (0xFF & lenBytes(3));
        if(c.size < 4 + len) {
          (packets, c)
        } else {
          val packetBytes = c.drop(4).take(len).toBytes.toArray
          splitPackets(
            packets :+ Packet(packetBytes),
            c.drop(4 + len)
          )
        }
      }
    }

    def loop(prev: Chunk[Byte], s: Stream[F, Byte]): Pull[F, Packet, Unit] = {
      s.pull.unconsChunk.flatMap {
        case Some((hd, tl)) =>
          val concated = Chunk.concat(Seq(prev, hd))
          val (packets, remain) = splitPackets(Vector.empty, concated)
          Pull.output(Chunk.vector(packets)) >> loop(remain, tl)
        case None =>
          Pull.done
      }
    }
  }
```
Have not test the performance yet, but I am worried about  `Chunk.concat`'s performance for large byte chunk

**Comment by jilen** [comment]
By the way, why `Chunk` have no  `append` api ?

**Comment by jilen** [comment]
@mpilquist Thanks for your advice
