### ISSUE TITLE
Restore `Queue#dequeueBatch1`?

### ISSUE THREAD

**Issue by rossabaker** [functional-streams-for-scala/fs2#1273]
`dequeueBatch1` was [removed](https://github.com/functional-streams-for-scala/fs2/commit/4ddd75a2dc032b7604dc1205c86d7d6adc993859#diff-6ae893d277869fb64e113ba04fbd8b59L67) in #1258.

The closest replacement I've found is `Stream(size).through(queue.dequeueBatch).chunks.compile.lastOrError`.  Was there a strong reason to remove it?

**Comment by mpilquist** [comment]
Fixed by #1274 -- take a look at the new `dequeueChunk1(maxSize)`

**Comment by rossabaker** [comment]
I didn't write the test, but it looks like the intent is to [ensure that `Close` is the last message](https://github.com/http4s/http4s/blob/ec1e0600ece470815e01cb093c756830f4c9ca76/blaze-core/src/test/scala/org/http4s/blazecore/websocket/Http4sWSStageSpec.scala#L86) in a reasonable amount of time.  `pollBatchOutpubound` calls [this](https://github.com/http4s/http4s/blob/master/blaze-core/src/test/scala/org/http4s/blazecore/websocket/WSTestHead.scala#L66), which used to call `dequeueBatch1`.  If I understand the test, we could have polled for these messages indvidually, raced against a timeout, just as well.

It was moderately annoying for it to disappear, but if it cleans up the internals, I can live without it.
