### ISSUE TITLE
Should acquiring a resource in a leased scope result in the new resource being part of the lease

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#1283]
Currently, if you lease a scope and then acquire a resource in the scope, the newly acquired resource is not part of the lease. The lease API would be significantly more expressive if acquired resources were leased automatically to any open leases on their enclosing scope.

One use case is extending the lifetime of resources over an append -- e.g., extending resources of `s1` over the overall stream in `s1 ++ s2`.

This doesn't work currently:
```scala
Stream.getScope[IO].flatMap(scope => Stream.bracket(scope.lease)(_.map(_.cancel.void).getOrElse(IO.pure(()))).flatMap(_ => r ++ Stream.eval(IO(println("after")))))
```

This kinda works but only for certain types of streams -- it relies on `r` acquiring resources before the first emitted chunk and then acquiring no other resources. Hence, it isn't very useful.

```scala
val r = Stream.bracket(IO(println("acquired")))(_ => IO(println("released")))
Stream.getScope[IO].flatMap { scope =>
      r.pull.uncons.flatMap { x =>
        Pull.acquire(scope.lease)(_.map(_.cancel.void).getOrElse(IO.pure(()))) >>
          x.map { case (h,t) => Pull.output(h) >> t.pull.echo }.getOrElse(Pull.done)
      }.streamNoScope ++ Stream.eval_(IO(println("after")))
    }.compile.drain.unsafeRunSync
```

**Comment by pchlupacek** [comment]
@mpilquist couldn't you express `s1 ++ s2` by

```scala 
acquireResource.flatMap { r =>
s1(r) ++ s2(r)
}
```

I am not quite sure if I understand correctly the need for extending lifetime of resource manually via `Scope`.

**Comment by SystemFw** [comment]
@pchlupacek 

```scala
acquireResource.flatMap { r =>
s1(r) ++ s2(r)
}
```

This works if you're in control of the resource acquisition. But if you get handed `s1` with finalisers, you can't delay the finalisers until the end of `s2`. This is only a problem in very rare cases, but the need for this does seem to pop up in those rare cases. We hit one in http4s, and that's where this issue is coming from.

**Comment by pchlupacek** [comment]
Ah yes, I see what do you mean. So essentially we want to `Lease` all scope instead Resource? Technically, we will lease resources, but the flag will be on scope level right ?

**Comment by mpilquist** [comment]
Yeah, I think scope would need a count of outstanding leases and we'd copy that count in to each resource that's acquired?

**Comment by pchlupacek** [comment]
Not sure. Perhaps its just  lessee: Seq[Scope] and when resource is acquired, you just travers through scopes and add them as lessee to resource. 

We would need to assure, that during interruption there won't be race, so the lessee won't be somehow holding resource release.

**Comment by pchlupacek** [comment]
@SystemFw also would like to have full example (case) from the http4s you mentioning. I really think this is very advanced technique, and may lead to strange behaviours if used improperly. I would like to see if we just couldn't do somehow better :-)

**Comment by SystemFw** [comment]
> I really think this is very advanced technique, and may lead to strange behaviours if used improperly. I would like to see if we just couldn't do somehow better

100% agreed tbh.
The conversation is here https://gitter.im/http4s/http4s?at=5bb6c069435c2a518e52f8a9
Unfortunately I don't have a condensed summary or anything,  @rossabaker was working on it

**Comment by pchlupacek** [comment]
@SystemFw not sure if I follow. if this is the issue : 
```scala
def writeEntityBody(p: EntityBody[F]): F[Boolean] = {
    val writeBody: F[Unit] = p.to(writeSink).compile.drain
    val writeBodyEnd: F[Boolean] = F.fromFuture(writeEnd(Chunk.empty))
    writeBody *> writeBodyEnd
  }
```
Then I think as per discussion 

```scala

val writeBody: Stream[F, Unit] = p.to(writeSink)
val writeBodyEnd: F[Boolean] = F.fromFuture(writeEnd(Chunk.empty))

(
writeBody >>  // note there is not drain !
Stream.eval(writeBodyEnd)
).complile.last.map(_.contains(true))
```

must do the trick. If not, this then seems like bug in fs2.

**Comment by SystemFw** [comment]
Do you mean `++` there?

**Comment by pchlupacek** [comment]
no >>

**Comment by SystemFw** [comment]
On the `Stream? wouldn't that call `writeBodyEnd` on each `Unit` emitted by `writeBody`? There's no guarantee that's a singleton stream

**Comment by pchlupacek** [comment]
ok then lets add `last` :-)

**Comment by SystemFw** [comment]
Already did that, but it has the same effect as using `++` in terms of when the finalisers are closed

**Comment by pchlupacek** [comment]
So this doesn't work? 
```
(
writeBody.last >>  // note there is not drain !
Stream.eval(writeBodyEnd)
).complile.last.map(_.contains(true))

```

**Comment by SystemFw** [comment]
Not for this specific case, it ends up being the same as `writeBody.drain ++ Stream.eval(...)` in terms of when the finalisers are called (which kinda makes sense in general, since in both based `writeBodyEnd` happens after the other stream has finished emitting, which is when you would expect the finalisers to be called)

**Comment by pchlupacek** [comment]
IS there any example with exact structure of the streams? It sounds to me like you would like to trun-off the resource management of `writeBody` stream all-together, and that seems quite fishy :-) I mean only thing where the `. last >>` and `++` approach may behave similarly is that some `inner` resource in flatMap gets finalized _BEFORE_ the `writeBody` stream finishes.

**Comment by rossabaker** [comment]
This is a pretty good example.  It is useful to know when `r` has been fully rendered to a sink to trigger assertions in tests or for metrics.  It works great if the sink is not buffered.  If the sink requires a final flush, it is difficult for `r` to register an interest in the completion of the flush.  Ideally, "done" would print after "1\n2\n\3\n".

```scala
@ val r = Stream(1, 2, 3).covary[IO].onFinalize(IO(println("done"))) 
r: Stream[IO[x], Int] = Stream(..)

@ val buff = Ref[IO].of(Vector.empty[Int]).unsafeRunSync() 
buff: Ref[IO, Vector[Int]] = cats.effect.concurrent.Ref$SyncRef@789c52bf

@ val write = Sink[IO, Int](i => buff.update(_ :+ i) *> IO(println(s"buffered $i"))) 
write: Stream[IO, Int] => Stream[IO, Unit] = fs2.Sink$$$Lambda$2148/256283896@47ff9edb

@ val flush = buff.get.flatMap(_.traverse_(i => IO(println(i)))).guarantee(buff.set(Vector.empty)) 
flush: IO[Unit] = Async(cats.effect.internals.IOBracket$$$Lambda$2463/1274298661@62c67363, false)

@ (r.to(write) ++ Stream.eval_(flush)).compile.drain.unsafeRunSync() 
buffered 1
buffered 2
buffered 3
done
1
2
3
```

The use case could be satisfied by providing a completion callback in addition to the finalizer on `r`.  This would the provider of `r` to understand more about how it is consumed, but is more consistent with the idea that `r`'s finalizer is for scoping scarce resources as tightly as possible.  I can see both sides of that.

**Comment by pchlupacek** [comment]
@rossabaker thanks a lot for this. I see the issue now. I'll think on it what is correct behaviour and what are the options we have...

**Comment by pchlupacek** [comment]
@rossabaker do you think we could also sort of reverse the problem, that essentially you want to modify the structure of `r.to(write)` so you can append the stream before any finalisation code will get executed?

**Comment by mpilquist** [comment]
Note this can be accomplished in recent versions of fs2 by using `compile.resource`:

```scala
@ r.through(write).compile.resource.drain.use(_ => flush).unsafeRunSync
buffered 1
buffered 2
buffered 3
1
2
3
done
```
