### ISSUE TITLE
Queue (consistently) misses an element on certain usage

### ISSUE THREAD

**Issue by svalaskevicius** [functional-streams-for-scala/fs2#1293]
When a dequeue stream is manipulated (merged with another stream, and split into two via pull), then dequeuing misses an element (always the first element on a subsequent pull). an example of the code showing this can be seen here: https://scastie.scala-lang.org/LBTK7fSnQIC0kLEkvk9cYA

Not only the element (4) is missing from the second printed list, but it is also not shown in the dequeue's evalTap logging - there is no "deq: 4" line.

This behaviour is also consistent - all repeated runs result in the same error.

`run1` in the example is added as a passing example - if the stream is split by amount, dequeuing works ok.

related conversation (in case there are more replies) on gitter starts here: https://gitter.im/functional-streams-for-scala/fs2?at=5bc642ed82893a2f3bf0cef9

fs2 version: 1.0.0
The same function (`splitByTimeout`) was working ok with an earlier fs2 release (0.10.x)

**Comment by mpilquist** [comment]
@pchlupacek I think this is a bug in `dequeue` which is defined as:

```scala
def dequeueChunk(maxSize: Int): Stream[F, A] =
  Stream.evalUnChunk(pubSub.get(maxSize)).repeat
```

There's no bracketing occurring here, so when the stream is canceled, this isn't finalized. I think we need something like `Stream.bracket(pubSub.get(maxSize).start)(_.cancel).flatMap(Stream.chunk)`

**Comment by pchlupacek** [comment]
@mpilquist yeah seems so will take a look on this.

**Comment by pchlupacek** [comment]
@mpilquist its strange. the pubsub get actually performs cleanup in subscribers on every get. so there shall not be a need for that bracket imho.

**Comment by pchlupacek** [comment]
ah i see the issue.  the get is not cancelled, as it is not treated as resource in stream context.  I think I will come with some generic fix for that  :)

**Comment by mpilquist** [comment]
Right we either supervise an incur the cost of the fiber or we have an alternative to get that returns something like Resource[F, A]

**Comment by mpilquist** [comment]
@pchlupacek Any luck? I'm fine with the simple fiber based solution and can PR that if you are busy.

**Comment by pchlupacek** [comment]
@mpilquist could you give me a day or two? I have solution in head, essentially I want to add subscribe: Stream[F, A] to PubSub for these situations, is quite simple actually, its only that you bracket the stream instead every `get`.

**Comment by mpilquist** [comment]
:+1: no problem at all

**Comment by guersam** [comment]
I have a trouble with queue as well.

### Program

```scala
import cats.effect.{ContextShift, IO, Timer}
import cats.implicits._
import fs2.Stream
import scala.concurrent.ExecutionContext
import scala.concurrent.duration._


implicit val cs: ContextShift[IO] = IO.contextShift(ExecutionContext.global)
implicit val timer: Timer[IO] = IO.timer(ExecutionContext.global)

val prog: IO[Unit] = for {
  queue <- fs2.concurrent.InspectableQueue.unbounded[IO, Char]
  
  sizeWatch = queue.size
   .evalTap(s => IO(println(s"Queue size: $s")))
   .filterWithPrevious { (prev, curr) =>
     println(s"Filtering with Prev: $prev, Current: $curr")
     prev > curr
   }
   .evalMap(s => IO(println(s"Filtered queue size: $s")))

  queueOps =
    Stream('a', 'b', 'c').to[IO](queue.enqueue) ++ 
     Stream.repeatEval[IO, Unit] {
       IO.sleep(500.millis) >>
       queue.dequeue1.flatMap(c => IO(println(s"dequeued: $c")))
     }

  _ <- (sizeWatch concurrently queueOps).compile.drain
} yield ()

prog.unsafeRunSync()
```

### Expected output
```
Queue size: 0
Filtered queue size: 0
Queue size: 3
Filtering with Prev: 0, Current: 3
dequeued: a
Queue size: 2
Filtering with Prev: 3, Current: 2
Filtered queue size: 2
dequeued: b
Queue size: 1
Filtering with Prev: 2, Current: 1
Filtered queue size: 1
dequeued: c
Queue size: 0
Filtering with Prev: 1, Current: 0
Filtered queue size: 0
```

### Actual output
```
Queue size: 0
Filtered queue size: 0
Queue size: 3
Filtering with Prev: 0, Current: 3
Filtering with Prev: 0, Current: 3
dequeued: a
Queue size: 2
Filtering with Prev: 0, Current: 2
Filtering with Prev: 0, Current: 2
dequeued: b
Queue size: 1
Filtering with Prev: 0, Current: 1
Filtering with Prev: 0, Current: 1
dequeued: c
Queue size: 0
Filtering with Prev: 0, Current: 0
Filtering with Prev: 0, Current: 0
```

It is related to this issues, or am I just doing something wrong?
