### ISSUE TITLE
[Doc] Concurrency Primitives doc: SignallingRef instead of Signal?

### ISSUE THREAD

**Issue by kczulko** [functional-streams-for-scala/fs2#1298]
Hi,

While working with fs2 I came to the microsite saying that `Signal[F[_],A]` has kind of companion object:
https://github.com/functional-streams-for-scala/fs2/blob/d65f6a2edafda98d4866e2dcc716f39dcb5606cd/site/src/concurrency-primitives.md#single-publisher--multiple-subscriber

```scala
val stream = for {
      topic     <- Stream.eval(Topic[IO, Event](Event("")))
      signal    <- Stream.eval(Signal[IO, Boolean](false))
      service   = new EventService[IO](topic, signal)
      _         <- Stream(
                    S.delay(Stream.eval(signal.set(true)), 15.seconds),
                    service.startPublisher.concurrently(service.startSubscribers)
                 ).parJoin(2).drain
    } yield ()
```

Shall we change that to `SignallingRef[F[_],A]`?

Please let me know if I'm doing sth wrong but if that requires a fix I can handle that.

Best regards,
Karol

**Comment by mpilquist** [comment]
Indeed, thanks for spotting that. PR would be most welcome.

**Comment by SystemFw** [comment]
Note that now a Stream can be interrupted differently, i.e. with a Deferred, or with `interruptAfter`, so if interruption is not used to explain something else (like signals or join), then just `interruptAfter(15.seconds) would do.
