### ISSUE TITLE
Support for gzip compress/decompress pipes?

### ISSUE THREAD

**Issue by djspiewak** [functional-streams-for-scala/fs2#1313]
scalaz-stream used to have gzip support way back in the day, but it never worked particularly well and it was tied to `Process`'s internals. @fthomas rightfully deleted it quite some time ago. I have resurrected it in a new and totally-not-hacky way! https://github.com/slamdata/fs2-gzip

Is there interest in a PR which moves this into -core? Or perhaps -io? I'm more than happy to do so. We needed it right away, which is the only reason I spun it up as a separate project.

---

For those who wish to code review the project I linked, here's a quick summary of the challenges involved and what exactly is being done to address them.

GZIP is basically an unwrapped inflate datastream wrapped by a CRC header/footer and some other magic bytes. These headers and footers aren't *entirely* trivial, but they are reasonably straightforward. Note that this does *not* mean that inflate with `nowrap = true` is the same as gzip! You cannot decompress the output of `gzip` with `deflate`, nor can you compress data for `gunzip` with `inflate`. They're still different formats.

The `java.util.zip` package contains an implementation of `Inflate` which is able to deal with variable-sized input chunks in an incremental way. By which I mean, you can pass a chunk of bytes to it, and it will process that chunk and give you as much output as it can, updating its state to accept the *next* chunk of bytes and returning control flow. This property (returning control flow and updating internal state) is critical to use in an async context.

By way of contrast, `GZIPInputStream` does *not* exhibit this property. The `InputStream#read` function is expected to block until input is available. You cannot simply return zero bytes to signal "return control flow back to whoever called you", even though that would have been an extremely sensible design for `InputStream` 20+ years ago. Naively, this would seem to imply that the only way to use `GZIPInputStream` within a `Pipe` would be to spin up a separate thread which blocks for `read` calls, context shifting chunks to and from that thread. This would be quite horrible.

Unfortunately, really no one has implemented a particularly good GZIP parser which is async-friendly. Spray comes the closest, and they do so by implementing GZIP header/footer parsing themselves and delegating to `Inflate` for the datastream encoding/decoding. This isn't a horrible strategy, but it makes me a bit nervous since a) it's tied to Spray in some unfortunate ways, and b) it's not used by anyone other than Spray.

`GZIPInputStream`/`GZIPOutputStream` are horrible, but they've been used by all the people since forever. It is desirable to use them *if possible*.

In this case, it *is* possible using a trick similar to what happens inside of Jawn's `AsyncParser`. Basically, we use a static no-trace exception as a signal to suspend an effective continuation, where the continuation closure is saved via mutable state. This is a little trickier than Jawn's approach though, since the mutable state in question is *inside* of `GZIPInputStream`.

The key property which allows this to work is the fact that the only places where `GZIPInputStream` takes control flow (via a method call) and performs reads on the underlying byte stream are strictly arranged into the following pattern:

1. Idempotent operations on mutable state
2. Read, read, read, read
3. Write new mutable state
4. Return

Critically, we do *not* have non-idempotent mutations interleaved with reads. All the non-idempotent writes are at the very end, after all reads are completed.

This allows us to throw an exception whenever a read is attempted with insufficient data available. This exception passes up through `GZIPInputStream` uncaught until it reaches our code on the *other* side of the `read` call, effectively unwinding the call stack and giving us control again. We then asynchronously suspend (i.e. `in.pipe.uncons`) until we have more bytes to supply. Since nothing has been non-idempotently mutated, we can safely just restart the same `read` call as soon as we get new bytes. And since traceless exceptions are insanely fast on HotSpot, we don't even lose any meaningful performance by doing so!

In order to support multiple sequential reads without cursor offsets, we have a single-cell `checkpoint`/`restore` mechanism on the underlying byte stream (which we bypass for performance as soon as we know we're beyond the header and into the `Inflate`-managed datastream). This deals with the fact that, technically, a *successful* `read` on the underlying byte stream represents a non-idempotent mutation (due to the fact that the cursor moves forward). But since that mutation is entirely within our control (rather than in the internals of `GZIPInputStream), it doesn't invalidate the technique.

Overall, I'm pretty happy with the implementation. I don't have any benchmarks written, but it should be relatively competitive with any approach which involves `Stream`, and it is entirely based on a well-tested and standard implementation of the core algorithm. I also have tests which show compatibility with the GNU `gzip`/`gunzip` utilities, just to be extra paranoid.

Also, the technique itself seems to be relatively general. We should be able to use this to make other `InputStream`s async-friendly, provided their internal state management adheres to the pattern I described above.

**Comment by SystemFw** [comment]
This is both amazing and terrifying :)

**Comment by mpilquist** [comment]
Looks pretty cool! I like the idea of extending this technique to other `InputStream`s too.

Note http4s has some support for gzip, though I guess only server side encoding: https://github.com/http4s/http4s/blob/master/server/src/main/scala/org/http4s/server/middleware/GZip.scala

**Comment by fthomas** [comment]
Thanks @djspiewak for bringing back some old memories! :-) For those interested in a little bit of history, here is the PR that removed the old `gunzip`: https://github.com/functional-streams-for-scala/fs2/pull/138

**Comment by djspiewak** [comment]
@pchlupacek A fair concern. To answer it a bit…

It's not something I've benchmarked *here*. It is something I've benchmarked previously in other projects (e.g. Tectonic, which derived from previously-benchmarked work in Jawn, which borrowed the trick from still-earlier benchmarks in other work; Odersky mentioned this quirk of the JVM when he introduced `breakable`, for example). The intuitive explanation here is that the way that HotSpot works, throwing and catching exceptions is incredibly fast, because it really just involves a long jump and a rewind on the stack pointer. The fact that locating an exception handler up the stack is so fast is the part which always surprises me a bit, but you can think of the process like a tiny type index which is carried along with control flow, so it can be a very direct jump. You blow your CPU pipelines, but that's about it.

The expensive part of exceptions is really just populating the stack trace. Literally, `Throwable#fillInStackTrace()`, since that function requires unwinding and then re-winding the entire call stack all the way to the root, and HotSpot's stack representation is optimized for exactly *not* this (as it should be). So stack traces are incredibly slow to compute. But that computation critically happens on exception *creation*, not on `throw`. So you can use a cached singleton exception as a signal, and effectively it just behaves like a labeled `break` in C (with almost the exact same performance), except that it can cross function boundaries.

**Comment by djspiewak** [comment]
@mpilquist It's possible to work with `GZIPOutputStream` without the exception trick (and that's exactly what this PR does). So, compression. It's really `GZIPInputStream` (decompression) that poses the difficulties. Http4s has had a few attempts to implement this (since it would be extremely useful for `Http4sClient`), but nothing has come to fruition.

**Comment by pchlupacek** [comment]
@djspiewak thanks for explanation. As for the initialized stacktraces, that the trick I have used previously, and I know it makes cost of creating exception to be on pair with any other object. 

so lets see how this goes ....

**Comment by pchlupacek** [comment]
I think this shall be placed in fs2.io imho.

**Comment by SystemFw** [comment]
I agree with it being in `io`

**Comment by sebastianvoss** [comment]
@djspiewak That would be great. I'm currently using `fs2-gzip` from a middleware to decode GZIPed requests in `http4s`. It works great but would be easier if it would be part of `fs2`.

**Comment by djspiewak** [comment]
@sebastianvoss It's coming! :-) I'm actually working on it right now.
