### ISSUE TITLE
Fix https on fs2.io

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#1321]
https://fs2.io uses a certificate that doesn't have fs2.io in the generated SubjectDN nor in any SubjectAltName extensions. Based on GH pages documentation, I think we need to update the fs2.io A records to be:

```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

(https://help.github.com/articles/troubleshooting-custom-domains/#https-errors)

@pchlupacek Can you update that DNS record?

**Comment by pchlupacek** [comment]
yeah sure.

**Comment by pchlupacek** [comment]
@mpilquist shall be done now. could you please verify ?

**Comment by mpilquist** [comment]
Verified both DNS and HTTPS. 👍
