### ISSUE TITLE
Printing sinks should take ContextShift + EC

### ISSUE THREAD

**Issue by djspiewak** [functional-streams-for-scala/fs2#1328]
There are three printing sinks on `Sink` which involve blocking IO operations but do not take the appropriate `ContextShift` + `ExecutionContext` pair to shift the blocking:

- `Sink.lines`
- `Sink.showLines`
- `Sink.showLinesStdOut`

Obviously a somewhat minor thing, but standard output latency can be a meaningful factor in some applications, and it's worth handling this properly in the API. Unfortunately, this does mean that we'll need to upgrade the constraint to be `Async[F]`.

**Comment by mpilquist** [comment]
This what somewhat intentional as I was afraid if the ceremony was too high, folks would use `IO(println(..))`. Not arguing strongly for that though.

Given binary compatibility of 1.0.x, any thoughts on how to proceed? 3 new methods with new names and the `ContextShift` + `ExecutionContext` pattern would work, along with deprecating the existing ones.

**Comment by djspiewak** [comment]
Yeah deprecation and duplication would be the way to go if we want to address it in 1.0. It's a pain though because we can't abuse overloading to keep the names. I'm completely fine if we wanted to push it back further to 2.0. It's definitely not a *huge* immediate deal.

I definitely agree on the ceremony side of things. It's actually a lot of work to get a file `Sink` now. Necessary work, but unfortunately still work. I kind of wish there were a way we could provide a nice API for encapsulating a lot of that ceremony, but I don't have any good inspirations as to how to do it.

Honestly, I'm pretty sympathetic to the ceremony argument on these sinks specifically, so if you feel like it's better overall to leave them the way they are, I wouldn't put up much of a fight. :-)

**Comment by SystemFw** [comment]
I think these should stay as they are, but we might provide different ones in `.io` for cases where you do need to worry about that throughput. Agreed on wishing for a nice API, although I think the one we had now is an improvement from the previous situations with unclear `async` versions of things

**Comment by mpilquist** [comment]
That works for me. We could add suitably scary warnings to these and link to the Enterprise Edition versions for serious workloads.

**Comment by djspiewak** [comment]
> We could add suitably scary warnings to these and link to the Enterprise Edition versions for serious workloads.

LMAO.

Okay, so in that case, what's in `io` already in the form of `stdout` is already pretty close. I would add `stdoutLines` (taking a `Show` and a `Charset`, perhaps with a defaulted parameter to utf-8) and also a `stdinLines` (producing `String`s) and call it a day.

**Comment by monadplus** [comment]
I'd like to work on this issue. Is the last comment still the way to go ?

**Comment by monadplus** [comment]
`linesAsync` in Stream is really similar to what is proposed in the last commend for `stdoutLines`.

**Comment by monadplus** [comment]
After having a look at this issue, in series/1.0 all three primitives have their counterpart using the given blocking execution context.

**Comment by kubukoz** [comment]
#1427 is merged, can this be closed?
