### ISSUE TITLE
[Poll] - Official logo for `fs2`

### ISSUE THREAD

**Issue by gvolpe** [functional-streams-for-scala/fs2#1350]
Our friend @Zelenya drafted a couple of amazing designs so let's have a poll to decide which one becomes the official `fs2` logo! See larger images [here](https://imgur.com/a/YtdBzKm).

![logos](https://pbs.twimg.com/media/Dsgk_cAW0AEzn2b.jpg)

Once we choose a design we can probably have another poll to choose the palette of colors.

[![](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/0)](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/0/vote)
[![](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/1)](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/1/vote)
[![](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/2)](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/2/vote)
[![](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/3)](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/3/vote)
[![](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/4)](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/4/vote)
[![](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/5)](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/5/vote)
[![](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/6)](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/6/vote)
[![](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/7)](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/7/vote)
[![](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/8)](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/8/vote)
[![](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/9)](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/9/vote)
[![](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/10)](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/10/vote)
[![](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/11)](https://api.gh-polls.com/poll/01CXQM0T123MGZNBGZ5K1K9CYD/11/vote)

**Comment by erip** [comment]
I really like number 6. 😄

**Comment by mpilquist** [comment]
/polls 0 1 2 3 4 5 6 7 8 9 10 11

**Comment by Daenyth** [comment]
4, then 8, would be my preference.

**Comment by lJoublanc** [comment]
While these are all nice, many won't scale very well (think gitter icon size or the icon on your web-address bar). I would say 4.

**Comment by SystemFw** [comment]
4 with different colours would be my preference, it's closer to explaining what fs2 does in a super smart way :)

I also like 2/7 (almost the same), just because they're cool. I'm afraid 8 won't scale very well and just look like a scala logo.

**Comment by Zelenya** [comment]
How would they look in gitter
![1](https://user-images.githubusercontent.com/11508062/49461526-32bb0b80-f7f4-11e8-9b2c-d1750b5764e0.png)

**Comment by pchlupacek** [comment]
yeah, do not scale very well.

**Comment by gvolpe** [comment]
Closing as we already have a winner :smiley: #1367
