### ISSUE TITLE
Question / Spike - Internals: turn View into Tagged Type

### ISSUE THREAD

**Issue by diesalbla** [functional-streams-for-scala/fs2#1360]
In the `fs2.internals` package, there is a `ViewL[F[_], R]` trait, with a single case class `ViewL.View` and a single factory method `ViewL.apply`. The goal of this class is to represent expressions of the `FreeC[F, R]` type that have been _unrolled_ deep enough until it could no longer be unrolled. In particular, a View can be either:

- An instance of the sub-type `FreeC.Result`, with no continuation; or
- A `ViewL.View`, which corresponds to a `FreeC.Bind` where the left hand side is a `FreeC.Eval` (the lift operation), and the rest is a continuation on the result.

We could get the same functionality using a tagged type, which would wrap a `FreeC[F, R]`. Using a tagged type could remove the need for an extra `ViewL` ADT (which overlaps with `FreeC`), at no memory cost.

**Comment by pchlupacek** [comment]
@diesalbla I would like to see concrete proposal, and specifically how the performance will look in case of right/left associative bind paths. 

Ofc, if we would remove somehow the cost of allocation would be excellent. 

Also note, we have been discussing to remove ViewL completely, but so far didn't have the luck with it.

**Comment by diesalbla** [comment]
@pchlupacek The concrete proposal was to used tagged types, a mechanism available at least in `scalaz` and `shapeless`, that allows annotating any type with a tag. In this case, we would use a tag `FreeC[F, R] @@ Viewable`, to indicate that it is a `FreeC` that can be inspected. 

I am thinking of another possible solution. Now, a `ViewL` is pretty much a `FreeC` somehow _normalised_, to a form in which the left hand side is either a `Result` or a `Bind-Eval`. I wonder if we could  remove the need for the `View`-`Bing` separation, by simply making all `FreeC` terms always into this form. This would involve: 
- Hide the `Bind` case class, so that the constructor is not public.
- Create a factory method `bind`, which will take similar parameters as the `Bind`, but whose implementation would perform the `mk` loop in the `View` class. 

Note that, until the `Eval` is reached, there is no need to use the `F` type effects. The only problem is, of course, that we would have to restrict the `FreeC` type to avoid infinitely left-recurring binds (if that can happen).

**Comment by mpilquist** [comment]
FWIW, I tried to force all `FreeC` values to be in the unrolled form by
making `flatMap` construction smarter but wasn't able to get that working.
IIRC, the problem was ensuring stack safety.

**Comment by pchlupacek** [comment]
@diesalbla not sure how to do that what do you proposing. Let's see if you can crack it. To my knowledge tagged types do not allocate memory, however I am unsure how to use them to implement FreeC/ViewL.

**Comment by diesalbla** [comment]
After giving it some thought, I re-realised that `ViewL` is not a data-type stored ever assigned in any other class, or composed with anything else. It is just a _placeholder_ for a sub-class of values, `Result` or Bind-Eval. This placeholder is _immediately_ deconstructed (pattern-matched), where each case (results or bind-eval) passed  to a different branch. This suggested that we could just remove the place-holder type, and factor the pattern-match as a higuer-order function (a `fold`). That is the result of that PR.

**Comment by pchlupacek** [comment]
@diesalbla could you prove benefits of this change? Any tests // measurement proving that this has measurable end user benefits?
