### ISSUE TITLE
Scalafix for Sink deprecation

### ISSUE THREAD

**Issue by SystemFw** [functional-streams-for-scala/fs2#1393]
Sink has been deprecated. The changes necessary to migrate are very simple:
- replace `Sink[F, A]` with `Pipe[F, A, Unit]`
- replace `stream.to(sink)` with `stream.through(sink)`

A scalafix to do this automatically should be quite easy, and useful at the same time. 
Good for someone who'd like to start contributing :)

**Comment by tmciver** [comment]
I'd like to try to do this.

**Comment by tmciver** [comment]
I have a mostly working version of a scalafix for this which you can see [here](https://github.com/tmciver/sink-to-pipe-scalafix).

I've tested this on a local copy of the [fs2-aws project](https://github.com/saksdirect/fs2-aws).  It seemed to work acceptably but one issue remains that I have not yet been able to resolve: extra imports of `fs2.Pipe` are added (even after running the `RemoveUnused` scalafix rule).  I'm sure there is a way around this but I wanted to give a progress report before more time went by.

I was new to scalafix before attempting this work and still am not very familiar with its inner workings.  If anyone has suggestions on improvements, I'd love to hear them!

**Comment by monadplus** [comment]
@tmciver Are you still working on it ?

**Comment by tmciver** [comment]
@monadplus Yes, sort of.  There are problems with it in its current form that I need to resolve but just have to find the time.  Contributions/help is welcome!

**Comment by monadplus** [comment]
@tmciver I'll try to open a PR between today and tomorrow to fix the issue with the redundant imports of `fs2.Pipe`. (I am also new with scalafix, cool tool)

**Comment by monadplus** [comment]
I have opened a PR @tmciver on the project (here)[https://github.com/tmciver/sink-to-pipe-scalafix]

**Comment by mpilquist** [comment]
Fixed in #1432
