### ISSUE TITLE
Provide an Alternative[Stream[F, ?]] instance

### ISSUE THREAD

**Issue by djspiewak** [functional-streams-for-scala/fs2#1394]
Should probably be just mixed into `monadInstance` and `monadErrorInstance` to avoid ambiguities. `Alternative`, btw, is basically just a universally quantified `Monoid` together with an `Applicative` with some laws governing their interaction. I was actually somewhat surprised to see that it isn't already implemented.

I'll get to this in PR form at some point if no one else gets to it first. Just thought I'd open the issue as a prerequisite step.

**Comment by SystemFw** [comment]
@djspiewak Actually there is a problem I think:

```scala
trait Alternative[F[_]] {
  ....
   def separate[G[_, _], A, B](fgab: F[G[A, B]])(implicit FM: Monad[F], G: Bifoldable[G]): (F[A], F[B]) = {
     val as = FM.flatMap(fgab)(gab => G.bifoldMap(gab)(pure, _ => empty[A])(algebra[A]))
     val bs = FM.flatMap(fgab)(gab => G.bifoldMap(gab)(_ => empty[B], pure)(algebra[B]))
     (as, bs)
  }
```

Which repeats the effects twice. Sounds like `MonoidK` is the best you can do, which sucks because the main use case for `Alternative[Stream` (as I see it) is to be able to call `guard`, which takes `Alternative` and not `MonoidK: Applicative`

**Comment by djspiewak** [comment]
@SystemFw Is that really a problem? I mean, users can write that function on their own *today* and it will repeat the effects twice. That's just kind of the best you can do given the function signature if you don't have memoization, which might not be safe in general.

**Comment by SystemFw** [comment]
Well, the way I see it is this:
If someone PR'd that `separate` to fs2, I'd reject the PR and ask for something with the correct type that doesn't repeat effects (or break purity). By adding the instance, we as library authors are providing a function that will do the wrong thing most of the time, so I'm a bit wary of it, I definitely consider that a problem.

Is this problem a show stopper? Maybe, maybe not, I'm open to being overruled (we could just add a comment). Let's see what the others think as well? :)

**Comment by djspiewak** [comment]
I guess the way I think about it is that particular function is definable *now*. All I would need to define this is `Monad[Stream[F, ?]]` and `Monoid[Stream[F, A]]`, both of which I have. So what if the cats team moved `separate` to `Monad` (taking an extra `Monoid` constraint) instead of keeping it where it is now? Would `Stream` no longer form a monad?

**Comment by SystemFw** [comment]
So, I see your point, and I can't disagree :P

However the reason I think this is somewhat a special case is that _a lot_ of new users on gitters, especially those that come from akka-stream, think in terms of fan- out and fan-in, and they reach for a function that "separates" streams as one of their first tools. So I think that offering `separate` would give them a loaded footgun. It's true that they can always implement it themselves (like a million other buggy functions), but generally at that point they come and ask :)


In any case, I don't feel strongly enough about this to say "this must not happen", but I do think it's worth keeping in mind.

**Comment by ChristopherDavenport** [comment]
I think it's alternative instance and scaladoc/comments to make it clear. To me, it seems reasonable and lawful. Just not what people expect.

What about the current behavior you would see for the current instance for `OptionT` used with effects?

**Comment by SystemFw** [comment]
> I think it's alternative instance and scaladoc/comments to make it clear

Well, as I said, if I end up in a minority it's fine :)

> To me, it seems reasonable and lawful. Just not what people expect.

I don't think that definition of `separate` is reasonable in any way for Stream. I _have_ wanted `guard` in the past though, i have to say.

> what about the current behavior you would see for the current instance for OptionT used with effects?

Yeah, I agree with this: conceptually it's a lawful function that just doesn't make sense for some instances, it's not the only one. The problem though is that people aren't constantly trying to `separate` `OptionT`, but they are constantly trying to do so with `Stream`.

**Comment by SystemFw** [comment]
I think I have a solution to this conundrum. I'll make a PR in the following days and you guys can tell me what you think.

**Comment by SystemFw** [comment]
I miserably failed to followup on this due to time constraints. I guess I'll just say what my idea is in case it takes me another month to make the PR.

Basically I thought we could provide the instance, and then add a `separate` method to `Stream`, requiring a piece of implicit evidence (`implicit AllowSeparate`). The `implicitNotFound` on that evidence can then say something like "are you sure you want to repeat effects twice, look at this instead". If the user is sure, they can just pass `Stream.allowSeparate` to the method.

Given that the name on the class will take precedence over the syntax defined by `cats`, you should be safe most of the time.
You can break it by building a method taking `F[_]: Alternative` and passing `Stream` to it, but this is not what I'm worried about, I'm worried about newcomers trying to split `Stream` specifically a la aka-streams, as mentioned above. 

WDYT? Too much fuss?

**Comment by djspiewak** [comment]
Hmm. I think this is actually a really good idea. Basically masking parts of the generic API which are almost certainly newcomer traps.

**Comment by SystemFw** [comment]
yeah, so if you're onboard with that, I can actually go on and open  a PR hopefully by the end of the week

**Comment by SystemFw** [comment]
Ok, there is another issue.

A definition based on:

```scala
def empty[A]: Stream[F, A] = 
 Stream.empty
def combineK[A](x: Stream[F, A], y: Stream[F, A]): Stream[F, A] =
       x ++ y
```

Fails to meet this law:

```scala
def alternativeRightAbsorption[A, B](ff: F[A => B]): IsEq[F[B]] =
    (ff.ap(F.empty[A])) <-> F.empty[B]
```

Which is guess is also the reason why `OptionT` is not an `Alternative` either.
We can do `MonoidK` I guess, even though the advantages of having that instance are minimal (but it doesn't hurt).

Thoughts?

**Comment by djspiewak** [comment]
Hmm, why doesn't it satisfy the law? Because of the possibility that `ff` is errored?

**Comment by SystemFw** [comment]
Well, I noticed cause the tests failed :)

But yeah, a failing Stream will not result in the same behaviour as empty
