### ISSUE TITLE
Add Chunk.toNel

### ISSUE THREAD

**Issue by Daenyth** [functional-streams-for-scala/fs2#1395]
I'd prefer to avoid translating a chunk `.toList` only to go `.toNel` immediately after.

**Comment by bhop** [comment]
Can I take this one?

**Comment by mpilquist** [comment]
@bhop Go for it :)

**Comment by bhop** [comment]
Do we want it to return `Option[NonEmptyList[A]]` as it is in cats?

**Comment by mpilquist** [comment]
Yep
