### ISSUE TITLE
Compiling monadic Stream

### ISSUE THREAD

**Issue by rnd4222** [functional-streams-for-scala/fs2#1402]
How do I compile Stream in a Monad (without Fallible/Sync instance)?
Why there is no instance of Stream.Compiler[F, F] for any Monad[F]?

**Comment by rnd4222** [comment]
@SystemFw Thanks for your reply.
So if I want to abstract over monad in my code I should abstract over Compiler instance too? Is it the only (recommended?) way?

**Comment by rnd4222** [comment]
Another use case (which can be solved by abstracting over **Compiler**): using **IO** for production code and **Either** for testing.

**Comment by SystemFw** [comment]
> I'm just trying to use Bifunctor IO-like monad,

If you're using `zio`, it does have a `Sync` instance.
You have to settle for `Throwable` errors though, that's a general constraint right now, and it's unlikely to change in the immediate future.

> Another use case (which can be solved by abstracting over Compiler): using IO for production code and Either for testing.

So first of all, I'd recommend not testing with `Either`, and just using `IO` (in general, not just with fs2). There are pretty much zero drawbacks to it. In any case you can do that by either testing whatever stream you have (which 
would be polymorphic over `F`), or if indeed you _have_ to test against the code that compiles the stream and not the stream itself, going through `Compiler`. I wouldn't do that though.

**Comment by rnd4222** [comment]
OK, makes sense. Thanks, I'm closing the issue.
