### ISSUE TITLE
Seq inconsistency between 2.12 and 2.13

### ISSUE THREAD

**Issue by lJoublanc** [functional-streams-for-scala/fs2#1411]
Related to #1232 

The predef `Seq` in the scala language 2.13 appears to have changed form mutable to immutable. As a result this means that code using `Seq`s will behave differently across versions. For instance `Chunk.Seq`. 

I've created https://github.com/lJoublanc/fs2seqincompat to demonstrate this. `Chunk seq scala.collection.mutable.Seq(1,2,3)` won't compile under 2.13 but will under 2.12 (use e.g. ++2.13.0-M5 to switch between versions).

Not sure whether there are other parts of the API that take a seq which may be affected.

See also gitter conversation [February 8, 2019 11:04 AM](https://gitter.im/functional-streams-for-scala/fs2?at=5c5d6240604f233ab6d47d23).
@rossabaker @mpilquist

**Comment by rossabaker** [comment]
Here's a [jawn-fs2 example](https://github.com/http4s/jawn-fs2/pull/41#discussion-diff-254544057R22) of where it causes trouble.

Maybe this could be fixed after Scala 2.13.0-M5 and before Scala 2.13.0 and not run afoul of binary compatibility guarantees?

**Comment by mpilquist** [comment]
Let me know what you think of #1413

**Comment by lJoublanc** [comment]
I'll certainly have a look first thing Monday GMT in the office.
