### ISSUE TITLE
Ability to fetch all available records in the Stream to a chunk before each evalMap

### ISSUE THREAD

**Issue by joshm1** [functional-streams-for-scala/fs2#1423]
I want to process chunks of messages, but before each `evalMap` is called, I want to fetch as many records as possible into the chunk.  Using `groupWithin` doesn't work because it looks like the records are grouped based on when they're added to the stream.  `chunkN` doesn't work either because I don't want it to wait on new records.

Here's an example:

Assume a record is being produced every second, continuously. Every time `evalMap` is called, it takes 5-10 seconds for the effect/IO to complete.

After the first message is produced, `evalMap` will be called with 1 record in the chunk.  During the 5 seconds it takes for that chunk to be processed, another 5 records are added to the stream. I want `evalMap` to be called right away with all 5 records that are available in the stream.

It's sensible for there to be a limit to the number of records in a chunk. I basically want the behavior of `chunkN`, but I don't want it to wait for all N records.

In my case, I'm using a fs2-kafka client

```scala
  kafkaConsumer.partitionedStream
      .map { partition =>
        partition
          .chunkN(1000, true) // <-- looking to replace this
          .evalMap { chunk => /* do work, returns ComittableOffset[F] */ }
      }
      .parJoinUnbounded
      .groupWithin(maxBatchCommitSize, maxBatchCommitWait)
      .map(_.foldLeft(CommittableOffsetBatch.empty[F])(_.updated(_)))
      .evalMap(_.commit)
```

**Comment by nigredo-tori** [comment]
> Using groupWithin doesn't work because it looks like the records are grouped based on when they're added to the stream.

It seems that you think of a `Stream` as some sort of queue and/or listener. Instead it's useful to compare it to Scala's `scala.collection.immutable.Stream` with extra effect handling: you can pull elements from it (which may trigger some side effects) but you can't directly add elements to an existing collection. Any parallelism and nondeterminism here are the property of the underlying monad.

That said, let's rephrase your question:
1. You have a `Stream` for which pulling each element takes an unpredictable amount of time.
1. You have some logic that handles chunks of such elements, where handling each chunk takes a large amount of time.
1. You want to build your processing in such a way that the elements are pulled **while you're handling a chunk** (this implies concurrency).
1. After a chunk is handled, if any new elements were pulled from the initial `Stream`, you want to yield a new chunk.

The easiest way I see to solve this would be using a `fs2.concurrent.Queue` of elements. You'll want to have one `Stream` that drains the initial `Stream`'s elements into this `Queue`, and another `Stream` that pulls available elements from it, yielding chunks (see `Queue.dequeueChunk`). These two `Streams` would need to be concurrently `merge`d. Basically, something like this:
```scala
def concurrentChunks[F[_]: Concurrent, A](in: Stream[F, A]): Stream[F, Chunk[A]] =
  Stream.eval(Queue.unbounded).flatMap { queue =>
    val push = in.evalTap(queue.enqueue).drain
    val pull = queue.dequeue.chunks // this uses dequeueChunk internally
    push.mergeHaltL(pull)
  }
```
I haven't tested or compiled this, and it obviously needs some work with backpressure and termination handling, but it should be enough to get you started.

**Comment by djspiewak** [comment]
You want either `balance` (bounded) or `balanceAvailable`. Something like this:

```scala
def process[F[_]: Concurrent, A, B](f: Chunk[A] => F[B]): Pipe[F, A, B] =
  _.balanceAvailable.flatMap(_.evalMap(f))
```

**Comment by mpilquist** [comment]
Closing this one but feel free to reopen if you have further questions!

**Comment by iOgre** [comment]
fs2.concurrent.Queue does not exists any more, and fs2.Chunk.Queue is not the same, correct?

**Comment by mpilquist** [comment]
`Queue` moved from fs2 to cats-effect in the fs2 3.0 release. However, there's built-in support for the type of operation this issue is about using `fs2.concurrent.Channel`. See https://github.com/typelevel/fs2/pull/3401 for an example usage.

**Comment by iOgre** [comment]
Thank you, will take a look
