### ISSUE TITLE
Properly handle blocking IO in watch API

### ISSUE THREAD

**Issue by nigredo-tori** [functional-streams-for-scala/fs2#1431]
I've stumbled upon a fact that `fs2.io.file.watch` [uses blocking API internally](https://github.com/functional-streams-for-scala/fs2/blob/a34ed54d3b9c07b98e704862cd6d081edbcdbdca/io/src/main/scala/fs2/io/file/Watcher.scala#L280) - it's written in such a way that it is almost always is in `WatchService.poll(Long, TimeUnit)`. If someone runs `fs2.io.file.watch` on the CPU pool (like I did), it basically hogs a single thread for itself, which is especially noticable when running on a single CPU core.

It seems that the correct behavior here would be to use the non-blocking `WatchService.poll()` instead, and control the poll frequency using `cats.effect.Timer`. Otherwise, `Watcher` and related functions should use the standard `ExecutionContext`/`ContextShift` idiom.

**Comment by Daenyth** [comment]
I'd vote for both, tbh

**Comment by mpilquist** [comment]
Moving this to 1.1 milestone as it will require an API change. 1.1 will be released soon -- next week or two.
