### ISSUE TITLE
Enqueuing in a bounded queue is an O(n) operation.

### ISSUE THREAD

**Issue by RafalSumislawski** [functional-streams-for-scala/fs2#1448]
A queue created with `fs2.concurrent.Queue#bounded` is backed by a `scala.collection.immutable.Queue` and calls it's `size` method to check if new elements can be enqueued. Queue.size has O(n) time complexity, as it uses `scala.collection.immutable.List.size` internally. That makes performance of a long bounded queue unacceptable.

There's no trivial fix for this. Changing implementation of the queue could be considered. I think a minimal "solution" would be to warn users against using long bounded queues in the scaladoc of `fs2.concurrent.Queue#bounded`.

**Comment by djspiewak** [comment]
I think we can probably just track size internally in parallel with the backing `Queue` instance, since we control all access to that queue, which in turn would make the size check `O(1)`.

**Comment by SystemFw** [comment]
Yeah I was thinking the same, it should just be a matter of enriching the state of the `Strategy` with some size information. @RafalSumislawski If you want to try and open a PR, I can help you see it through, if not one of us can take care of it, thanks for spotting this in either case :)

**Comment by RafalSumislawski** [comment]
Thanks for quick feedback. I'll try implementing the fix you suggested.

**Comment by mpilquist** [comment]
Fixed by #1468
