### ISSUE TITLE
Port test suite from topic/fs3 branch to series/1.0

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#1465]
The topic/fs3 branch contains a new test suite based on ScalaTest 3.1 generators instead of ScalaCheck. Given that topic/fs3 is likely far away from being ready for production, let's port that test suite back to series/1.0.

@geoffreytchew is working on this.

**Comment by SystemFw** [comment]
\o/

It likely addresses most of #1009 as well
