### ISSUE TITLE
Memory leak on zipWithNext?

### ISSUE THREAD

**Issue by zoraida** [functional-streams-for-scala/fs2#1467]
Hi all, I am using zipWithNext to implement some kind of pagination were each element on the Stream retrieves a “page”. 

Processing current page depends on previous one thus using zipWithNext allows me to pass information between contiguos elements into the same Stream(hope this makes sense to all of you). 

Base on my understanding, I would expect:
* In a given moment of time at least two elements(page content) are kept in memory (current and previous).
* Since previous and current elements can belong to different Chunks(here is were more confused I am), then in a given moment of time, at least two Chunks(is this… how many pages?) are kept in memory.

The point is, I was trying to adjust the page size to keep control of the memory that we need but I started to get Heap OOM thus I decided to profile just a simple piece of fs2 code and try to understand it better.

The code:
```
  import cats.effect.IO
  import cats.implicits.toFunctorOps
  import fs2.Stream

  def dynamicPagination[F[_], P, O](cont: P => O => Boolean, increment: P => P)(
    s: (P, Option[O]) => Stream[F, O])(current: P)(previousElem: Option[O]): Stream[F, O] =

    s(current, previousElem).zipWithNext flatMap {
      case (o, None) =>
        if (cont(current)(o)) Stream(o) ++ dynamicPagination(cont, increment)(s)(increment(current))(Some(o))
        else Stream(o)
      case (o, Some(_)) => Stream(o)
    }

  val ALPHA_NUMERIC_STRING = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

  def randomAlphaNumeric: String = {
    var chars = 10000 // 2 bytes * char = 10000000 bytes => 10Mb
    val builder: StringBuilder = new StringBuilder()
    do {
      val character = (Math.random() * ALPHA_NUMERIC_STRING.length()).toInt
      builder.append(ALPHA_NUMERIC_STRING.charAt(character))
      chars = chars - 1
    }while (chars!= 0)

    builder.toString
  }

  val r = new scala.util.Random
  def randomNumeric: Long = r.nextLong()

  case class Element(id: Long, value: String)

  def continue: Long => Element => Boolean = _ => _ => true
  val infiniteStream: (Long, Option[Element]) => Stream[IO, Element] =(_, previousE) => 
    Stream.emit(previousE.fold(Element(randomNumeric, randomAlphaNumeric(chars)))(previous => 
     Element(randomNumeric + previous.id, randomAlphaNumeric(chars)))).repeat.covary[IO]

   dynamicPagination[IO, Long, Element](continue, _ + 1L)(infiniteStream)(0L) 
    (None).compile.drain.unsafeRunSync
```
Heap behaviour when run with JVM 8:
![fs_heap](https://user-images.githubusercontent.com/2461902/57714112-15784c00-7674-11e9-8cbd-91594f9c61d5.png)
it does not ends on an OOM, I thought that it would be but nop:
<img width="1169" alt="fs_heap_jvm8_256M png" src="https://user-images.githubusercontent.com/2461902/57724655-9bec5800-768b-11e9-8fe3-37c6a3ebad53.png">

Heap behaviour when run with JVM 11:
<img width="1170" alt="fs2_heap_jvm11_256" src="https://user-images.githubusercontent.com/2461902/57757964-e5be5800-76f6-11e9-8c0c-1e5227c47f15.png">

They look totally different. Both cases I am using same heap size but there is a change on the GC(from Parallel to G1). This may be the reason.

Does it make sense to you?

Thanks.
Zoraida.-

Yep! using version 1.0.4 ;)

**Comment by mpilquist** [comment]
In general, these graphs look okay to me. The Java 8 graphs show that various objects are getting collected only when needed -- the drop just after 20:00 shows the collector reclaiming all the unreferenced heap values. The Java 11 collector appears to be doing a better job at collecting unreferenced objects earlier.

**Comment by SystemFw** [comment]
A "sawtooth" pattern is a normal state for the pre-G1 collectors

**Comment by mpilquist** [comment]
Closing this one but feel free to reopen if more data points to FS2 or you get an OOM exception.
