### ISSUE TITLE
[1.0.3/1.0.4] onFinalize with handleErrorsWith in nested stream

### ISSUE THREAD

**Issue by tlipinski** [functional-streams-for-scala/fs2#1505]
After upgrading from 1.0.2 to 1.0.3/1.0.4 I've found out that some code I wrote no longer works as expected. Here's simplified example with nested streams:
```
import cats.effect.IO
import fs2.Stream

object Bug extends App {
  val stream = for {
    _ <- Stream(1, 2, 3)
    _ <- Stream(())
      .evalMap { _ =>
        IO {
          println("eval")
          throw new RuntimeException("ex")
        }
      }
      .handleErrorWith { th =>
        Stream.eval(IO(println("error")))
      }
      .onFinalize {
        IO(println("finalize"))
      }
  } yield ()

  stream.compile.drain.unsafeRunSync()
}
```
In 1.0.2 it outputs everything in order as I expect:
```
eval
error
finalize
eval
error
finalize
eval
error
finalize
```

However in 1.0.3 the output is:
```
eval
error
eval
error
eval
error
finalize
finalize
finalize
```

I get interesting result in 1.0.3 if I swap `handleErrorWith` and `onFinalize`. The output is then:
```
eval
finalize
error
eval
finalize
error
eval
finalize
error
```
Much better than previous one with `onFinalize` evaluations stacked at the end of the stream but it unfortunately it requires from me changing the order of evaluations.

**Comment by SystemFw** [comment]
Add `.scope` after the `onFinalize` and you will get the behaviour you want

**Comment by tlipinski** [comment]
Thank you very much, it works! Based on the speed of your response, it must have been something obvious;)

**Comment by mpilquist** [comment]
Definitely not obvious, just something we've run in to a number of times. In hindsight, we perhaps should have saved those changed until 1.1.0 and included a more prominent note in release notes or ScalaDoc or something. Glad it's working for you now!

**Comment by SystemFw** [comment]
Not obvious, but it's a known tradeoff with a change we made to finalisation. Basically if you are in a case where the next action relies on the finalizer for the previous action to have run, you need to insert a scope boundary manually, in cases where it's not inserted already (i.e when `Pull` is transformed to `Stream`)

**Comment by SystemFw** [comment]
> , we perhaps should have saved those changed until 1.1.0 and included a more prominent note in release notes or ScalaDoc or something

:+1:

Perhaps still worth explaining a bit more when we release 1.1.0, just to get more attention on it
