### ISSUE TITLE
Add `Alternative[Chunk]` instance

### ISSUE THREAD

**Issue by Daenyth** [functional-streams-for-scala/fs2#1516]
To allow for `chunk.separate`, for example

**Comment by djspiewak** [comment]
I'm not entirely sure we should be using abstractions to interact with `Chunk`. I guess I see some value in it, but people really should be doing as much as possible to pattern match and monomorphize their chunk manipulation.

**Comment by Daenyth** [comment]
I think that's a pretty sensible take, but that does lead to me needing to use `chunk.toVector.separate` in this case, which is a totally pointless allocation.

**Comment by kubukoz** [comment]
This can probably be closed since #1517 is merged.
