### ISSUE TITLE
Feature request: Add foreach to CompileOps

### ISSUE THREAD

**Issue by BalmungSan** [functional-streams-for-scala/fs2#1542]
Yesterday I asked on the gitter channel what would be the best way to simple run a final side-effect to each element of a `Stream` as the final step on my program. Christopher Davenport suggested:

```scala
def doSomething(t: T): F[Unit] = ???

val data: Stream[F, T] = ???

data.evalMap(t => doSomenthing(t)).compile.drain 
```

While this works as expected, and is concise enough, I believe it would be good to have some kind of `foreach` as a compile step.
Thinking about this, I decided to do a little research and I found out that other streaming libraries provide a similar construct.

+ **Zio - ZStream**: [`foreach[R1 <: R, E1 >: E](f: (A) ⇒ ZIO[R1, E1, Unit]): ZIO[R1, E1, Unit]`](https://javadoc.io/doc/dev.zio/zio-streams_2.12/1.0.0-RC10-1)

+ **Monix - Observable**: [`foreachL(cb: (A) ⇒ Unit): Task[Unit]`](https://monix.io/api/3.0/monix/reactive/Observable.html#foreachL(cb:A=%3EUnit):monix.eval.Task[Unit]) _(However, in this case the function is impure)_.

+ **Akka - Source**: [`Sink.foreach[T](f: (T) ⇒ Unit): Sink[T, Future[Done]]`](https://doc.akka.io/api/akka/current/akka/stream/scaladsl/Sink$.html#foreach[T](f:T=%3EUnit):akka.stream.scaladsl.Sink[T,scala.concurrent.Future[akka.Done]]) which can be passed to a `runtWith` on a `Source`. _(Again, this is an impure function... But well, it is Akka ¯\\\_(ツ)\_/¯ However, they also have a `foreachAsync`, which receives a `T => Future[Unit]` instead, it is still impure, but captures my idea of a final effectual operation)_.

Thus, I would like to write the following:

```scala
def doSomething(t: T): F[Unit] = ???

val data: Stream[F, T] = ???

data.compile.foreach(t => doSomenthing(t)) // F[Unit]
```

I suspect that since it is done on the `Compiler`, it could be faster than the current alternative.  
Also, I assume it would be possible to also create a:

```scala
foreachAsyn(maxOpen: Int)(f: T => F[Unit])(implicit F: Async[F]): F[Unit]
```

**Comment by Daenyth** [comment]
Given that evalMap exists, and works, I don't think this is a strong option for inclusion. As a heavy user I really feel the api is tricky to learn because there's lots of things that do similar but distinct operations. I think when the operation is the same, it's good to have one clear way

**Comment by BalmungSan** [comment]
@Daenyth I agree that there should be a clear way to do something. And that is precisely the reason I believe this would be a good addition.
IMHO, `evalMap` is just much more general than the proposed addition. Specially, I do not think that a `Stream[F, Unit]` makes much sense. I would also believe that is the reason `evalTap` exists, but it also does not makes much sense if this _tap_ should just be the very last step.

As I said, it was not clear to me, what was the best way to simple call final side effect to each element of the stream. I even spent a few minutes searching for a `foreach` method, as for me, that should had been the name of such method.

Now, I must admit that I am a really novice user of the library, and that maybe the lack of experience with it is what makes me think this is good addition.
I also have to admit that id did not took me too much to get to the `evalMap` solution... But, it didn't feel natural for me, that is why I asked on the gitter channel.

Also, I still believe that, other streaming libraries having a similar _(yet not standard)_ mechanism, is a sign that more people than me find this useful. _(or at least that is what I want to believe 😋)_

Finally, as I said, I guess _(certainly I do not know)_ that if it is added on the **Compiler** it may be more performant than the current solution, as `evalMap` waits for a value, that at the end is an `Unit`, than then is discarded by the `drain`. _(But, I would also think that this is already optimized, or that the JIT would help)_.

**Comment by SystemFw** [comment]
> IMHO, evalMap is just much more general than the proposed addition.

Why do you think that? `evalMap` expresses exactly the idea of evaluating an effect for each element of the stream. Is it worth to special case both the base of returning`Unit`, and the case of compiling straight after, when the existing solution is short and intuitive?

> . Specially, I do not think that a Stream[F, Unit] makes much sense.

Why not? `Stream` has several capabilities that go beyond `IO` , so there are very many places where it makes sense to be in `Stream`, even if the `Stream` is `Stream[F, Unit]`. For example, a very typical case is representing each concurrent process happening in your application as a `Stream[F, Unit]`, which then get `parJoin`ed in `main`, and that's because the concurrency model offered by fs2 is much more high level, safer and composable than raw `Fibers`.

> I would also believe that is the reason evalTap exists

`evalTap` is just syntactic sugar when you want to evaluate an effect but return the input value.

> Finally, as I said, I guess (certainly I do not know) that if it is added on the Compiler it may be more performant than the current solution, as evalMap waits for a value, that at the end is an Unit, than then is discarded by the drain

I think this is introducing a different thing: asynchrony. You can't really do that without violating the semantics of fs2, which is that concurrency is handled by explicit combinators.

----

Overall, I don't think there is a very strong reason for inclusion, but tbh I didn't really mind either way (which is why I haven't commented on the issue so far). However, @Daenyth 's point about complicating things by introducing inconsistency is valid

**Comment by BalmungSan** [comment]
> because the concurrency model offered by fs2 is much more high level, safer and composable than raw Fibers.

Totally agree. But, correct me if I am wrong, but for a **Stream** that represents only side effects, that can be concurrently composed with others, `Stream[F, Nothing]` is a better representation, as it explicitly states that is a continuous computation that is performing side-effects but never produces a value.
But well, I suppose this really do not brings too much value to the discussion.

Thus, given there would not be any performance gains. The only points that remains is consistency and readability of the code.
I agree that having multiple ways of doing things brings extra complexity. But I still believe the `foreach` method would be more readable.
_(Also, I still think there are not the same thing, `evalMap` is still more general than `foreach`. It is true you can replace any `foreach` with `evalMap`, but the opposite does not hold)_.

For now I will leave this open, in case more people wants to share their opinions about this.

**Comment by BalmungSan** [comment]
I am closing given there are not more opinions about this, and there are good reasons not to do it.
Thanks for the answers.
