### ISSUE TITLE
`showLinesStdOut` and friends could keep the elements unchanged

### ISSUE THREAD

**Issue by kubukoz** [functional-streams-for-scala/fs2#1569]
Currently `showLinesStdOut` uses `evalMap` to print each element, discarding its value. I think these operators would be much more useful if they kept the original elements (so that there's a nice and easy way to debug the values of a stream at a stage without having to reimplement `showLinesStdOut` with `evalTap`).

**Comment by ChristopherDavenport** [comment]
`.observe` lets you have this semantic rather than passing through what is effectively an outlet of values.

**Comment by kubukoz** [comment]
Right, `.observe(_.showLinesStdOut)` does the job. It would be nice to have a faster way of doing this, especially repeatedly, like `.through(debug)`... we could have a pipe like that in the package object or Stream/Pipe's companion.

**Comment by mpilquist** [comment]
I like making debugging simpler. Signature of `debug` could be tricky. Where would it write elements? Does it need to take a `String => F[Unit]`?

**Comment by kubukoz** [comment]
I'd say we could add a specific one for starters (just `debug(tag: String)` that prints to stdout) and that'll be it... and maybe `debugToString` that won't require `Show`, and just `toString` the elements before printing.

A function for debugging that takes `String => F[Unit]` would be pretty similar to `evalTap`, so I'm not sure it'd be worth the hassle... but anything that allows skipping `s => Sync[F].delay(println("tag: " + s))` will be a welcome change.

**Comment by kubukoz** [comment]
The greatest problem with `observe` is that it requires Concurrent, IMO. I think we could start with `def debug(tag: String): Stream[F, O]` that outputs `$tag: $elem` to stdout.
