### ISSUE TITLE
Effectful filtering of streams operators

### ISSUE THREAD

**Issue by kubukoz** [functional-streams-for-scala/fs2#1570]
I often find myself looking for an operator that would allow filtering the stream with an effectful function.

Something like `def evalFilter(f: A => F[Boolean]): Stream[F, A]`, maybe also `def evalMapOption[B](f: A => F[Option[B]]): Stream[F, B]` (similar to how `TraverseFilter`'s methods look like).

I would like to contribute these, if it looks like a good idea.

**Comment by mpilquist** [comment]
👍 from me.

**Comment by kubukoz** [comment]
Done in #1619
