### ISSUE TITLE
Feature request: max chunk size on output of groupAdjacentBy

### ISSUE THREAD

**Issue by danxmoran** [functional-streams-for-scala/fs2#1588]
As a toy example, given a stream like this:
```scala
Stream(x, x, x, y, x, y, y, x)
```
And a max size of `2`, I want to get an output of:
```scala
Stream(Chunk(x, x), Chunk(x), Chunk(y), Chunk(x), Chunk(y, y), Chunk(x))
```
I couldn't figure out how to do this using existing methods on `Stream`, so I ended up copying the definition of `groupAdjacentBy` into my project and tweaking it. I'd be more than happy to contribute the changes back to fs2 if there's interest!

**Comment by mpilquist** [comment]
@danxmoran Someone else recently asked about this, as a way to guard against groups getting too big and filling memory. I think it's a good idea and a PR is welcome. To preserve binary compatibility, we'd need a new method name like `groupAdjacentByLimit` or something.
