### ISSUE TITLE
Release 1.1.0 or 2.0.0?

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#1600]
The series/1.1 branch has some source and some binary incompatibilities with series/1.0. These incompatibilities are minor for fs2-core and a bit more involved for fs2-io.

FS2 has always used the `epoch.major.minor` versioning scheme, where a change in the major component signaled breakage. Upstream dependencies like cats and cats-effect use `major.minor.patch`. 

Do we want to change to `major.minor.patch` and release FS2 2.0.0 this week, alongside Cats 2.0.0 and Cats Effect 2.0.0?

**Comment by pchlupacek** [comment]
I have no preference there :-) Although I believe longer term it would be hard to always sync with cats.effect versioning.

**Comment by ChristopherDavenport** [comment]
My horse in this race, is if we all use semver, it means every patch version for fs2 implies a minor version for http4s as we move towards 1.0 ourselves. Which means there are no versions people can upgrade to safely and know semantics may not have changed.

**Comment by kubukoz** [comment]
I prefer 2.0.0. It's different to see 1.0.0 vs 0.10.0 and 1.1.0 vs 1.0.0. As a user, I'd be surprised if I had 1.1.0 in my transitive dependencies and saw binary compat issues.

**Comment by mpilquist** [comment]
Alright, let's go with 2.0.0 then. I agree we won't always by number synchronized with cats/cats-effect.
