### ISSUE TITLE
Split Stream.scala and StreamSpec.scala into smaller files

### ISSUE THREAD

**Issue by kubukoz** [functional-streams-for-scala/fs2#1602]
I imagine Stream's companion object could extend a trait that'd be in a separate file, for starters. Then it could be split into StreamInstances and StreamFunctions.

StreamSpec could be split much easier, by groups of related tests (e.g. RegressionSpec, EvalMapTests etc.).

The reasons for this suggestion:

- incremental compilation is slow due to having to recompile the whole file which is thousands of lines long
- formatting takes a looot of time
- `testOnly` is very slow if you can't specify specific test names (i.e. in bloop)
- (probably not so relevant) the files are impossible to browse on GH with mobile browsers as they hang the whole application.

**Comment by mpilquist** [comment]
Re: tests, try this: `testOnly StreamSpec -- -z evalMap` -- this will run all tests with the word `evalMap` in test name.

It would be nice to improve incremental compilation and speed up formatting. We could move formatting to a CI check instead of formatting on save perhaps. I'm not a big fan of `StreamInstances` and `StreamFunctions` as I find it difficult to find stuff and difficult to move various constructors and functions around so it's accessible everywhere it's needed to make the file modularization work.

**Comment by SystemFw** [comment]
> I'm not a big fan of StreamInstances and StreamFunctions as I find it difficult to find stuff and difficult to move various constructors and functions around so it's accessible everywhere it's needed to make the file modularization work.

There is definitely some level of personal preference here, but I agree with Michael. I really care about having  a tiny top level scope (in terms of files), and quickly navigate the structure of the library, at the cost of bigger files. Compare the top level of fs2 0.9 and what we have now and you'll see this tendency at work.
 Others (for example Alex) prefer having many small files (you can see that in cats-effect `internal`, one file per op)

**Comment by kubukoz** [comment]
> Re: tests, try this: `testOnly StreamSpec -- -z evalMap` -- this will run all tests with the word `evalMap` in test name.

It works in sbt, but not bloop :/.

> We could move formatting to a CI check instead of formatting on save perhaps

A CI *check* will be frustrating. A CI auto-commit to upstream that does formatting would be much better. But I haven't seen that work so far.

I can see some benefit in having everything in a single place, but in the age of IDEs and Metals it's also easy to search for a symbol and navigate to it. It doesn't help discoverability though.

I think we could at least move the typeclass instances to another file - that doesn't hurt so much because instances aren't as much part of an explicit API as a "bridge" to cats and cats-effect. Not sure if this is a large enough amount of code to make a difference.

As a user, I agree with all your points. As a wannabe contributor, it slowed down the feedback loop quite significantly and I think we could do better.
