### ISSUE TITLE
Add  repeatNWhile(n,O => Boolean)?

### ISSUE THREAD

**Issue by nesteg** [functional-streams-for-scala/fs2#1626]
Example:
Stream.eval(IO(0))
 .repeatNWhile(3,_ == 0)
 .compile
 .last
N == 3 last == Option(0)

Stream.eval(IO(1))
 .repeatNWhile(3,_ == 0)
 .compile
 .last
N == 1 last  == Option(1)

**Comment by SystemFw** [comment]
I would rather not add new functions that you can easily get with existing combinators, because they hurt discoverability.
For example you can obtain the behaviour you want with 
```
.repeat
.takeThrough(_ == 0)
.take(3)
```

**Comment by nesteg** [comment]
Sank you.
