### ISSUE TITLE
Reactive streams conversion doesn't cancel upstream if there are no elements processed

### ISSUE THREAD

**Issue by Avasil** [functional-streams-for-scala/fs2#1638]
Hello, I feel like there might be an issue with reactive streams conversions:

```scala
implicit val cs = IO.contextShift(ExecutionContext.global)
implicit val timer = IO.timer(ExecutionContext.global)

val source = 
  Stream.repeatEval(IO.pure(1))
    .evalTap(_ => IO(println("next elem")))
    .onFinalize(IO(println("1: finalize")))

val fs2 =
  source.toUnicastPublisher
    .toStream[IO]
    .onFinalize(IO(println("2: finalize")))
    .interruptAfter(0.second)

fs2.compile.drain.unsafeRunSync()
```
It only prints `2: finalize`. Perhaps it is a feature because it is pull-based but it can be a problem for push based stream like `Observable`:

```scala
implicit val cs = IO.contextShift(ExecutionContext.global)
implicit val timer = IO.timer(ExecutionContext.global)
implicit val s = Scheduler.global

val source = Observable.repeatEvalF(IO.pure(1))
  .doOnNextF(_ => IO(println("next")))
  .guaranteeF(IO(println("1: finalize")))

val fs2 =
  source.toReactivePublisher
    .toStream[IO]
    .onFinalize(IO(println("2: finalize")))
    .interruptAfter(0.second)
```
prints
```
next
2: finalize
```

I tested on fs2 `2.0.0` and Monix `3.0.0`

The original issue is here: https://github.com/monix/monix/issues/1001 /  https://github.com/megri/http4s-monix-issue it is solved with a workaround but I wanted to fix the underlying problem and came up with the above. It seems to be happening only if a websocket is closed before it could process any elements, otherwise it works fine.

**Comment by mpilquist** [comment]
In this case, the `interruptAfter(0.second)` is causing interruption to occur before the upstream is even opened. You can see this by changing `source` to log acquisition in addition to finalization:

```scala
 val source =
    Stream.bracket(IO(println("1: acquire")))(_ => IO(println("1: finalize"))) >>
      Stream.repeatEval(IO.pure(1)).evalTap(_ => IO(println("next elem")))
```

This also prints just `2: finalize`, showing that the source is never opened.

**Comment by mpilquist** [comment]
Closing but feel free to reopen if you think there's still an issue here that's not explained by the above.
