### ISSUE TITLE
Add a combinator for (OutputStream => Unit) => Stream[F, Byte]

### ISSUE THREAD

**Issue by Daenyth** [functional-streams-for-scala/fs2#1641]
Some java apis accept an `OutputStream` as an input parameter, which they then write to. A combinator that exposes the results of those writes as an fs2 stream is desirable for wrapping such libraries; `(OutputStream => Unit) => Stream[F, Byte]`

I'll PR this to `fs2-io` as I have time, based on my previous work:  https://gist.github.com/Daenyth/9a569040a4333595b2be4019d1bc6b91

**Comment by djspiewak** [comment]
Should this signature be `(OutputStream => F[Unit]) => Stream[F, Byte]`? Beyond that, I love it. This is a great type signature.

**Comment by Daenyth** [comment]
Likely I'll go with the `F[Unit]` version as it's trivial to lift the former to the latter with `Sync` (which you'd need for this structure anyway)
