### ISSUE TITLE
Alternative, efficient, extensible replacement for `to`

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#1654]
We currently support building a collection from a stream via the `.to` method:

```scala
@ Stream(1, 2, 3).intersperse(0).compile.to[List]
res1: Id[List[Int]] = List(1, 0, 2, 0, 3)

@ Stream(1, 2, 3).intersperse(0).compile.to[Array]
res2: Id[Array[Int]] = Array(1, 0, 2, 0, 3)
```

This uses the stdlib collection building support -- `scala.collection.Factory` in 2.13+:

```scala
def to[C[_]](implicit f: Factory[O, C[O]]): G[C[O]] =
  compiler(self, () => f.newBuilder)(_ ++= _.iterator, _.result)
```

Some downsides of this approach:
 - It doesn't support efficiently building a `String` from a `Stream[F, String]`
    - There's no `Factory[String, String]` though we could provide one
    - You can't specify `.to[String]` as the kind is wrong
 - Similar problems exist for building a `ByteVector` from a `Stream[F, Byte]`
 - Building an `Array[Byte]` from a `Stream[F, Byte]` is inefficient as each byte element of each chunk is boxed/unboxed when added to the array builder (due to use of `_ ++= _.iterator`). This could be somewhat mitigated by adding some instanceof checks and using `bldr.addAll(chunk.toArray)`.

As an alternative to `to`, we could offer `collect` (name credit to Java 8 stream API):

```scala
def collect[X](cb: ChunkCollector[O, X]): G[X] =
  compiler(self, () => cb.newBuilder)((acc, c) => { acc += c; acc }, _.result)

trait ChunkCollector[A, X] {
  def newBuilder: ChunkAwareBuilder[A, X]
}

trait ChunkAwareBuilder[A, X] { self =>
  def +=(c: Chunk[A]): Unit
  def result: X
}
``` 

We'd have instances like:

```scala
def stringFromStrings: ChunkAwareBuilder[String, String] =
  new ChunkAwareBuilder[String, String] {
    private[this] val builder = new StringBuilder
    def +=(c: Chunk[String]): Unit = c.foreach(s => builder ++= s)
    def result: String = builder.toString
  }

def byteVector: ChunkAwareBuilder[Byte, ByteVector] =
  new ChunkAwareBuilder[Byte, ByteVector] {
    private[this] var acc = ByteVector.empty
    def +=(c: Chunk[Byte]): Unit = acc = acc ++ c.toByteVector
    def result: ByteVector = acc
  }

def fromFactory[A, C[_], B](f: Factory[A, C[B]]): ChunkAwareBuilder[A, C[B]] =
  fromBuilder(f.newBuilder)

def fromIterableFactory[A, C[_]](f: IterableFactory[C]): ChunkAwareBuilder[A, C[A]] =
  fromBuilder(f.newBuilder)

private def fromBuilder[A, C[_], B](builder: Builder[A, C[B]]): ChunkAwareBuilder[A, C[B]] =
  new ChunkAwareBuilder[A, C[B]] {
    def +=(c: Chunk[A]): Unit = builder ++= c.iterator
    def result: C[B] = builder.result
  }
```

This would give us usage like:

```scala
scala> Stream(1, 2, 3).intersperse(0).compile.collect(List)
res2: cats.Id[List[Int]] = List(1, 0, 2, 0, 3)

scala> Stream(1, 2, 3).intersperse(0).compile.collect(Array)
res3: cats.Id[Array[Int]] = Array(1, 0, 2, 0, 3)

scala> Stream(1, 2, 3).intersperse(0).map(_.toByte).compile.collect(ByteVector)
res4: cats.Id[scodec.bits.ByteVector] = ByteVector(5 bytes, 0x0100020003)
```

This works for efficient string building as well:

```scala
scala> Stream(1, 2, 3).intersperse(0).map(_.toString).compile.collect(ChunkCollector.string)
res5: cats.Id[String] = 10203
```

Here we have to use `ChunkCollector.string` directly -- we can't use `.compile.collect(String)` b/c `String` is a type alias for `java.lang.String` and has no companion.

Thoughts? I have a working prototype of this all that I can clean up.

**Comment by Daenyth** [comment]
I've wanted *exactly* this behavior for a while. I could bikeshed on the naming a little bit, but that could be done later ;)

I think it's worth exposing a `.compile.foldChunks(z)((acc, chunk) => ...)` method. The mutable builder design could still be implemented by that

**Comment by mpilquist** [comment]
:+1: Name suggestions welcome. I'm not thrilled with `collect`. I also worry that the API is less discoverable -- e.g., folks might not realize that `.compile.collect(ByteVector)` exists and is efficient.

BTW, we have `.compile.foldChunks` now

**Comment by mpilquist** [comment]
OK I opened a draft PR in #1656. I was able to get an overload of `.to` working so we have `s.compile.to(List)` and `s.compile.to(ByteVector)` now, in addition to `s.compile.to[List]`.
