### ISSUE TITLE
Import fs2-crypto in to fs2-io project

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#1696]
@AdamChlupacek @pchlupacek Any objections to importing [fs2-crypto](https://github.com/Spinoco/fs2-crypto) in to the fs2-io project? I know initially, we decided to keep this separate (#102) but API seems stable and downstream projects use it so I think it would be good to be released all together now. I'm happy to do the work, just want to make sure you both are okay with it.

**Comment by mpilquist** [comment]
Preview here: https://github.com/functional-streams-for-scala/fs2/compare/master...mpilquist:topic/tls?expand=1

**Comment by pchlupacek** [comment]
@mpilquist go ahead and thanks :-)

**Comment by mpilquist** [comment]
@pchlupacek @AdamChlupacek When working on tests, I noticed that `TLSEngineSpec` fails on JDK11 -- both on fs2-crypto repo and in the ported version.
```
[info]   - client-initiated *** FAILED *** (938 milliseconds)
[info]     java.lang.Throwable: Expected fs2.io.tls.TLSEngine$DecryptResult$Decrypted but got Handshake(empty,None)
```

That error is received here:

```scala
hsToServer3 <- cast[DecryptResult.Decrypted[IO]](tlsClient.decrypt(hsToClient2.data))
```

I also noticed that `HandshakeResult` has new enumeration values in JDK11, though I confirmed we're not hitting those cases in this test.

I'm thinking of writing tests at the `TLSSocket` level instead of `TLSEngine` level, given the JDK dependent differences here. I guess alternatively, we could require tests be run under JDK11 and figure out what needs to change here to make this test pass, but that seems too coupled to JDK version. Thoughts?

**Comment by mpilquist** [comment]
The previous line -- computing `hsToClient2` -- results in `BUFFER_UNDERFLOW` case. Adding some printlns gives this:

```scala
hsToClient1 <- cast[DecryptResult.Handshake[IO]](tlsServer.decrypt(hsToServer1.data))
hsToServer2 <- cast[DecryptResult.Handshake[IO]](tlsClient.decrypt(hsToClient1.data))
_ = println(s"hsToServer2: $hsToServer2")
hsToClient2 <- cast[DecryptResult.Handshake[IO]](tlsServer.decrypt(hsToServer2.data))
_ = println(s"hsToClient2: $hsToClient2")
hsToServer3 <- cast[DecryptResult.Decrypted[IO]](tlsClient.decrypt(hsToClient2.data))
```

```
hsToServer2: Handshake(Chunk(20, 3, 3, 0, 1, 1),None)
UNDERFLOW Status = BUFFER_UNDERFLOW HandshakeStatus = NEED_UNWRAP
bytesConsumed = 0 bytesProduced = 0
SPECIAL CASE - Result(empty,false,false,false,true)
hsToClient2: Handshake(empty,None)
UNDERFLOW Status = BUFFER_UNDERFLOW HandshakeStatus = NEED_WRAP
bytesConsumed = 0 bytesProduced = 0
SPECIAL CASE - Result(empty,false,false,false,true)
```

**Comment by mpilquist** [comment]
Can fix on JDK11 by requesting `TLSv1` SSLContext instead of just `TLS`, which defaults to TLS 1.3.

**Comment by djspiewak** [comment]
Shouldn't the name of this kind of module be something like **fs2-tls** rather than **fs2-crypto**? Quite a bit of streaming crypto is not TLS.

**Comment by mpilquist** [comment]
@djspiewak On the branch, it's just a new `fs2.io.tls` package inside the existing `fs2-io` module

**Comment by mpilquist** [comment]
Update: problem is definitely with the TLS 1.3 handshake. Issue reproduces when forcing TLS 1.3 and connecting to google.com:443. With the TLS 1.3 handshake, the server sends a ServerHello (0x16), Server Change Cipher Spec (0x14), and encrypted wrapper (0x17). However, `TLSEngine` gets the `ServerHello` and switches to handshake mode due to a `HandshakeStatus.NEED_WRAP`, leaving the 0x14 and 0x17 messages in the original buffer. The underlying `SSLEngine` then generates a Client Change Cipher Spec message and waits for server response, which never comes.

**Comment by mpilquist** [comment]
I pushed an update to my topic/tls branch. I have a simpler version of `TLSEngine` in `TLSEngineSimple.scala` -- it is no where near complete but it makes it further in the TLS handshake than `TLSEngine.scala` does. It gets to the point that the `SSLEngine` thinks the handshake is finished, though it doesn't successfully send the encrypted client verification back to the server. I've spent more time on this than I intended today so I'd appreciate a second pair of eyes. Thanks!

**Comment by pchlupacek** [comment]
@mpilquist thanks a lot for following this through. Unfortunately these issues are hard to debug and we still find time-to-time some corner cases that need to be "implemented". The Java SSL engine has unfortunately very complex unlucky API, which makes its abstraction unbelievably complex. 
I'll ask @AdamChlupacek @mraulim to take eyes on this.

**Comment by mpilquist** [comment]
I pushed an update today that changed the default `TLSEngine` back to the one from fs2-crypto. I also added some improved logging -- red output is from `TLSSocket` whereas the uncolored output is from JDK `SSLEngine`. I haven't made much progress on the underlying issue though I suspect it's related to having both two sets of wrap buffers and leaving some messages in one of them. I might poke at this again tomorrow -- pointers are appreciated.

**Comment by ChristopherDavenport** [comment]
An absurd amount of logging later, will add more and see if we can get even clearer data.
https://gist.github.com/ChristopherDavenport/65d567299c1dbefa1918e3e2d5750dc0

**Comment by mpilquist** [comment]
I've gotten this working on topic/tls branch. I wrote a new `TLSEngine` that's given a `write` and `read` callback that the engine can use when needing to access network.

One thing outstanding is how to guard against a concurrent read & write from both trying to perform the handshake.
