### ISSUE TITLE
Style change: replace ShouldMatchers in tests with assertions

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#1764]
Example rewrites:

|Before|After|
|----|----|
|`x shouldBe y`|`assert(x == y)`|
|`x should be < y`|`assert(x < y)`|
|`an[Exception] shouldBe thrown by f`|`assertThrows[Exception](f)`|

I recently made this same change to scodec-bits (in topic/dotty branch for now) and found the result much simpler to read. Note that `assert` is macro-powered and if the assertion fails, you still get details on the cause of the failure:

```scala
scala> val xs = List(1, 2, 3)
xs: List[Int] = List(1, 2, 3)

scala> assert(xs.reverse == List(3, 2, 1, 0))
org.scalatest.exceptions.TestFailedException: List(3, 2, 1) did not equal List(3, 2, 1, 0)
```

**Comment by SystemFw** [comment]
yes please :)

**Comment by mgibowski** [comment]
So following this:

|                                              Before  |  After                                           |
| --------------------------------- |:-------------------------------:|
|`.asserting(_ shouldBe expected)` |  `.asserting(_ == expected)`.   |

right?

**Comment by mpilquist** [comment]
Yeah, that would be great though not sure how feasible it is. The most direct translation is sort of annoying -- `.asserting(x => assert(x == expected))`

**Comment by mgibowski** [comment]
I did some initial work in the branch above. 
I couldn't introduce a new `.asserting(_ == expected)` while keeping the old one with the same name on Scala 2.12 (on 2.13 it worked).

So for compatibility with 2.12 I introduced a new function: 
`.assert(_ == expected)` (taking `f: A => Boolean` as an argument)

The old one (which operates on `Assertion`) is still useful when there are multiple assertions to check, like here:
```
.asserting {
  case (ok, open) =>
  assert(ok == N)
  assert(open == 0)
}
```

**Comment by mpilquist** [comment]
The major downside of `def assert(f: A => Boolean): F[Assertion]` is that we lose info about the actual and expected values. We could write our own macro but that makes cross building more difficult and I'd prefer to avoid macros.

**Comment by mgibowski** [comment]
Yes, after some trials I also came to this conclusion. In any way - I will work on this issue. I will write here if there are some issues or converting all matchers is too much for me.

**Comment by mpilquist** [comment]
Sounds good, thanks for the help!
