### ISSUE TITLE
Add cats.Align instance for fs2.Stream

### ISSUE THREAD

**Issue by LukaJCB** [functional-streams-for-scala/fs2#1765]
Should be fairly similar to the `zip` implementation

**Comment by bobbyrauchenberg** [comment]
i'd be happy to pick this up

**Comment by bobbyrauchenberg** [comment]
I'm new to FS2 so apologies if it's a stupid question, but is there a case where it's possible to return anything other than `Both[A, B]`? Or is returing Align.Left and Align.Right exactly the point of this work?

What would we do in the case where we have 

```scala
streamA.align(streamB)
```

where `streamA` is `Stream.constant("1")` and `streamB` is `Stream.empty` - looking at the docs for Align, we'd be returning an infinite Stream of `Align.Left(1)`

**Comment by LukaJCB** [comment]
@bobbyrauchenberg good question! 
You are right that returning `Ior.Left` and `Ior.Right` in addition to `Ior.Both` is exactly the point of this work. To answer your question, yes you would get an infinite stream of `Left(1)`.

**Comment by kubukoz** [comment]
Hey @bobbyrauchenberg, that seems to me like the correct behavior. The longer of the two streams will result in having values as `Left` xor `Right` at the end, but the prefix will always be Both. This could probably be made into a nice property test.

**Comment by mpilquist** [comment]
This was fixed by #1791
