### ISSUE TITLE
Support scala.js 1.0

### ISSUE THREAD

**Issue by cquiroz** [functional-streams-for-scala/fs2#1778]
I'm trying to get the typelevel ecosystem to support scala.js, most of the dependencies of fs2 are already there including `cats`, `cats-effect` and `scodec-bits`.

The one sore point is `scalatest`. The set of versions of scalatest is very confusing but scalatest 3.1.0 should support scala.js 1.0.0-RC2. Why does fs2 uses 3.1.0-SNAP13? is that due to the dependency on `scalatestplus-scalacheck`?

**Comment by mpilquist** [comment]
No, it's because that's the last release of scalatest 3.1 which included the new generator stuff. Bill took that out before 3.1 final and then moved it to 3.2. If we could get a scalajs 1.0 version of a scalatest 3.2 milestone, that would solve the issue.

**Comment by a1russell** [comment]
3.2.0-M3 has been published for Scala.js 1. Does that build work for you?

**Comment by mpilquist** [comment]
Unfortunately not - ScalaTest moves their generators to 3.3. I exchanged some emails with Bill last night and he’s going to get a 3.3 snap released.

**Comment by mpilquist** [comment]
This was fixed with the release of 2.3.0.
