### ISSUE TITLE
Reactive streams subscription cannot be handled uninterruptibly

### ISSUE THREAD

**Issue by djspiewak** [functional-streams-for-scala/fs2#1816]
Related to #1638, and also http4s/http4s#3261.

So the `StreamSubscriber` mechanism is quite clever, and the API correctly assumes that actually *registering* the subscriber with the `Publisher` is going to be something which is very use-case and API specific, and thus it isn't captured in the fs2 API whatsoever. That's good. Unfortunately, this paradigm opens up a tricky loophole.

For publishers where `cancel()` must be invoked to avoid leaking resources (which is most of them), it is impossible for users to *uninterruptably* register their subscription and register the finalizer for proper cleanup. As a simplified example:

```scala
StreamSubscriber[F, A] map { sub =>
  Stream.eval(F.delay(publisher.subscribe(sub)) >> sub.stream
}
```

This isn't an unusual paradigm. In fact, almost everyone who is *correctly* using `.stream` is going to do something very much like this. Unfortunately, it is wrong. If the fiber running the resulting `Stream` is canceled during the `>>` cancel boundary, it will leak the upstream stream since `cancel()` cannot be run. It is impossible for user-land code to resolve this issue, since we really need the `F[Unit]` subscription action to be part of the `bracket` which is *inside* of `stream`, but… we don't have access to it.

The solution here is to change `stream` to take an `F[Unit]` which manages the subscription. This keeps it generic so that users can control things, but fs2-reactive-streams itself can juggle the resource management and registration of the finalizer. This change can be done while preserving binary compatibility by overloading `.stream` and deprecating the zero-argument version.

Note that this doesn't *entirely* close the loopholes which surround handling these types of APIs, but it at least fixes the one that cannot be otherwise worked around in userland.

**Comment by SystemFw** [comment]
Tbh when I wrote/refactored the current version of `StreamSubscriber` cancelling in `>>` wasn't even on the horizon, so there might be more bugs like this :)

Do you have a PR/gist we can look at?

**Comment by djspiewak** [comment]
> Do you have a PR/gist we can look at?

Haven't even looked at the implementation yet, but I could quickly. It doesn't seem all that hard to do, at least in theory.

**Comment by djspiewak** [comment]
@SystemFw Turned out to be really easy to fix. PR up. We could probably test this by doing something tricky with latches but am lazy.

**Comment by Daenyth** [comment]
🤔 Is there an IO implementation out there that would allow "fuzzing" these kinds of things by aggressively canceling at arbitrary bind points? Something like cats-effect-laws TestContext but able to configure a percentage of things to be canceled for no reason

**Comment by djspiewak** [comment]
> Is there an IO implementation out there that would allow "fuzzing" these kinds of things by aggressively canceling at arbitrary bind points?

Cats Effect 3 :-D
