### ISSUE TITLE
Guide needs information that fs2.concurrent.Queue needs to be terminated

### ISSUE THREAD

**Issue by arturaz** [functional-streams-for-scala/fs2#1822]
I spent good 3-4 hours debugging what is going on (I'm a FS2 newbie) until I finally realized that queues are infinite and they need to be explicitly terminated.

The example in guide doesn't say anything about it.
https://fs2.io/guide.html#asynchronous-effects-callbacks-invoked-multiple-times

I suggest adding a section about the termination. I can do a pull request if you point me to the right place.

Maybe like this?
```
def rows[F[_]](h: CSVHandle)(implicit F: ConcurrentEffect[F], cs: ContextShift[F]): Stream[F,Row] =
  for {
    q <- Stream.eval(Queue.unbounded[F, Option[Either[Throwable, Row]]])
    _ <- Stream.eval { F.delay { 
      h.withRows(e => F.runAsync(q.enqueue1(Some(e)))(_ => IO.unit).unsafeRunSync)
      // Terminate the queue
      F.runAsync(q.enqueue1(None))(_ => IO.unit).unsafeRunSync
    } }
    row <- q.dequeue.unNoneTerminate.rethrow
  } yield row
```

If you're wondering what I was writing, it was integration between fs2 and 7zip.

https://gist.github.com/arturaz/9a45a8b3807fc625e4feb006b3a94ab1

**Comment by mpilquist** [comment]
Yeah, docs are light on `Queue` -- there's some very brief documentation here: https://github.com/functional-streams-for-scala/fs2/blob/master/site/docs/concurrency-primitives.md

Would be nice to update both the guide example and the queue docs with info about shutdown & propagating errors (e.g., sometimes you want an error thrown by a producer to propagate to consumers)

**Comment by arturaz** [comment]
I can't find the sources for the docs. Are they publicly available? Could you provide me a link?

 I could try to write docs for the guide and submit a pull request.

**Comment by mpilquist** [comment]
The sources are here: https://github.com/functional-streams-for-scala/fs2/tree/master/site/docs

To build a local version of the site, launch SBT and run `microsite/previewSite`. Note you'll need jekyll installed -- some instructions here: https://47degrees.github.io/sbt-microsites/docs/getting-started/

**Comment by arturaz** [comment]
Submitted a pull request: https://github.com/functional-streams-for-scala/fs2/pull/1833
