### ISSUE TITLE
Add chunkAll

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#1834]
A use case for this came up recently so I sketched this solution:

```scala
def chunkAll[F[_], O](s: Stream[F, O]): Stream[F, Chunk[O]] = {
    def loop(s: Stream[F, O], acc: Chunk.Queue[O]): Pull[F, Chunk[O], Unit] =
      s.pull.uncons.flatMap {
        case Some((hd, tl)) => loop(tl, acc :+ hd)
        case None => Pull.output1(acc.toChunk)
      }
    loop(s, Chunk.Queue.empty).stream
  }
```

I decided against opening a PR for a couple of reasons:
1) It's not safe on infinite streams. It wouldn't be our first operation with such an issue but maybe adding more such operations isn't a great idea.
2) It can be simulated with `chunkN(Int.MaxValue, true)` for all safe use cases.

Opening this issue to document the decision. I'm totally okay with closing this as won't fix, but would like some opinions.

**Comment by SystemFw** [comment]
I actually found myself wanting `compile.chunk` recently.
I think in practice there are quite a lot of cases of "I know this portion of the code to be finite, locally".
One particularly common case for me is things where I have to operate at Chunk level, and I want to `Chunk -> Stream -> Chunk`.
I guess what I'm saying is that I see it as legitimate.

I think the main issue for me is why not `chunkN` or even `chunks.foldMonoid`

**Comment by sloshy** [comment]
I'd support this, personally. If I need to `.compile.to(Chunk)`, I'd rather have some shorthand that keeps it in a Stream as well. Considering any of the `.compile.to(X)` operations are not safe on infinite streams, I wouldn't really think this one needs to be either. It just needs a disclaimer of some sort.
