### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by ssanj** [functional-streams-for-scala/fs2#1836]
There seem to be raw markdown links in the documentation:

| page | broken link |
| ----- | ---------- |
| https://fs2.io/concurrency-primitives.html | https://fs2.io/guide.md#talking-to-the-external-world |
| https://fs2.io/guide.html | https://fs2.io/concurrency-primitives.md |

which unfortunately don't work.

I these relative links should have been picked up by Github pages. If the documentation is rendered using a Jekyll instance it may require https://github.com/benbalter/jekyll-relative-links.

An alternative is to use absolute URLs for the above links directly to the fs2.io site.

I'm happy to create a PR with the fixes for the above links but I wondered what the best course of action would be.

**Comment by kubukoz** [comment]
I think we could try using the relative links plugin :)

**Comment by ssanj** [comment]
@kubukoz I've found a workaround that does not involve updating Jekyll and it seems to be used by Doobie so it must be legit ;)

https://github.com/functional-streams-for-scala/fs2/pull/1840

**Comment by ssanj** [comment]
Options for installing a Jekyll plugin: https://jekyllrb.com/docs/plugins/installation/

**Comment by mpilquist** [comment]
Fixed by #1840.
