### ISSUE TITLE
Memory leak when upgrading kafka4s application from 2.0.1 to 2.1.0+

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#1884]
Reported by @hilios on Gitter: https://gitter.im/functional-streams-for-scala/fs2?at=5ec5254d9832dd6f0463cd82

Sample application: https://github.com/hilios/kafka4s/blob/master/fs2/src/it/scala/io/kafka4s/fs2/Fs2KafkaLeak.scala

Appears to leak on 2.1.0+ and be okay on 2.0.1.

**Comment by mpilquist** [comment]
The heap dump shows tons of `CompileScope` instances. Looking through the diffs of 2.0.1 vs 2.1.0, I'm pretty sure the root cause is 1b1ebbf7f.

**Comment by mpilquist** [comment]
With this minimization:

```scala
object RetrySanityTest extends App {
  implicit val cs: ContextShift[IO] = IO.contextShift(ExecutionContext.Implicits.global)
  implicit val timer: Timer[IO] = IO.timer(ExecutionContext.global)
  import scala.concurrent.duration._

  Stream.retry(IO.unit, 1.second, _ * 2, 10).repeat.compile.drain.unsafeRunSync
}
```

I confirmed there's a leak in master and it's fixed by removing scoping in `handleErrorWith`.

**Comment by mpilquist** [comment]
This doesn't leak:
```scala
Stream.eval(IO.unit).attempt.repeat.compile.drain.unsafeRunSync()
```

This does:
```scala
Stream.eval(IO.unit).attempts(Stream.constant(1.second)).head.repeat.compile.drain.unsafeRunSync()
```

**Comment by hilios** [comment]
Thank you for taking a look at this.

Do you think this is an issue caused by the combination of a `retry` with a `repeat` then?

**Comment by mpilquist** [comment]
Manually inserting a scope after `.head` fixes:

```scala
Stream.eval(IO.unit).attempts(Stream.constant(1.second)).head.scope.repeat.compile.drain.unsafeRunSync()
```
