### ISSUE TITLE
Documentation for s.as[O2]

### ISSUE THREAD

**Issue by kamilkloch** [functional-streams-for-scala/fs2#1909]
Hi all,

I just noticed a small inconsistency in `s.as[O2]` documentation, which reads:
`Alias for _.map(_ => o2)`. It is not true - `s.as(o2)` memoizes `o2` and `s.map` does not:

```scala
def rnd: Int = scala.util.Random.nextInt(3)
println(Stream(1, 2, 3).as(rnd).toList) // List(1, 1, 1)
println(Stream(1, 2, 3).map(_ => rnd).toList) // List(1, 0, 1)
```
Granted, it is a minor glitch and `as` should not be fed an impure function in the first place, but perhaps the doc should be changed to: Alias for `val o2Memoized = o2; _.map(_ => o2Memoized)`?

**Comment by kubukoz** [comment]
Fixed in #1910
