### ISSUE TITLE
Add `withFilter` to Stream in order to filter in for comprehensions

### ISSUE THREAD

**Issue by hogiyogi597** [functional-streams-for-scala/fs2#1971]
It was brought up in a few Gitter posts recently that it would be nice to have a `withFilter` alias for `filter` to allow `Stream`s to be used in for comprehensions.

https://gitter.im/functional-streams-for-scala/fs2?at=5f0f056215779f6fdca8c090
https://gitter.im/functional-streams-for-scala/fs2?at=5f207b56e90668200523130e

I am planning on adding this and using this issue to track progress.

**Comment by kubukoz** [comment]
I was convinced Scala falls back to `filter` if `withFilter` isn't defined. Has that changed recently, or is my memory failing me?

**Comment by hogiyogi597** [comment]
@kubukoz It looks like it might have been removed. I am not totally familiar with it but I did find this:
https://github.com/scala/bug/issues/6455

If I remove my `withFilter` method and try to use it in the for comprehension in my test I get this error:
```scala
[error] /Users/shogan/_Personal/scala_fp/fs2/core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala:1240:30: value withFilter is not a member of fs2.Stream[[x]fs2.Pure[x],Int]
[error]         value <- Stream.range(0, 10)
[error]                              ^
[error] one error found
```

**Comment by kubukoz** [comment]
Ah, i think I actually saw that. Thanks
