### ISSUE TITLE
Topic does not support any form of backpressure

### ISSUE THREAD

**Issue by djspiewak** [functional-streams-for-scala/fs2#244]
Please correct me if I'm wrong…

As far as I can tell from the implementation of `Topic`, the queuing of incoming data (which is subsequently dequeued and read by subscribers) is handled entirely by the `Strategy` in question, which defaults to a cached thread pool.  Cached thread pool is implemented using an *unbounded* queue.  This means that if the writers pushing data into a topic are moving faster than the slowest subscriber, memory will progressively fill and the application will (ultimately) crash.  The only way to avoid this is to pass a non-default `Strategy` which wraps an `ExecutorService` which implements the *semantics* of cached thread pool but atop a bounded queue.

This is incredibly clumsy and very difficult to discover for a new user.  A better solution is to implement an internal queuing mechanism within the topic sink to bound outstanding elements to some finite, user-specified limit.  This would allow us to still use the implicit `Strategy` (which is the correct design, I believe) while giving API consumers a way to easily and by-default avoid resource-related DoS issues.

**Comment by pchiusano** [comment]
Punting on this until after 0.9 is out

**Comment by pchlupacek** [comment]
fixed by #627
