### ISSUE TITLE
Redesign wye combinators for doing bounded merges and zips (was: behavior of wye.drainR and wye.drainL)

### ISSUE THREAD

**Issue by alissapajer** [functional-streams-for-scala/fs2#260]
`wye.drainR` (and `wye.drainL`, which is implemented in terms of `drainR`) are displaying behavior contradictory to what I expect. To note, I didn't find any examples, usages in the source, or tests for either of these two functions. What was the intent for these functions?

Here is the example I've constructed (thanks to @dcsobral for the idea to use `Process.awakeEvery`).

``` scala
import scalaz.concurrent._
import scalaz.stream._
import scala.concurrent.duration._

implicit val x = scalaz.stream.DefaultScheduler

def effectSink: Sink[Task, Int] = {
  def effect(ii: Int): Task[Unit] = Task delay { println(s"GOT $ii") }
  Process.constant(effect _)
}

// a process that can provide 17 Ints before halting, observed through a println
val initial: Process[Task, Int] = Process.emitAll(0 until 17) observe effectSink

val slowProcess: Process[Task, Duration] = Process.awakeEvery(1.seconds)

// 11 because it's prime, avoiding divisibility coincidences with the above 17
val result: Process[Task, Int] = initial.wye(slowProcess)(wye.drainR(11))

result.runLog.run
```

And here is the output I see, where the messsages `GOT 0` through `GOT 11` (12 total) print instantaneously, and then a subsequent `GOT` message prints every `1.seconds` until the process `initial` has naturally halted, at which point `result` halts as well and the `Vector` is printed.

``` scala
scala> result.runLog.run
GOT 0
GOT 1
GOT 2
GOT 3
GOT 4
GOT 5
GOT 6
GOT 7
GOT 8
GOT 9
GOT 10
GOT 11
GOT 12
GOT 13
GOT 14
GOT 15
GOT 16
res0: IndexedSeq[Int] = Vector(0, 1, 2, 3, 4, 5)
```

There are two (maybe three) behaviors demonstrated here that are contrary to what I expect.

(1) `res0` is a seq with only the first `6` numbers pulled from `initial`, where `6 = 17 - 11`. Specifically, `result.runLog.run` outputs a seq with size `m - n` where `m` is the the total number of elements pullable from `initial` before it halts, and `n` is the parameter in `wye.drainR(n)`. Running the final process eventually pulls everything possible from `initial`, but then only provides the first `m - n` numbers in its final output seq. For an experiment, I just let `n = 100` and `m = 17`. `17 - 100` is negative, and as fits the pattern, `Vector()` was output.

(2) The `GOT` messages don't print all at once, but instead print 1 per second (determined by constant `1.seconds`), once the first `n+1` messages have printed. Now the `n` parameter in `drainR(n)` refers to, if I understand correctly, the size of the buffer that's created as messages are pulled through the `wye` from the right and the left. But since a `println` prints only every 1 second, inside the `wye` we wait until something has been successfully pulled from the right before pulling from the left, and then wait again, so the buffer is essentially staying at size 0. Is the intention to limit the flow of elements through the `wye` in accordance with how frequently elements from the right are available?

(2.5) As a second experiment, I instead drained `initial`, so that we have instead `slowProcess.wye(initial)(wye.drainR(11))`. And now the results were entirely as expected, with the `result.runLog.run` outputing the entire expeced seq. So this issue does not manifest itself when the process we're draining (right-side proecss) is "faster" than than the left process. This is consistent with what's been observed above.

(3) Lastly, was the intent for `drainR` to terminate when either the left or the right side terminates? For my use cases, instead of `initial.wye(slowProcess)(wye.drainR(n))` I've been using `initial.wye(slowProcess.drain)(wye.merge)` (or `wye.mergeHaltBoth`, for example), and this has suited my needs. 

What do you think? Thanks! :)

**Comment by pchiusano** [comment]
I still think this is worth doing, but I'm going to punt until after 0.9 unless someone speaks up who is willing to take on the design and testing necessary.

**Comment by pchlupacek** [comment]
This issue is mostly relevant to 0.8 design. In 0.10 we do things differently, and I am going to close this for now. If this will raise somehow differently with 0.10 suggest open different issue, more relevant to 0.10.
