### ISSUE TITLE
Mac implementation of `tcp` occasionally hangs on socket close

### ISSUE THREAD

**Issue by pchiusano** [functional-streams-for-scala/fs2#275]
Issue is seemingly triggered by concurrent reads and writes to an `AsynchronousSocketChannel`. See `TcpSpec`:

```Scala
  property("echo") = forAll { (msgs0: List[String]) =>
    val msgs = ("woot" :: msgs0).map(_ + "!") // ensure nonempty
    val out = Process(msgs: _*).pipe(text.utf8Encode)
    echoTest(msgs) {
      tcp.lastWrites_(out) ++
      tcp.reads(1024).pipe(text.utf8Decode)
    } &&
    echoTest(msgs) {
      tcp.lastWrites(out).tee(tcp.reads(1024))(tee.drainL)
         .pipe(text.utf8Decode)
    } && {
      // NB: this version occasionally causes problems on mac
      // the AsynchronousSocketChannel.close operation hangs indefinitely,
      // even though all read/write operations have completed on the socket
      // This appears to be a JDK bug
      if (System.getProperty("os.name").contains("Mac")) true
      else echoTest(msgs) {
        tcp.lastWrites_(out) merge tcp.reads(1024).pipe(text.utf8Decode)
      }
    }
  }
```

Also see discussion in #250. We would be grateful if anyone more knowledgeable can find a workaround or fix for this issue.

**Comment by pchiusano** [comment]
I am curious if this is still a problem, especially with JDK 8. Linking in #529

**Comment by djspiewak** [comment]
@pchiusano I tested it on JDK 8 a few months ago.  It was still a problem.  I was also able to minimize the issue quite a bit (at least in terms of the surrounding context) and even spent a bit of time digging into the underlying native code.  As far as I can tell, it's a bug in Darwin itself (something to note is that the host process becomes zombied until your machine restarts whenever this happens).  It's probably possible to work around it in userland, but clearly non-trivial.

**Comment by pchiusano** [comment]
@djspiewak For your testing, were you using scalaz-stream, or the NIO API directly? I am vaguely hopeful that there was something about the way the old scalaz-stream impl was using the API that caused the problem (like maybe not having #535) and that things will miraculously work with the new implementation. :)

**Comment by djspiewak** [comment]
I minimized it to the NIO2 API directly.  As I said, I wouldn't be entirely surprised if there was a way to somehow use NIO2 API to work around the problem in the kernel, but that sounds like a pretty intense bit of investigation to find.

**Comment by pchiusano** [comment]
Ok, good to know. :\ If this is a Darwin bug, we can't be the first people
to hit it. Is it an issue that Apple already knows about and is tracked
somewhere?

**Comment by djspiewak** [comment]
@pchiusano I couldn't find any mention of it elsewhere, other than a passing hit in a (broadly unrelated) Netty bug.  The Netty guys just dodged it, since the problem wasn't really central to what they were doing.

People aren't really using NIO2 very much, and the APIs that NIO2 is using on Darwin are different than the old async IO APIs, afaik.  Add to this the fact that most serious NIO applications are going to be run and tested on Linux and NIO already has a deserved reputation of platform-specific quirks.  We're now getting to the edge of my knowledge on the problem, but it doesn't surprise me all that much that other people haven't really hit it, or if they have hit it, they've just put it down to "platform specific weirdness" and just done all their testing on Linux.

**Comment by pchiusano** [comment]
Makes sense.

Btw, I think I came across that same Netty issue and even asked if they had
more info: https://github.com/netty/netty/issues/852#issuecomment-57022548

**Comment by slandelle** [comment]
Hi there,

Just to let you know that I ran into the same issue with sshd: https://issues.apache.org/jira/browse/SSHD-666

**Comment by pchlupacek** [comment]
@pchiusano I don't expreincing any of these with 0.9 tcp. Do you still have that issue? Running jdk 1.8.0_40.

**Comment by pchiusano** [comment]
I don't actually remember the test that triggered this. But I can try
running the tcp tests when back in front of computer.

**Comment by pchlupacek** [comment]
@mpilquist @pchiusano I didn't had that behaviour since 0.9 implementation. I suggest to close this.
