### ISSUE TITLE
tee should propagate EarlyCause to its Processes

### ISSUE THREAD

**Issue by dansanduleac** [functional-streams-for-scala/fs2#288]
I have a situation where I'm sending a source through a sink that is built in a similar way to `io.bufferedChannel` (when `O=Unit`):

```scala
 def bufferedSink[F[_],R,I,O](acquire: F[R])(
                               onKill: R => F[Unit])(
                               onComplete: R => F[Unit])(
                               step: R => F[I => F[Unit]]): Sink[F,I] = {
    // Slightly more advanced `io.bufferedChannel` which is specialized for Sink: it has an onKill finalizer  (similar to bufferedChannel.flush) which I expect to only run if there were no errors. 
    import scalaz.stream.Process._
    eval(acquire).flatMap { r =>
      repeatEval(step(r)).onKill(eval_(onKill(r))).onComplete(eval_(onComplete(r)))
    }
  }
```

The only difference (aside from it taking an `F[_]` instead of just Task) is that instead of a `Sink[_, Option[I]]` I return a `Sink[_, I]`, which, admittedly, is what caused this whole issue.

I wrote this kind of sink for an accumulate-then-commit model - you can send stuff to it, and at the end, if it halts gracefully, it will execute `onKill` and commit the stuff that it's been buffering. Specifically in my case, `step` would write to a temporary DB table, `onKill` would merge the temporary table into the destination table, and `onComplete` would close the DB connection. 

However, if I use the standard pattern of `source to sink`, which internally uses `Process.tee`, and there is an error in the `source`, the `sink` won't know about it _at all_: it will just be killed gracefully, and then proceed to commit incomplete data.
Specifically in here:
```scala
final def tee[F2[x] >: F[x], O2, O3](p2: Process[F2, O2])(t: Tee[O, O2, O3]): Process[F2, O3] = {
  import scalaz.stream.tee.{AwaitL, AwaitR, disconnectL, disconnectR, feedL, feedR}
  t.suspendStep flatMap {
    ...
    case Halt(rsn)             => this.kill onHalt { _ => p2.kill onHalt { _ => Halt(rsn) } }
  }
}
```

could we prepend this case to that one:
```scala
    case Halt(c: EarlyCause)   => this.injectCause(c).drain.causedBy(c) onHalt { _ => p2.injectCause(c).drain.causedBy(c) onHalt { _ => Halt(c) } }
```

I've run the tests and only one fails, which I'm having a look at now:
```
[info] ! resource-safety.cleanups: Falsified after 0 passed tests.
[info] > Labels of failing property: 
[info] tee-cln-left r: -\/(java.lang.Exception: bwahahahahaa!) t: List(Error(java.lang.Exception: bwahahahahaa!}), Error(java.lang.Exception: bwahahahahaa!}))
```

**Comment by pchlupacek** [comment]
@pchiusano @dansanduleac do you think this can be closed?

**Comment by dansanduleac** [comment]
Sorry for the long absence - I'm working on a PR now which changes `Kill` to keep track of an `Option[Error]` that might have caused it, which in turn would allow a process to take different actions depending on whether it was halted by 
* a `Kill(None)` i.e. no error occurred in the pipeline, but no more data is required of this process
* a `Kill(Some(_))` i.e. an error occurred somewhere in the pipeline, so if I were planning to perform any operations off the fact that everything completed successfully, I now know _not_ to do that

As I mentioned before, this allows implementing transactional processes and presenting them to users as an API that's easy to use. Specifically, it allows rewriting `io.bufferedChannel` in a way that doesn't require the user to pass in an `Option[I]`, unlike the current approach which forces them to do this every time they use a channel from this API: 
```scala
source.map(Some(_)) ++ (Process(None)) through unwieldyBufferedChannel
```

With this in mind, `io.bufferedChannel` might be rewritten as:
```scala
/**
   * Implementation of resource for channels where resource needs to be
   * flushed at the end of processing.
   */
  def bufferedChannel[R,I,O](acquire: Task[R])(
                             flush: R => Task[Unit])(
                             release: R => Task[Unit])(
                             step: R => Task[I => Task[O]]): Channel[Task,I,O] = {
    eval(acquire).flatMap { r =>
      repeatEval(step(r)).onNormalKill(eval_(flush(r))).onComplete(eval_(release(r)))
    }
  }
```

Where  `flush` would only be called if the kill that came through had no error attached to it. [1] [2]

Users of such a channel could use it simply as `source through channel` and not have to worry about wrapping stuff in an Option.

[1] I agree that `onNormalKill` sounds awful, but I haven't thought of a better name so far.
[2] In this case, `flush` cannot return more items (as in the original implementation of `bufferedChannel`), because it would have to return a `I => Task[O]`, and there would be no more inputs of `I` to give it at that point. But in its place, it seems arguably better to allow users access to a transactional Channel/Sink without asking them to use it any differently than they would use an ordinary Channel.

**Comment by pchlupacek** [comment]
@dansanduleac Are you sure you can solve all the termination propagation in tee and wye and pipe correctly? In case yes, how they will be defined. On wiki there is page describing current behaviour, can you please elaborate on how that will change? 

Thanks a lot for your efforts!

**Comment by dansanduleac** [comment]
@pchlupacek good point - I hadn't looked at `wye` yet, and indeed it needed these changes applied as well. I've added 2 new commits to the PR, which deal with `pipe` and `wye` respectively, and amended the tests in `ResourceSafetySpec` to reflect what I expect should happen.

**Comment by djspiewak** [comment]
This issue came up recently in the Gitter channel.  I was actually completely unaware of this `tee` semantic, but it kinda horrifies me TBH.  I understand the original rationale, but I don't think it is correct.  There needs to be *some* signaling mechanism to alternate legs which indicates either normal or abnormal termination in a main leg.  Here's another simple example of a `ByteVector` sink which implements atomic writes into a file:

```scala
def atomicChunkW(target: String): Sink[Task, ByteVector] = {
  Process.await(Task { File.createTempFile("", "") }) { path =>
    io fileChunkW path onHalt {
      case Cause.End => Process.eval_(Task {
        Files.move(path, target, StandardCopyOption.REPLACE_EXISTING)
      })
  
      case cause => Process.eval_(Task { Files.delete(path) }) causedBy cause
    }
  }
}
```

This doesn't work though, because the sink never receives anything except `Kill`!  So the `move` is never invoked.  In fact, it is not at all possible with the current implementation of `tee` to implement this sort of pattern using a `Sink`!  Given how common this sort of "recover/commit" logic is, it seems like a significant limitation.

I would propose that we move ahead with ways of enriching the `EarlyCause` algebra to allow this sort of signaling.  Given the need for arbitrary chaining, I think it would actually make the most sense to redefine `Kill` as `Kill(Option[EarlyCause])`, rather than just `Kill(Option[Error])`.  Either way though, we need to be able to separate normal from abnormal termination in these cases.

**Comment by djspiewak** [comment]
Just to make sure that things are linked nicely, there's been a *lot* of discussion on this issue (including our current working proposal) on #314.

**Comment by pchiusano** [comment]
Closing this. Not relevant with new design.
