### ISSUE TITLE
port number used on tcp.server

### ISSUE THREAD

**Issue by julien-truffaut** [functional-streams-for-scala/fs2#292]
tcp.server binds to a `InetSocketAddress`. However, it is possible to use a ```port = 0``` to let the system pick up an available port and in that case, there is currently no way to obtain which port has been selected.

Would it be possible to make tcp.server return the port it is using?

**Comment by pchiusano** [comment]
Yes, I think this should be possible. I would add a method to `tcp.Socket` here: https://github.com/scalaz/scalaz-stream/blob/master/src/main/scala/scalaz/stream/tcp.scala#L46 and then follow the same pattern as `localAddress`. PRs welcome!

**Comment by pchiusano** [comment]
@pchlupacek can you add support for this to your work on #529, if you haven't already?

I don't think we will backport this to 0.8 though, sorry.
