### ISSUE TITLE
I'm pretty sure tcp doesn't work at all

### ISSUE THREAD

**Issue by djspiewak** [functional-streams-for-scala/fs2#329]
There are a ton of issues with the API and implementation and also tests.  It's very unclear to me *if* it's working at all, and if so, then *how*.  I'm relatively certain that, at the very least, the resource management is not guaranteed, since interrupts during asynchronous evaluation can result in leaks and/or spurious errors (even with the old `runAsync`).  In no particular order of importance…

## `tcp.server` signature is deceptive

The simplified signature of this function is as follows:

```scala
def server[A](bind: InetSocketAddress, concurrentRequests: Int)(handler: Process[Connection,A]): Process[Task, Process[Task, Throwable \/ A]]
```

So this sort of promises the same thing as the old NIO API, which is that the outer process manages the server instance and the inner processes represent clients that have been handled.  This makes a lot of sense, *however* the `concurrentRequests` parameter is in conflict with all of this!  The only way that this signature would make sense in the presence of this parameter and what it implies is if the return type were a flattened `Process[Task, Throwable \/ A]`.  We can see quite clearly *why* this is the case if we dig into the implementation:

```scala
setup map { sch =>
      nondeterminism.njoin(concurrentRequests, maxQueued) {
        Process.repeatEval(accept(sch)).map(processRequest)
      }.onComplete(Process.eval_(Task.delay { sch.close }))
    }
```

The `setup` value has the following type: `Process[Task, AsynchronousServerSocketChannel]`.  So ok, that's the *outer* process.  The inner processes are derived from an an infinite process of ongoing accepts, mapped into `processRequest` (which produces a process).  However, notice what we're doing with that infinite stream of accepts: we're *flattening* it with `njoin`!

In other words, going back to the original type signature, our outer `Process` of `Process` does not contain an inner `Process` for every single client connection, but rather it contains a *single* `Process` which carries the output of *all accepted connections* in a completely random order.  The inner process has no particular resource management associated with it, and thus its unflattened existence is entirely spurious.

Put another way, this implementation is doing the equivalent of creating a `Process[Task, Throwable \/ A]` and then running it through `Process.emit` as the last step of the function, just to satisfy a type signature.  This in turn leads to users doing very strange things on the other end.  More on this in a bit…

## Resources are improperly acquired

It is very important for reasons of `runAsync` that resources are grabbed via the `Process.await` function, called on an atomic `Task` (i.e. all resources are grabbed within a single `delay` or `async` block, not a bound chain), and then those resources are released using an `onComplete` defined on the process resulting from the body of the `await`.  Without following this template, `runAsync` does not make any strong guarantees about the finalizer soundness, and resources can leak and/or get released multiple times (the former will happen with the new `runAsync` implementation(s), while the latter will happen with the old `runAsync`).

However, if you look in the implementation of `tcp.server`, we're blithely "managing" our resources with the `map` function!  (non-concurrent case shown)

```scala
      setup map { sch =>
        Process.repeatEval(accept(sch)).flatMap(processRequest)
               .onComplete (Process.eval_(Task.delay { sch.close }))
      }
```

`setup` needs to be restructured to use `await`.  Its current implementation is simply unsound.

## `tcp.client` grabs resources non-atomically

This relates to the first paragraph of the previous section, but see the following implementation excerpt:

```scala
    Process.await(setup flatMap connect) { ch =>
      val chan = asynchronous(ch)
      bindTo(chan, S)(output).onComplete(Process.eval_(chan.close))
    }
```

This is sort of *half*-right, but the problem is that `setup` acquires resources which are then used in `connect` and ultimately freed (indirectly) by the `onComplete` in the body.  The resources acquired by `setup` can and will leak in the event of an interrupt.  As far as I can tell, these tasks are only separated for code organization reasons.

## `TcpSpec` is a hot mess

I don't even know where to start here…

First off, there's a ton of "compile this process and run its task, then run this other process that depends on the first thing, and *really* hope that everything is initialized in time!"  That happens in all three tests.  Second, it appears that the `tcp.chat` test is abusing multiple properties to get around the fact that ScalaCheck does not offer `before`/`after` functionality.  See the `setup` and `teardown` "properties" below:

```scala
    property("setup") = forAll ((i: Int) => { startServer; true })
    property("go") =
      if (System.getProperty("os.name").contains("Mac")) true
      else forAll { (msgs: List[List[String]]) =>
        val clients = msgs.map { msgs =>
          tcp.connect(addr) {
            tcp.lastWrites_(Process.emitAll(msgs).pipe(text.utf8Encode)).merge {
              tcp.reads(1024).take(1).pipe(text.utf8Decode)
            }
          }
        }
        nondeterminism.njoin(10, 10)(Process.emitAll(clients))(S2).run.run
        true
      }
    property("teardown") = forAll ((i: Int) => { stopServer; true })
```

The *really* mind-blowing thing about the above is when you take the `setup` property together with the following gem:

```scala
    lazy val startServer =
      link.discrete.wye(server)(wye.interrupt)
          .run
          .runAsync { _.fold(e => throw e, identity) }
```

Wait…what?

So `startServer` is a *lazy val* that is only going to get initialized once anyway, but we're running it inside of a `forAll { i: Int => ... }` property for some reason?  I really don't get that.  The worrying thing is that the spec doesn't appear to work without this!  So unless ScalaCheck is performing some really bizarre reinitialization voodoo…  Actually that's truly the only way I can think of that this would function in any sense of the word.

`stopServer` is similarly fun, since it just flips a `Signal` that is *itself* a lazy val:

```scala
    lazy val stopServer = { println("shutting down"); E.shutdown(); link.set(true).run }
```

## Summary

Honestly, I have no idea how any of this holds together or *what* it is even testing.  Maybe it works, maybe it doesn't, I can't tell and no one else seems to know either.  My best guess is that `tcp.client` is correct, `tcp.server` is just *phenomenally* unsound and deceptive in its types, and `TcpSpec` is not testing anything meaningful at all.  I think we *can* address all of this, but probably not without changing method signatures, rewriting specs and otherwise fixing a whole bunch of stuff.

**Comment by pchlupacek** [comment]
I think tcp.* needs a closer look. At least we need to know more info like address of other party etc. I am pretty fine with types, but I agree they little bit jump from the way how we use other stuff in task. 

However I would hold to get runAsync stuff before we will know the right answer to your observation, as we may have deeper issue here.

**Comment by djspiewak** [comment]
> However I would hold to get runAsync stuff before we will know the right answer to your observation, as we may have deeper issue here.

You mean a deeper issue with `runAsync` itself?  I considered that.  In fact, that was my primary suspect all along.  I just kept running into things in `tcp` that were manifestly broken.  I actually have a patch stuck in my local stash which completely fixes the chat example, partially by rewriting the test and partially by rewriting `tcp.server`.  The other examples don't work in that patch though, and I had to change so many things both semantically and in the signatures that it was almost like I was removing the old `tcp` and introducing a new module, also coincidentally named `tcp`.

It never, *ever* boiled down to anything I could see going wrong in the asynchronous stepping.  That's not surprising though, since the nondeterminism in `tcp` is relatively straightforward, and all of the use-cases are tested either in `WyeSpec` or `MergeNSpec`.

**Comment by pchlupacek** [comment]
@djspiewak tcp is paul's code, I think we really need to agree here that we can go forward with him. @pchiusano can you just quickly take look on this?

**Comment by pchlupacek** [comment]
@djspiewak thanks so much for all the work. I think if we won't hear from Paul by Sunday, lets make release. Not sure tho if he don't have to publish it anyhow. We can fix stuff in 7.1

**Comment by djspiewak** [comment]
> thanks so much for all the work. 

:-)  Partially selfish in motivation.  @alissapajer and I have been mud wrestling with tricky, non-deterministic scalaz-stream deadlocks and hangs for about six months now.  It's worth a lot to me to get them out of the way once and for all.

> I think if we won't hear from Paul by Sunday, lets make release. Not sure tho if he don't have to publish it anyhow.

Yeah, I would be really surprised if he *didn't* need to be the one to do the publishing.

> We can fix stuff in 7.1

Agreed.  I'm already thinking about a deep dive into `tcp`.  One of the "nice" things about having fruitlessly thrown a week at the functionality is that I now understand it pretty deeply, so I'm quite sure I could fix the bugs (and the signatures and the tests) and make things work correctly.  I just didn't want to do it under the gun of getting `runAsync` into a working state.

**Comment by pchiusano** [comment]
@djspiewak A couple comments

* `tcp.server` signature is as designed (we can debate the design, but it was intentional) -- when the outer process completes, the server is bound to the socket. It's not the same semantics as before, where the outer process demarcates individual connections. Idea was this can be used to avoid race conditions (in tests and user code), where client attempts to connect before the socket is bound. Flattening the stream out to just the results doesn't give you this. You can see how this is used in [the echo test](https://github.com/scalaz/scalaz-stream/blob/master/src/test/scala/scalaz/stream/TcpSpec.scala#L41) which doesn't have any weird hacks to shut down the server, it just `flatMap`s the server process.
* The chat tests are definitely a mess. I recall not being able to come up with anything useful / easy to test, given how much nondeterminism there is.

I'm not really happy with there being a distinction between `eval(acquire) flatMap { ... }` and `await(acquire) { ... }`. If people have to worry about that when writing code, then our resource finalization scheme is too fragile IMO. I think we need to come up with a more comprehensive, robust approach.

**Comment by djspiewak** [comment]
@pchiusano 

> tcp.server signature is as designed

The problem is that the results of the inner processes are sort of meaningless, since they're randomly ordered and interleaved.  The connection handler process results are basically just mashed together.  This is fine if the connection handlers are purely effectful, but if you *ever* want to be able to return results from your handlers, you need to have some sort of algebra which allows you to deinterlace the values on the other end.

The *internal* problem which stems from this type signature is that the concurrency within `tcp.server` is best described as "weird".  I'm not actually certain that I fully understand how it all fits together, and it's been a few weeks since I looked at it, but I remember there being some weird `emit` lifts just to satisfy the type signatures, which seemed extremely suspicious.

While I was desperately trying to get the `stepAsync` implementation working with `tcp.server`, I actually rewrote most of that code locally, restructuring both the resource management and the concurrency.  I was able to get things working for the most part, but some of the tests proved to be more involved, which was why I ultimately punted.

> I'm not really happy with there being a distinction between eval(acquire) flatMap { ... } and await(acquire) { ... }. If people have to worry about that when writing code, then our resource finalization scheme is too fragile IMO. I think we need to come up with a more comprehensive, robust approach.

I'm not happy about it either, but it is fundamentally unavoidable.  I made an argument to this effect in #333.  I can construct arbitrary variations on the `eval`/`flatMap` theme that can ultimately never be fully satisfied while preserving our desired append semantics.  The solution I propose in #333 is to remove `onComplete` (keep `onHalt`) and add a first-class finalizer mechanism to `Await`.  Decoupling finalizers from acquisition logic is fundamentally never going to work reliably, especially not when the finalizers are hidden within lazily-constructed append chains.

**Comment by pchiusano** [comment]
Well, the results are randomly interleaved, but they can still be useful
for logging, say.

You are right that there needs to be a new primitive which associates a
finalizer with resource acquisition. Let's discuss further.

**Comment by pchlupacek** [comment]
@djspiewak @pchiusano I think before resolving tcp, we really need to resolve append associativity(#333) and resource cleanup that must be very robust. If we have to alter algebra, I am fine with that, but I think this is something which shall be top priority for now, even thinking to release it as 0.7.1 if we will find quick fix to that. After that let's look on tcp?

**Comment by pchlupacek** [comment]
@djspiewak not sure completely if thats relevant, but I am integrating 0.7 with our server, and at the same time removing specs2 in favor of scalacheck. It almost killed me that scalacheck tests suffers from https://issues.scala-lang.org/browse/SI-7646. I know that I have been hitting this several times when testing the concurrent primitives in scalaz-stream. Was wondering, perhaps, if that can't be somewhere in the root of tcp issue as well. 

I opened this https://github.com/rickynils/scalacheck/issues/155 in Scalacheck with temporary workaround that resolves the issue (at leas in our highly-concurrent tests). 

Not sure if that helps, but perhaps...

**Comment by djspiewak** [comment]
@pchlupacek I bear the scars of the Cake Pattern on my soul.  Object init deadlocks are basically the first thing I think of when I see threads being stuck.  I'm very, very certain that the tcp issues are separate.

**Comment by pchlupacek** [comment]
:-) ok just was checking

**Comment by jilen** [comment]
http://stackoverflow.com/questions/29518523/scalaz-stream-tcp-infinite-echo-client-only-send-first-message  I have wrote an simple tcp echo app but client not work, and I have no idea how point out what's going wrong

**Comment by pchiusano** [comment]
Closing. See #529 for tracking new implementation.
