### ISSUE TITLE
Create benchmarks

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#399]
We have to find a way how to reliably prove the performance after various changes stay in expected limit, or better improves. So far we have limited tests with so-so reliability. If anyone has experience / ideas and want to step in, please comment below.

**Comment by wookietreiber** [comment]
I just created a PR to show you how this might look like using [ScalaMeter](http://scalameter.github.io/).

**Comment by pchiusano** [comment]
I am looking for volunteers to take this on. There is already a benchmark project, I would just use the [sbt-jmh](https://github.com/ktoso/sbt-jmh) (or some other reputable JVM benchmarking tool) plugin to write some benchmarks there. If they can be run as part of Travis, even better.

Regression testing for performance is a separate issue, let's get some benchmarks written first.

I wrote some performance 'tests' in [`StreamPerformanceSpec`](https://github.com/functional-streams-for-scala/fs2/blob/topic/redesign/core/src/test/scala/fs2/StreamPerformanceSpec.scala). These might be a good starting point for some benchmarks.

**Comment by mpilquist** [comment]
Fixed in #646
