### ISSUE TITLE
Release snapshot versions

### ISSUE THREAD

**Issue by jedesah** [functional-streams-for-scala/fs2#405]
`scalaz-stream` is becoming relatively stable and when making a contribution back to the project, often times we would like to have access to the fix or improvement as soon as possible.

It's not reasonable to release minor versions every time there is a new function that was added or a minor bug fix, but it would be nice for those that know exactly what they want, to grab a snapshot version.

`scalaz-stream` already publishes locally a version name corresponding to the commit hash, it would be nice if there was a public snapshot repository that did the same thing for everyone.

Maybe this already exists, if so it would be nice to document it on the README.

Does any other project do this? Am I crazy to think this would be useful? It is too hard to automate?

**Comment by djspiewak** [comment]
It wouldn't be difficult to push up a bintray release (versioned with the hash) any time master successfully builds.  There are other projects which do this.

**Comment by pchiusano** [comment]
I can do snapshots on an ad hoc basis, but looking for volunteers to figure out a way to do this in some more automated fashion, weekly or biweekly.

**Comment by mpilquist** [comment]
As of 0.9.0, snapshots are published to Sonatype on an ad hoc basis. We could automate via http://www.cakesolutions.net/teamblogs/publishing-artefacts-to-oss-sonatype-nexus-using-sbt-and-travis-ci but if so, I'd like to use a Sonatype account dedicated to snapshot publishing.

**Comment by mpilquist** [comment]
OK, topic/redesign branch publishes snapshots on successful Travis builds.
