### ISSUE TITLE
Remove warnings

### ISSUE THREAD

**Issue by jedesah** [functional-streams-for-scala/fs2#411]
There is a whole slew of warnings, mostly about unchecked types du to erasure (except for the one removed in #410). It would be nice to get ride of those warnings in order to make other warnings stand out for anyone working on the project.

Is there any reason why they are not removed? I don't mind removing them, but I want to make sure there is no reason for them to be there before doing the grunt work.

**Comment by pchlupacek** [comment]
@jedesah I think the reason was 2.10/2.11 compatibility.

**Comment by jedesah** [comment]
There is no @unchecked in 2.10?

**Comment by pchiusano** [comment]
There are no longer any warnings in the 0.9 work, and we are basically freezing any pre-0.9 series code with the possible exception of disastrous, horrible bugs, for which we might do another 0.8 point release.

**Comment by jedesah** [comment]
:+1:
