### ISSUE TITLE
Queue can overflow memory

### ISSUE THREAD

**Issue by djspiewak** [functional-streams-for-scala/fs2#412]
Not sure why I didn't realize this before:

```scala
queued = queued fast_++ as
```

This is the second line of `enqueueOne`.  It is *not* guarded by a conditional.  In other words, when the queue is full, we delay the acknowledgement to the enqueuing process, but we don't delay the enqueue itself!  This means that it's possible to crash a queue-using application through repeated enqueues that do not await acknowledgement.  That seems like a serious issue…

**Comment by pchlupacek** [comment]
hm, you are talking about the application that just throws the tasks on the queue and never waits for task's completion? Not sure how we can in queue avoid that. In general if the program is not using flow control by awaiting task completion, I think that program needs to be perhaps fixed?

**Comment by djspiewak** [comment]
@pchlupacek That is indeed the case that I'm thinking about, and you're right, I'm not sure how much we can do.  I toyed with a couple of different ideas, but ultimately the data is still in memory.  At the end of the day, I can think of only two possibilities to address this issue (other than correcting the enqueuing sources to respect flow control and *not* spin up an indefinite number of enqueuers):

- Implement a method `enqueueLater(item: Task[A]): Task[Unit]`.  This would behave just like `enqueueOne`, except the `item` effect would not be run until the queue could guarantee space for the data.  The tradeoff here is that ordering would need to be slightly relaxed under certain circumstances (`enqueueOne` and its ordering guarantees would be unaffected).
- Implement a configuration for `boundedQueue` which `fail`s the resulting effect from `enqueueOne` if the queue is full.  This is probably a preferable option, since emulating this behavior (which is sometimes desirable!) is actually somewhat hard to do correctly if you're an API consumer.

Alternatively, we can just punt and WONTFIX this issue.  My preference would be to implement the second item, since it would just be a configuration and users could ignore it if desired.

**Comment by pchlupacek** [comment]
@djspiewak I like option 1). I wouldn't care about order that much hence in that code, you really throwing the data to the queue unordered w/o guarantee anyhow, so this is just a little helper for people to not kill the Ram. I think it is in fact useful for perhaps web servers where you really cannot guarantee how the requests are coming in unless the caller will take care...

Just a small detail perhaps. Maybe just define enqueueLater as `suspendEnqueue(item:  => Seq[A]): Task[Unit]` shall be enough?

So I think this is instead a bug a feature enhancement :-)

**Comment by djspiewak** [comment]
@pchlupacek I agree that this is a RFE rather than a Bug.  I'll retag…

In any case, let's consider this issue as defining `enqueueLater`.  I would prefer to use `Task` rather than a bare thunk, though `Task[Seq[A]]` is certainly a preferable signature to the one I proposed.  The reason for `Task` rather than the thunk is I was envisioning people dumping excess data to scratch space (e.g. on disk).  Under that strategy, the effect given to `enqueueLater` (or `suspendEnqueue`) would be the effect that reloads the data back into memory.  A thunk can of course do this, but not without side-effects.

**Comment by pchlupacek** [comment]
@djspiewak ok, agreed. next on todo list :-)

**Comment by pchlupacek** [comment]
@djspiewak I also reread your suggestion, and perhaps you right the second option where the items fails is more likely desired. In fact, not sure if it isn't confusing both solutions seems to me fair and may have their use case, tho the failure one seems to me more accurate, plus users can laters decide to recover and re-enqueue if needed...

**Comment by ceedubs** [comment]
I was surprised the first time I called `enqueueOne` and realized the `Task` was blocking instead of immediately failing. +1 for a way to get immediate failure. I've wanted this so a service could immediately return a 503, and I couldn't figure out an elegant way to do it.

**Comment by pchlupacek** [comment]
@ceedubs use `async.boundedQueue` and check size of queue before submtting the task. Agree this is not super elegant, but fix is on the list. If you interested, feel free to submit PR with fix as suggested above. 
Thanks!

**Comment by pchiusano** [comment]
I think this is all addressed with new design. There's also now an `offer1` function on `Queue` which will noop and return false immediately if the queue is currently full. And the implementation of blocking queue's `enqueue1` decrements the semaphore before doing anything.

Reopen if I'm missing something here. :)
