### ISSUE TITLE
Write tests to ensure queue size signal produces output without needing a dequeue first

### ISSUE THREAD

**Issue by alissapajer** [functional-streams-for-scala/fs2#433]
Hi folks, before I go fix this I wanted confirm that others also don't expect this behavior:

``` scala
  property("size-signal-no-dequeue") = protect {
    val q = async.unboundedQueue[Int]
    val l = List(2,4,6,8)

    val t1 = Task { l.foreach(i => q.enqueueOne(i).run) }
    //val t2 = q.dequeue.runLog
    val t3 = q.size.discrete.runLog

    val sizes = new SyncVar[Throwable \/ IndexedSeq[Int]]
    t3.runAsync(sizes.put)

    Thread.sleep(100) // delay to give chance for the `size` signal to register

    t1.run

    //val values = new SyncVar[Throwable \/ IndexedSeq[Int]]
    //t2.runAsync(values.put)

    Thread.sleep(100) // delay to give chance for the `size` signal to collect all values

    q.close.run

    val expectedSizes = Vector(0,1,2,3,4)
    //(values.get(3000) == Some(\/-(l.toVector))) :| s"all values collected ${values.get(0)}" &&
      (sizes.get(3000) == Some(\/-(expectedSizes.toVector))) :| s"all sizes collected ${sizes.get(0)} expected ${expectedSizes}"
  }

```

I grabbed this from our "size-signal" spec in `QueueSpec` and commented out the lines relevant to dequeueing.

As we enqueue 4 items, I'd expect to see the `size` signal `runLog` to  `Vector(0,1,2,3,4)`, but we don't get any results. The test fails with:

``` scala
[info] all sizes collected None expected Vector(0, 1, 2, 3, 4)
```

**Comment by alissapajer** [comment]
Another example that shows this is in this [gist](https://gist.github.com/alissapajer/4ed2d8b10b14af63f3fb). If you remove the `q.dequeue.drain` no queue size will be returned.

**Comment by pchiusano** [comment]
I believe this is fixed in new implementation, however we don't have any tests for it. @alissapajer you are most welcome to add some tests for this to `QueueSpec`.

I'll leave this open and change the title accordingly.

**Comment by alissapajer** [comment]
@pchiusano a couple questions I ran into while writing queue tests:

(1) `Queue#close: Task[Unit]` does not exist any more - what is the new canonical way to close a queue, if there is one?

(2) When a `wye.mergeHaltL` is required, what is the new canonical way to perform that?

Thanks!

**Comment by pchiusano** [comment]
@alissapajer you can base your tests off [this branch](https://github.com/functional-streams-for-scala/fs2/blob/topic/redesign-channel/core/src/main/scala/fs2/Wye.scala) which has `mergeHaltL/R`.

There's no close operation on queues, but you can use a `Queue[Option[A]]`, then `process1.unNoneTerminate` when reading a stream from the queue. You can also use a separate `Signal[F,Boolean]` which is set to false when you want to stop listening to the queue. (It could make sense to implement `CloseableQueue` as a decorator of a `Queue` using one of these approaches.)

**Comment by mpilquist** [comment]
Hi @alissapajer -- any update on this issue? We are getting close to a 0.9.0-RC1 build and I'm checking status on all of the open issues targeted to 0.9.0.
