### ISSUE TITLE
NIO exception when using nio.file for large files

### ISSUE THREAD

**Issue by clayrat** [functional-streams-for-scala/fs2#435]
When copying a ~6Gb file using `scalaz.stream.nio.file.chunkW` I get a following exception:

```
java.lang.IllegalArgumentException: Negative position 
    at sun.nio.ch.SimpleAsynchronousFileChannelImpl.implWrite(SimpleAsynchronousFileChannelImpl.java:350)
    at sun.nio.ch.AsynchronousFileChannelImpl.write(AsynchronousFileChannelImpl.java:251)
...
at scalaz.stream.nio.file$$anonfun$chunkWriteBuffer$2$$anonfun$apply$7$$anonfun$apply$8.scalaz$stream$nio$file$$anonfun$$anonfun$$anonfun$$go$1(file.scala:202)
```

My guess is that the culprit is `var pos = 0` in `chunkWriteBuffer` (https://github.com/scalaz/scalaz-stream/blob/master/src/main/scala/scalaz/stream/nio/file.scala#L196) which is inferenced to be an Int. Is it sensible to change that one (and similar code in `chunkReadBuffer`) to Long?

**Comment by fthomas** [comment]
`pos` is only passed to [`AsynchronousFileChannel#write`](http://docs.oracle.com/javase/7/docs/api/java/nio/channels/AsynchronousFileChannel.html#write%28java.nio.ByteBuffer,%20long,%20A,%20java.nio.channels.CompletionHandler%29) which takes a `long`, so it seems reasonable to me to change its type to `Long`.

**Comment by clayrat** [comment]
Ok, so which branch to PR against?

**Comment by fthomas** [comment]
I don't know if another 0.7 release is planned, so `master` should be fine.

Can you confirm that the change fixes the bug?

**Comment by pchlupacek** [comment]
@clayrat master is just ok. Will be part of 0.8

**Comment by pchiusano** [comment]
Linking in #538, make sure we address this also

**Comment by mpilquist** [comment]
I just confirmed (by inspection) that this is not an issue in 0.9.
