### ISSUE TITLE
Meta-issue for tracking 0.9 release

### ISSUE THREAD

**Issue by pchiusano** [functional-streams-for-scala/fs2#437]
Hi everyone. This is a meta-issue to organize work on getting a 0.9 release out. There is a ton of work to do and I feel kind of overwhelmed by it. This has to be a team effort or it is never going to get done.

We can split off sub-issues as needed. Use the [0.9.0 Milestone](https://github.com/scalaz/scalaz-stream/milestones/0.9.0). Don't be shy about adding new issues that you think of. You can link to them from here.

I'll get this started - 

Points of discussion:

* Anyone have objections to this being a 2.11+ only project from now on? The code does not compile with 2.10 due to differences in the typechecker. If you'd really like to make it work, check out the `topic/0.8-redesign` branch and see if you can get it to work with both 2.10.x and 2.11.x. Otherwise, let's just let 2.10 support lapse.
* Project organization - I've been going back and forth or whether to split the project into different submodules (within this repo) or separate repositories. After futzing with various ideas, here's what I'm thinking. We have _two separate repositories_, `fs2/stable` (the package `fs2`) and `fs2/unstable` (the package `fs2.unstable`, with a module structure that mirrors `fs2`), each with their own release cycles, with existing modules split between the two repos based on whether they are experimental or not (proposed split is below).
  * Idea is that after the 1.0 release (next release after 0.9), `stable` would do releases much less frequently, and would be mostly bugfixes, performance improvements, or promoting "completed" modules or definitions from `unstable`. Backwards compatibility would be a high priority here. 
  * `unstable` would have its own more frequent releases and could change APIs from one release to the next, with no real attempt at backwards compatibility (an important thing to document to users). It's a sandbox for things that are experimental, etc. Of course, people can also just write unofficial libraries that depend directly on `stable`, and if they want these to be officially 'blessed', they could potentially be promoted into `stable`. Right now, the various modules and functions of the library are of varying levels of stability and/or quality, and users aren't really clear on what's what. 
  * Here's a proposed split: `stable` gets everything in the new `fs2` package, plus all the generic combinators like what's in `process1`, `tee`, and `wye`. Also some stable, domain-specific modules like `text`, `time`, and `hash`, and the new `task` module (see below).
  * `async`, `io`, `nio`, `tcp`, `udp`, and anything I/O-related gets moved to `unstable`. Many of these functions are no longer as necessary or useful, or their design should just be revisited in light of the capabilities of the new design. In particular, with first-class handles, I think a lot of the I/O functions could use a redesign.

Let me know what you think about this split. Related to this: if we go this route, should we just introduce new repositories under the [FS2 org](https://github.com/functional-streams-for-scala) for both `stable` and `unstable`? Or we could try to sort of preserve history (though no matter what we do there is going to be a large, rather discontinuous commit at some point) and eventually use this repo for `stable` and migrate it to the FS2 org.

Incomplete list of todos (now):

* Introduce a new module, `task`, with [these functions for inverting control](https://gist.github.com/pchiusano/cf6e6f1b1271c113d1a1), subject to design review, tweaks, and bikeshedding over good names. Along with the new algebra, which has good support for mid-pipeline concurrency, these proposed functions I think eliminate many (most?) uses of the `async` package. You no longer need to use a `Queue` for instance, if you just want different stages of a pipeline to run concurrently.
* Port all transducers #438
* Port stuff in `io`, `async`, `nio`, etc, over to `fs2` package.
* Much more testing of new design.
  * Especially for `process1`, `tee`, `wye`, `time`, `hash`, `text`, I'd probably just port over the old tests. 
  * Most of the resource safety and concurrency tests (not including `async`) will probably need a rewrite.

Todo (later):

* Cleanup and backwards compat pass. I'd like to maintain source compatibility (possibly with deprecations) when it is reasonable or easy to do so. Simple example - add a deprecated `type Process[+F[_],+A] = Stream[F,A]` declaration to the `fs2` package object. 
* More documentation, possibly runnable documentation (using [tut](https://github.com/tpolecat/tut) or something similar)
* More implementation notes and comments. I will work on this.
* When new repo structure is settled, it would be nice to set up auto build of documentation and API docs to the website, fs2.co
* Release notes and migration guide
* Publish to sonatype, and to fs2.co
* What else?

**Comment by pchlupacek** [comment]
Generally ok with plan. Only perhaps some async stuff may need to be necessary in stable too, not sure of we won't need that to implement task, wye, merge etc... Thinking at least of Signal there.

**Comment by pchlupacek** [comment]
Also we perhaps need a bit of coordinated split of work between people, perhaps someone coordinating that effort.

**Comment by pchiusano** [comment]
I can help coordinate things. For simplicity, I'm going to suggest that we just continue working in a single repository (this one), even if we ultimately split things up later. It's easy enough to move things around later. What I'd like to focus on right now is:

* Getting all the functionality ported over
* Testing

I'm going to create sub-issues associated with this milestone and we can divide up the work.

**Comment by pchiusano** [comment]
FYI, I deleted the 0.8-redesign branch and created [topic/redesign](https://github.com/scalaz/scalaz-stream/tree/topic/redesign) instead. Doing a bit of cleanup on that branch at the moment.

**Comment by pchlupacek** [comment]
@pchiusano just a small idea. If we would have the stable/unstable design, won't it be practical to also think that some sort of `core` functionality has not dependencies at all? Perhaps move all ByteVector stuff to fs2.io._ module? I don't think so it adds complexity and may be beneficial for some people to have dependency free version of the fs2?

As regards the developement of fs2, I can perhaps take some concurrency primitives (unstable) and/or some network (nio/tcp/udp) to work on if required. LMK which part you would like me to take. I think work on these can start after join/wye will be implemented. So if you think is appropriate to hop on on any of these (wye/njoin) with perhaps testing LMK.

**Comment by mpilquist** [comment]
Looks like everything listed in this issue has been addressed so I'm going to close this.
