### ISSUE TITLE
Port all transducers to new design

### ISSUE THREAD

**Issue by pchiusano** [functional-streams-for-scala/fs2#438]
Port all functions in `process1`, `tee`, `wye`, `text`, `time`, `hash`. Here's my proposed convention:

  * The `Process1` / `Tee` / `Wye` instances go in the `process1/tee/wye/text/etc` module directly.
  * Totally generic pull operations go in `trait pull1` or `trait pull2` (depending on whether they take one or two `Handle`s) which are currently mixed into the `fs2.Pull` companion object, though not sure that is a good idea. A good example is `awaitLimit`. You might use it when building up a `Tee`, `Process1`, or just building up a `Pull` directly.
  * For any non-generic `Pull`-based function that's useful, it can be exposed in the object `process1.pull` (or `text.pull`, `time.pull`, etc). A good example might be `time.sleep`, which you might want to insert in the middle of building up a `Pull`. This would be accessible via `time.pull.sleep`.

Also add tests for these. Many of the old tests can probably be ported or copied over directly.

**Comment by pchiusano** [comment]
@fthomas would you be willing to kick this off by going through `process1` from `master` and porting everything over? You can follow [the basic structure here](https://github.com/scalaz/scalaz-stream/blob/topic/redesign/src/main/scala/fs2/Process1.scala#L7). Since you've written many of the transducers in the library and I think this will go pretty quick once you get used to the new API. I also think it'll be pretty interesting (I only ported a couple functions so far, but I was already learning things about the new style).

Assuming you are willing: 

* We can do a kickoff meeting and maybe pair program the first few if you want. Up to you. Just mention me on gitter.
* If it's ugly or difficult to express something, or just plain not possible, that could be a problem (maybe the core algebra needs tweaking), or just a sign we need to introduce new helper functions. Let us know what you discover!
* Try to preserve chunkiness of the inputs when possible. As in, use `await` to obtain a full chunk, rather than `await1`. If this results in you reading too much from a `Handle`, you can always `push` back any leftovers (this is what is done by `take`, for instance).
* I am very curious to know any qualitative impressions you have about the new style of building up transducers.

After we have `process1` done, I'm guessing we'll have a much better sense of how to express things, and maybe we can divide up doing the other modules.

@fthomas let me know what you think.

Anyone else have thoughts or ideas?

**Comment by fthomas** [comment]
I can try this. I'll start with tests for those transducers that are already there and will submit PRs for things that are ready to be merged. This way others can learn with me as I go along.

That said, I don't want that the `process1` port is blocked by me. If someone else is interested in working on the transducers, feel free submit PRs too.

**Comment by pchiusano** [comment]
@fthomas that sounds great. Looking forward to seeing how it goes!

**Comment by mpilquist** [comment]
With the merge of #615, all transducers have been ported or otherwise excluded from the port due to missing abstractions (e.g., Monoid, Eq) or non-applicability to the redesign.
