### ISSUE TITLE
Implement simple inversion of control functions in `task.scala`

### ISSUE THREAD

**Issue by pchiusano** [functional-streams-for-scala/fs2#439]
I want FS2 to have some simple functions for converting between a 'multi-use' imperative callback API and the stream world, without having to use the types in the `async` package. I've stubbed out some tentative signatures in [`task.scala`](https://github.com/scalaz/scalaz-stream/blob/topic/redesign/src/main/scala/fs2/task.scala), based on some discussion with @djspiewak. 

This API is by no means set in stone, but I do want to have two functions like the `queue` and `signal` functions in `task.scala`, even if the signatures need tweaking. If anyone has further ideas about this API, please raise them here. Otherwise I think someone should just dive into trying to implement, and we'll see what shakes out.

Whoever takes this on may need to possibly fiddle with the API to make it implementable. I think both functions can be implemented with an actor (use `fs2.internal.Actor`), but see my [note about strictly returning an Ack](https://github.com/scalaz/scalaz-stream/blob/topic/redesign/src/main/scala/fs2/task.scala#L24).

Once you have something working (with some tests), report back and we'll go from there.

@djspiewak can you take the lead on this or delegate it, as I think you had more ideas on how it should work. But @pchlupacek and others please weigh in if you have thoughts, objections, or concerns.

**Comment by pchiusano** [comment]
@djspiewak there is no hurry, but do you have a sense of when you might be able to take a look at this? :)

**Comment by pchiusano** [comment]
Just linking to @pchlupacek's comment regarding `Task`. https://github.com/scalaz/scalaz-stream/issues/447#issuecomment-149652429 

* The 'interruptible' functions are already removed from `Task` in FS2. `Future` is private to FS2 so let's just ignore it. (I just noticed I didn't bother deleting the interruption functions, but regardless, they can be deleted and aren't used anywhere.)
* I'm not in favor of removing `Task.async`. It's a useful function and it makes the FS2 `Task` more of a drop-in replacement for the scalaz one.
* I like the idea of generalizing these combinators, however...
* I don't like the idea of renaming `task` to `async`. If we generalize them to work for not just `Task`, I'd probably just mix these into the `Stream` object directly.

My suggestion is that @djspiewak proceed with implementing these functions, just for `task`. Once he has a working implementation, we can discuss generalizing it and/or moving the functions to a different module. With actual concrete implementations, I think it will be obvious what we'd need if we wanted to generalize them.

**Comment by pchlupacek** [comment]
@pchiusano I still believe that make the Task.async private is right think to do and instead just have `task.async(cb => ???):Stream[Task,A]`, I believe this will be ok for any patterns that are used in scalaz stream and will resolve the pre-emption issue for once.

**Comment by dk14** [comment]
Maybe you could add this for async piping:

     type S[T] = Stream[Task,T] 
     def pipeAsync[O](register: (S[Input] => S[Ack]) => Unit): Task[S[O]]

or even that:

    case class Accept[W](w: W, unprocessedSize: Int) extends Ack[W]
    def pipeAsync[O](s: S[Input]): Task[S[Ack]] 

All unaccepted `Ack`s are going to be processed synchronously inside parent process. This one is a bit harder to implement and might be a questionable (but very convenient) approach - I believe it could be converted into something more straightforward.

It would be also great having a way to quickly implement `perConcurrentId` pattern, like in `JMSXGroupID`. It asynchronously splits one queue (or `Stream`) into several ones using some predicates, like:

    def broadcast[O](register: ..., cojoin: S[Input] => S[S[Input]]): Task[S[S[O]]]

It should replace topics, though. `unprocessedSize` would have an aggregated size then (nice for back-pressure). 

P.S. You will also have to close empty sub-queues automatically, actually I have to do that manually now and guys who did same for Akka had to do that as well - so it's like a killer-feature for my project :).

**Comment by mpilquist** [comment]
I think this issue has been overcome by events. @pchlupacek do you agree?

**Comment by pchiusano** [comment]
Agree.

**Comment by pchlupacek** [comment]
ok
