### ISSUE TITLE
Process.onKill should not swallow Kill

### ISSUE THREAD

**Issue by djspiewak** [functional-streams-for-scala/fs2#448]
Currently, `onKill` fails to mirror `onComplete`, which propagates the initial `cause` out of the finalizer.  Instead, `onKill` outright swallows the `Kill`.  This is highly undesirable, since it *defaults* to a semantic where the finalizer can override the interrupt for anything downstream of the `onKill`.  Due to the way that `Kill` is used, this can result in (among many other terrible things) unexpected non-termination and non-composability.

The solution is just to tack on a `causedBy Kill` to the implementation.

**Comment by pchlupacek** [comment]
@djspiewak I agree. Perhaps we have to also mirror the onComplete`s behaviour and add `asFinalizer` to onKill too.

**Comment by pchiusano** [comment]
I'm a little nervous about changing this one in a point release, even
though you are probably right.

**Comment by pchlupacek** [comment]
@pchiusano I think this is ok. Is really more like bug than anything else. Like @djspiewak points it only leads to unexpected behaviour with non-terminating processes.

**Comment by djspiewak** [comment]
@pchiusano If anyone is using it currently, they're either manually repropagating the signal, or their code has hidden bugs.  If you want to swallow a `Kill`, it *needs* to be via `onHalt`, and we've made that clear in the past.  So I think it's fair to classify this as a bug, and the change would not be a meaningful regression.

**Comment by pchiusano** [comment]
@djspiewak you've convinced me. :) I have no objections to this change.

**Comment by pchiusano** [comment]
Closing this. Not relevant for 0.9+.
