### ISSUE TITLE
`awaitAsync` not asynchronous enough

### ISSUE THREAD

**Issue by pchiusano** [functional-streams-for-scala/fs2#477]
I noticed this while testing `process1.prefetch`. Only the leftmost stream operation is done asynchronously, whereas you really want all operations to be done asynchronously until a chunk can be produced.

Here's an example:

```Scala
val s = Stream(1).flatMap(i => Stream.eval(Task.delay(Thread.sleep(1000))))
s pull { h => h.awaitAsync }
```

Currently, that will just step the `Stream(1)` asynchronously (somewhat pointlessly, since it's strict), returning a Future that will force the sleep `Task` _synchronously_.

You don't just want the leftmost stream to be stepped asynchronously, because after that finishes, we still haven't produced a chunk. So we should continue doing things asynchronously, up to the `Thread.sleep` which finally produces a chunk when it's done.

I don't have a solution to this yet, but it's obviously kind of a big deal.

**Comment by pchiusano** [comment]
I think I have a fix for this, it will involve some refactoring, there doesn't seem to be a purely local change that does the trick. 

My idea is to implement `awaitAsync` in terms of:

```Scala
def _awaitFree: (Free[F,Step[Chunk[A],Stream[F,A]]], List[Token])
```

`Token` replaces `Long` as the unique identifier for resources allocated by `bracket`. It will be something like `private[fs2] class Token`, just using object identity. Importantly, `_stepFree` can allocate a `Token` without having to ask the `runFold` interpreter.

With something like `_stepFree`, we can interpret that to an `F[Step[Chunk[A],Stream[F,A]]]]`. Then we use the functions of `Async` to run that `F` asynchronously. `Async` has a function:

```Scala
def set[A](r: Ref[A])(a: F[A]): F[Unit]
```

This starts running the `F[A]` asynchronously. At any time later, you can call `get` on the `Ref[A]` to block until it has been `set`.

Details still to be worked out.

**Comment by pchlupacek** [comment]
+1 on token. I would like to take that and use it in Signal // Queue // Topic. Perhaps token can be bound to `Async` ?

**Comment by pchiusano** [comment]
No it can't be specific to Async since bracket should not require an Async
constraint (you can allocate resources in sequential code). But it will be
private to fs2 and we will be careful not to use it in ways that would be
observable.

**Comment by pchiusano** [comment]
Spent a while on this today, started several different approaches that all didn't work. Think I've got an approach that will work, but feeling somewhat fried at the moment so I don't think I'll dive into testing it out until next week.
