### ISSUE TITLE
Reimplement `Task.gatherUnordered` (and related functions)

### ISSUE THREAD

**Issue by pchiusano** [functional-streams-for-scala/fs2#489]
`Task.gatherUnordered` was accidentally removed in FS2. It should be resurrected I think. However, it should not have the behavior of trying to interrupt or cancel running tasks if any of the tasks fails.

Also resurrect `gather` (define in terms of `gatherUnordered`).

**Comment by mpilquist** [comment]
`gatherUnordered` without cancellation is the same as `traverse(identity)`. As such, I'm going to close this.
