### ISSUE TITLE
unsafeChunkR can return too few bytes before the InputStream is empty

### ISSUE THREAD

**Issue by refried** [functional-streams-for-scala/fs2#498]
I think I've run into the fs2 version of this:
http://stackoverflow.com/questions/7874713/java-read-from-inputstream-doesnt-always-read-the-same-amount-of-data

I've got a method like this:
```
def loadBatch(is: InputStream): Process[Task, Labeled] =
  Process.constant(3073).toSource.through(io.chunkR(is))
    .map{v => println(v.length); Labeled(v.head, CifarUnlabeled(v.tail.toArray))}
```
and am observing that every 3rd read comes up short:
```
3073
3073
2590
3073
3073
2531
3073
3073
2167
3073
3073
2768
...
```

They don't add up to anything meaningful, like 10240, and in fact the "short" read length doesn't seem to repeat.

When I read the same file using a `java.io.FileInputStream`, I get consistent 3073-byte reads.  When I call `Thread.currentThread.getContextClassLoader.getResourceAsStream` which returns a `sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream`, I get the uneven chunks demonstrated above.

I'm not sure what the tidiest way to loop within `unsafeChunkR` to extract as much as possible from the `InputStream` before returning would be (e.g. multiple calls to `.read` and concatenating the results together until reaching EOF), but would be grateful for any suggestions.

**Comment by pchiusano** [comment]
Leaving this open as reminder for whenever we port file I/O stuff to new design.

**Comment by refried** [comment]
I totally thought this had been merged in time for 0.8x, doh.  (I was still on 0.7x at the time.)

Are you sure you don't want to do a micro release? :)

**Comment by pchiusano** [comment]
If you want, you can open a PR against series/0.8 and series/0.8a branches. I'm still not sure if we will do a point release, but if there is a critical mass of stuff to fix we probably should.

**Comment by refried** [comment]
*nod*  I opened #539, #540 just in case.

**Comment by refried** [comment]
Analogous issue for `nio`.

**Comment by mpilquist** [comment]
See comment on #559 re: support for this in 0.9 (ie., use `rechunkN`)
