### ISSUE TITLE
Support for Scalaz 7.2.0

### ISSUE THREAD

**Issue by zaneli** [functional-streams-for-scala/fs2#502]
Scalaz 7.2.0 released a few days ago.
https://github.com/scalaz/scalaz/wiki/7.2.0

Do you have any plans to supporting Scalaz bump version to 7.2.0?

**Comment by pchiusano** [comment]
I would say probably not. We are getting pretty close to an initial
release, which won't depend on scalaz.

**Comment by zaneli** [comment]
Oh, I see.
I'm looking forward to it being released. :)

By the way,
if someone corresponds to support Scalaz 7.2.0 and send pull request,
is there any possibility that you accept and merge it?

**Comment by pchlupacek** [comment]
I think that will require to make different binary i.e. 0.8.0b. To me such PR is ok if it addresses all that, whilst still keeping 0.8 against 7.1

**Comment by zaneli** [comment]
I understand that you won't deal with it proactively,
but I'd like it if possible...

I have tried #503 and I will retry as following the instructions.
https://github.com/functional-streams-for-scala/fs2/pull/503#issuecomment-163652489
https://github.com/functional-streams-for-scala/fs2/pull/503#issuecomment-163696826

Could you give me some advice on what I should do about that?

* Should I create `series/0.8b` branch off of `release/0.8` tag? (not `topic/scalaz-720` and so on?)
* Where should I submit the PR to? `functional-streams-for-scala:master`?

I guess that following corresponds preferred to me.

1. You (someone in owners of this repository) create `series/0.8` branch off of `release/0.8` tag.
2. I create `topic/scalaz-720` branch off of `series/0.8` branch, and fix it.
3. I submit the PR from `zaneli:scalaz-720` to `functional-streams-for-scala:series/0.8`.
4. If this PR is accepted and merged, you create `series/0.8b` and release it.

How do you think about it?

Sorry for my poor English. Thank you.

**Comment by zaneli** [comment]
My wish came true.
#532
