### ISSUE TITLE
Port retry combinator to FS2

### ISSUE THREAD

**Issue by pchiusano** [functional-streams-for-scala/fs2#508]
Thanks to @matthughes for prompting this, we should port [this combinator](https://gist.github.com/pchiusano/7894696) to FS2. It can just be a regular `Process1` - nothing in the implementation needs to know anything about `Task`. Should go in the `process1` object, with an alias in `Process1Ops`.

Some stuff we will need:

* implementation of `attempt` - `p.attempt = p.map(Right(_)).onError(e => emit(Left(e)))`

I'd keep the implementation of `dropWhileUnlessAtEnd` private, feels a little too specialized

**Comment by mpilquist** [comment]
@pchiusano I'd like to close this -- I'm not sure that the behavior here is common enough to be generally useful and even if so, I think there are lots of other retry patterns that we'd then want to consider. I could see this combinator being in the guide though, perhaps as an exercise?

**Comment by pchiusano** [comment]
Yeah, that's fine, can close. Maybe this would be nice as a worked example a la [the README example](https://github.com/functional-streams-for-scala/fs2/blob/series/0.9/docs/ReadmeExample.md). It could also be given as an exercise in the guide, along with a link to 'the answer'.
