### ISSUE TITLE
fs2.either won't alow disjunctive types

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#533]
Thanks to this implicit `RealSupertype[A,B]` on `Stream.either` A and B must be supertype related, which shouldn't be the case if output value is Either[A,B].

**Comment by pchiusano** [comment]
Just remove that constraint , it's a copy paste error, I probably copied the merge signature. If you look in Wye.scala you can see the constraint isn't there. You might need a RealSuperype[A,A2] like for append...

**Comment by pchlupacek** [comment]
@pchiusano yeah sorry was in middle of something so just wrote this as note to include it in any future PR...

**Comment by mpilquist** [comment]
Fixed in 75be3b5dd6037a853e6f25fcbaf9b8ef76aea38c.
