### ISSUE TITLE
Test that hanging async steps get GC'd

### ISSUE THREAD

**Issue by pchiusano** [functional-streams-for-scala/fs2#536]
I'm not totally sure how to test this, but in something like `a merge (Stream.emit(b)) take 1`, `a` should get garbage collected even if it is 'left running' (because it is waiting on a queue that never gets filled, say). If this is done repeatedly, the memory usage should stay constant, rather than growing linearly due to there still being a dangling reference to the (now zombie) steps.

**Comment by pchlupacek** [comment]
@pchiusano @mpilquist I beleive this was fixed by recent discoveries and #661 ?

**Comment by mpilquist** [comment]
:+1:
