### ISSUE TITLE
Flesh out user guide, port examples from pre 0.9, and ensure all examples compile

### ISSUE THREAD

**Issue by pchiusano** [functional-streams-for-scala/fs2#537]
Here's what I'm thinking:

* Use @tpolecat's [tut](https://github.com/tpolecat/tut) to make sure all snippets in [the guide](https://github.com/functional-streams-for-scala/fs2/tree/topic/redesign/docs) compile. The docs directory should become a new subproject, listed in `build.sbt`, and which pulls in the tut plugin.
* Longer form examples can go in the newly created `docs` subproject as regular `.scala` files

See #419

Volunteers wanted for this!

**Comment by ChrisCoffey** [comment]
If nobody has picked this up I'd like to take it on, provided you're okay with me learning the library as I go.

**Comment by mpilquist** [comment]
@ChrisCoffey Go for it! Happy to help, provide feedback, etc. I'm planning on recording a few screencasts that introduce 0.9.0 soon, though they are much more of a snapshot-in-time style than living documentation.
