### ISSUE TITLE
nio.file.chunkReadBuffer can return an underfilled buffer before EOF

### ISSUE THREAD

**Issue by refried** [functional-streams-for-scala/fs2#559]
like #498
relates to #538

**Comment by refried** [comment]
backported to 0.8 and 0.8a in #561 and #563 respectively

**Comment by mpilquist** [comment]
Leaving open so we make sure to address in 0.9 as well.

**Comment by mpilquist** [comment]
@fiadliel We can close this right? The 0.9 file api doesn't have this issue.

**Comment by fiadliel** [comment]
I would expect to get a read size equal to the requested number of bytes (other examples of this happening have been from sources other than files), but the API doesn't guarantee this.

I do have one small reservation about the idea, the `Pull` might not progress in pathological cases (where we continually get 0 bytes). But it does match what people seem to expect from the API, and chances of this happening are (hopefully) extremely low.

**Comment by fiadliel** [comment]
Addendum: I'll send a PR.

**Comment by mpilquist** [comment]
We decided it was best to support this use case by sending the output of the various file streams through one of the chunk management combinators, like `rechunkN`.
