### ISSUE TITLE
Release 0.8.1 / 0.8.1a

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#570]
There's [some interest](https://gitter.im/functional-streams-for-scala/fs2?at=5701d21ee4a8384a1bbe7fa4) in releasing 0.8.1(a) with fixes #498 and #559. Does anyone have any objections? If not, I'll do these release sometime this week. /cc @djspiewak @pchlupacek

**Comment by pchlupacek** [comment]
+1

**Comment by mpilquist** [comment]
0.8.1 and 0.8.1a for scala 2.10.6, 2.11.8, and 2.12.0-M4 are now on Sonatype.
