### ISSUE TITLE
fs2.concurrent.join is broken with Task.async

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#572]
While working on io.tcp I discovered to me incorrect behaviour of concurrent.join when working with async- based streams. I have created the stream of processes that essentially sleep about a 1s and then prints their result. The code is below:

```scala
val open = new AtomicInteger(0)
 val parent:Stream[Task,Stream[Task,Unit]] = Stream.emits(0 to 20).map { idx =>
    val sleep = (Math.random() * 1000).millis
    eval(Task.delay(println(s"START($idx, ${sleep.toMillis}, ${open.incrementAndGet()})"))) ++
      time.sleep(sleep) ++
      eval(Task.delay(println(s"DONE($idx, ${open.decrementAndGet()})")))
  }
concurrent.join(Int.MaxValue)(parent).run.run.run
```

now this only starts all processes but none of them really terminates. Essentially this runs everything up to result of async evaluation of `time.sleep` (to be clear this starts the time.sleep, but never terminates). 

to verify this I just modified a code to block the thread by delay likewise: 
```scala
val open = new AtomicInteger(0)
 val parent[Task,Stream[Task,Unit]] = Stream.emits(0 to 20).map { idx =>
    val sleep = (Math.random() * 1000).millis
    eval(Task.delay(println(s"START($idx, ${sleep.toMillis}, ${open.incrementAndGet()})"))) ++
     eval(Task.delay(Thread.sleep(sleep.toMillis))) ++
      eval(Task.delay(println(s"DONE($idx, ${open.decrementAndGet()})")))
  }
concurrent.join(Int.MaxValue)(parent).run.run.run
```
And that code works. 

I dig a little bit more, and found (to me) strange behaviour of join : 
  - when you start join it first evaluates all heads of the supplied processes in order as they have been submitted ( I would expect them to be evaluated in order, but interleaved with evaluation of other elements too, longer the initial `parent` process runs)
  - when all `heads` of childrens are evaluated, this will run the second elements, but in _reverse_ order as they have been submitted by `parent` process. (I would expect this to be run and interleaved randomly). 

@pchiusano @mpilquist can you take a quick look on that?

**Comment by pchlupacek** [comment]
I have digged into implementation, and, I think that cause relies in here https://github.com/functional-streams-for-scala/fs2/blob/topic/redesign/core/src/main/scala/fs2/concurrent.scala#L39. I am also not confident that this approach will scale performance-wise beyond hundred of open requests, mainly because how Future.race is implemented, where we traverse at every `get` full stack of open requests (see here  https://github.com/functional-streams-for-scala/fs2/blob/topic/redesign/core/src/main/scala/fs2/Async.scala#L167).

**Comment by mpilquist** [comment]
@pchlupacek Hm, I can't get your initial example to fail. Here's some sample output:

```
scala> p.run.run.run
START(0, 696, 1)
START(1, 94, 2)
START(2, 321, 3)
START(3, 620, 4)
START(4, 125, 5)
START(5, 505, 6)
START(6, 300, 7)
START(7, 815, 8)
START(8, 92, 9)
START(9, 995, 10)
START(10, 756, 11)
START(11, 586, 12)
START(12, 306, 13)
START(13, 521, 14)
START(14, 675, 15)
START(15, 445, 16)
START(16, 591, 17)
START(17, 372, 18)
START(18, 489, 19)
START(19, 514, 20)
START(20, 713, 21)
DONE(8, 20)
DONE(1, 19)
DONE(4, 18)
DONE(6, 17)
DONE(2, 16)
DONE(12, 15)
DONE(17, 14)
DONE(15, 13)
DONE(18, 12)
DONE(19, 11)
DONE(5, 10)
DONE(13, 9)
DONE(11, 8)
DONE(0, 7)
DONE(20, 5)
DONE(16, 6)
DONE(3, 4)
DONE(14, 3)
DONE(10, 2)
DONE(7, 1)
DONE(9, 0)

scala> p.run.run.run
START(0, 272, 1)
START(1, 807, 2)
START(2, 401, 3)
START(3, 17, 4)
START(4, 273, 5)
START(5, 171, 6)
START(6, 470, 7)
START(7, 670, 8)
START(8, 643, 9)
START(9, 450, 10)
START(10, 624, 11)
START(11, 997, 12)
START(12, 916, 13)
START(13, 965, 14)
START(14, 536, 15)
START(15, 873, 16)
START(16, 118, 17)
START(17, 27, 18)
START(18, 393, 19)
START(19, 122, 20)
START(20, 931, 21)
DONE(3, 20)
DONE(17, 19)
DONE(19, 18)
DONE(16, 17)
DONE(5, 16)
DONE(0, 15)
DONE(4, 14)
DONE(2, 13)
DONE(18, 12)
DONE(9, 11)
DONE(6, 10)
DONE(14, 9)
DONE(10, 8)
DONE(8, 7)
DONE(7, 6)
DONE(1, 5)
DONE(15, 4)
DONE(12, 3)
DONE(20, 2)
DONE(13, 1)
DONE(11, 0)
```

**Comment by pchlupacek** [comment]
@mpilquist just for clarification you are running from which branch? I am still using topic/redesign...

**Comment by mpilquist** [comment]
I'm using topic/redesign too.

**Comment by pchlupacek** [comment]
seems I must have somehow merged things incorrectly. I'll dig into that today.

**Comment by pchlupacek** [comment]
@mpilquist  got it working too. I am still confused about this part mentioned on concurrency, but I'll track that later. Thanks and sorry for mess.
