### ISSUE TITLE
Finalizers are not called in expected order in concurrent.join

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#589]
Finalizers in concurrent.join are called in reverse order. The following code 
```scala

  concurrent.join(10)(
    Stream.range(0,3).map { idx =>
      emit(idx)
      .onFinalize(Task.delay(println(s"INNER DONE $idx (A)")))
      .onFinalize(Task.delay(println(s"INNER DONE $idx (B)")))
    }
    .onFinalize(Task.delay(println(s"OUTER DONE (A)")))
    .onFinalize(Task.delay(println(s"OUTER DONE (B)")))
  )
  .onFinalize(Task.delay(println(s"MERGE DONE (A)")))
  .onFinalize(Task.delay(println(s"MERGE DONE (B)")))
  .runLog.run.unsafeRun

```

outputs 

```
OUTER DONE (A)
OUTER DONE (B)
INNER DONE 2 (B)
INNER DONE 0 (B)
INNER DONE 2 (A)
INNER DONE 0 (A)
INNER DONE 1 (B)
INNER DONE 1 (A)
MERGE DONE (A)
MERGE DONE (B)

```

while serialised version (flatMap instead of join) outputs 

```
INNER DONE 0 (A)
INNER DONE 0 (B)
INNER DONE 1 (A)
INNER DONE 1 (B)
INNER DONE 2 (A)
INNER DONE 2 (B)
OUTER DONE (A)
OUTER DONE (B)
MERGE DONE (A)
MERGE DONE (B)
```

Note that there are two problems, actually:
(a) inner stream finalizers are called in reverse order 
(b) OUTER finalizer is called before INNER processes are completed.

**Comment by pchiusano** [comment]
On a) the inner stream finalizers are run in nondeterministic order. The inner streams are running concurrently so there won't be any guarantee on the order their finalizers are run in. That seems unavoidable, right? b) might be fixable somehow.

EDIT: I can think of a fix for b), it's basically using the logic that waits for the inner streams to terminate ([here](https://github.com/functional-streams-for-scala/fs2/blob/topic/redesign/core/src/main/scala/fs2/concurrent.scala#L41)). Except that should be invoked at the end of the stream (using `noneTerminated`), and only invoked once.

**Comment by pchiusano** [comment]
Not sure if my comment made any sense, but I realized it won't work. We need to insert some logic BEFORE the end of the outer stream, before its finalizers start running. I cannot see any way of doing that, since those finalizers may have been added before the call to join. Main limitation is that we can only append finalizers, to be called after other ones, can't prepend.

**Comment by pchlupacek** [comment]
@pchiusano I am just pushing the small PR that fixed cause in concurrent join of `done` not being invoked in certain cases. Unfortunately I am unable yet to minimize the case (found it when testing tcp) so it didn't come with any test. Maybe you will spot the reason?

**Comment by pchlupacek** [comment]
@pchiusano on the finalizers. (a) I am ok with finalizers to be run nondet for the inner processes. But the finalizers for one given inner process shall be run in expected order, that means `A` before `B` and that what I observed is not the cause.

on the (b) I am not really sure if my suggestion was correct one. For example if you run long-running `inner` processes. So thinking about it again, I think the in fact that if it is run as soon as `outer` is terminated is correct (current behaviour). If there is absolutelly need finalizer to be run after all `inner` streams one may attach it after conncurrent.join, eventually.

**Comment by pchiusano** [comment]
Ah gotcha. That is weird. Not sure what is going on there. Good point on b)
attaching finalizers to result of join seems like best way to handle that.

**Comment by pchlupacek** [comment]
Ah, excellent and thanks for hard work there
