### ISSUE TITLE
Add closable queue

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#606]
The 0.9 queue does not support closing. We should add a `ClosableQueue` implemented in terms of `Queue` and a close `Signal`. We might also want to consider opt-in support for propagating failures from the enqueue stream to the dequeue stream.

See https://github.com/functional-streams-for-scala/fs2/issues/441 for some discussion.

@pchlupacek I assigned this to you since you've mentioned working on it before. Let me know if that's okay or if you want me to take a shot.

**Comment by pchlupacek** [comment]
@mpilquist yeah, I am on it

**Comment by pchlupacek** [comment]
Just to clarify the behaviour here. Shall we drop all the `A` enqueued after queue will be closed? Essentially no re-opening support right?

**Comment by mpilquist** [comment]
Right

**Comment by mpilquist** [comment]
@pchlupacek Are you still thinking we drop this? I took a shot at implementing it last week in context of another issue, but I ended up not liking the implementation and deleted it. I'm okay with closing this.

**Comment by pchlupacek** [comment]
:-) I may implement it. I am just not bought that it is really, really needed. In fact, the closeXXX, failXX in 0.8 lead to a lot of bugs which we are still hunting as we speak. So I am more thinking this is sort of devil hole we will put in. Lets close it if you don't have objections and if we would have demands for this I am ok to implement it.

**Comment by mpilquist** [comment]
Sounds good. I'll close for now and we can always revisit in the future if we have a need for it.
