### ISSUE TITLE
Add support for topics

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#607]
There's no `Topic` in 0.9. This issue tracks adding types like `Topic`, `ClosableTopic`, `WriterTopic`, etc. -- likely in a release after 0.9. The new design should support back pressure.

For discussion see:
 - https://github.com/functional-streams-for-scala/fs2/issues/441
 - https://github.com/functional-streams-for-scala/fs2/issues/244

Let's discuss requirements, designs, & prototypes on this issue. I'd like to get some buy-in from folks before we do significant implementation.

**Comment by pchlupacek** [comment]
Even though we are using the topic heavily now, I am sort of inclining to replace it with signal altogether. Or at least implement it only in terms of signal of tuples, or possibly tuple and optional message going in. 

On the back-pressure side, I am not sure what is the correct approach, perhaps only I am thinking of is to stop (kill) the clients (subscribers) that are significantly behind.

**Comment by pchlupacek** [comment]
fixed by #627
