### ISSUE TITLE
TCP tests intermittently fail on Travis

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#639]
E.g., https://travis-ci.org/functional-streams-for-scala/fs2/jobs/134288718

**Comment by pchlupacek** [comment]
I'll take a look on that I think may be related to OS resources like number of open files etc. 
Don't really see something wrong with code. 
Never hit that on my machine.You were able to reproduce it locally?

**Comment by pchlupacek** [comment]
We do 10.000 clients with 10 concurrent requests. Perhaps will decrease this to 1000 and see if that gets better?

**Comment by mpilquist** [comment]
@pchlupacek I don't think I've seen it fail locally (though I may be wrong). I've been meaning to link to one of these Travis failures for a while and haven't had a chance until today. It's probably like 2-5% failure rate on Travis.

**Comment by mpilquist** [comment]
This seems to be fixed.
