### ISSUE TITLE
Introduce Sink1 and Channel1

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#648]
Hence with 0.9 we do have `Sink` and `Channel` that is in fact alias for `Pipe` , I would like to propose to introduce two new types defined as : 
```scala 

  type Sink1[F,A] = Stream[F,A => F[Unit]]
  type Channel1[F,A,B] = Stream[F,A => F[B]]

```

The reason for these is to 
  1. make interop with 0.8 code easier (they are in fact same signature as 0.8 sink, and channel)
  2. allow for sinks that are allocating resources and after sink // process is done to releasing them 
  3. I think they may be generally more understandable than just using that `diamond` versions
  4. We sort of missing good story on serial effects like we had in 0.8

I also want to define on them following combinators:

```scala
def asPipe: Pipe[F,A,B] = ???

def pipeIn[I2](in:Pipe[F,I2,A]):Pipe[F,I2,B] = ???
def pipeOut[O2](in:Pipe[F,A,O2]):Pipe[F,A,O2] = ???
 
def mapIn[I2](f: I2 => I):Pipe[F,I2,B]  = ???
def mapOut[O2](f: O => O2):Pipe[F,I2,B]  = ???

def mapInF[I2](f: I2 => F[I]):Pipe[F,I2,B]  = ???
def mapOutF[O2](f: O => F[O2]):Pipe[F,I2,B]  = ???

// on the StreamInvariantOps I'd like to add

def observe1(snk:Sink1[F,A,Unit]):Stream[F,A] = ???
def through1(ch:Channel1[F,A,B]):Stream[F,B] = ???
def observeThrough1(ch:Channel1[F,A,B]):Stream[F,(A,B)] = ???

```

The implementation will be similar as with 0.8. that means zipWith + evalMap

@pchiusano @mpilquist are you ok with this?

**Comment by mpilquist** [comment]
@pchlupacek At this point, I'm not convinced that we need these, though I'm happy to discuss. Could you provide some examples of the types of sinks/channels that you can write this way but are hard to express in the current 0.9 version? One reason I'd rather we not define these is that it will bifurcate the library -- some code will use `Sink`/`Channel` and others will use `Sink1`/`Channel1`, often without good reason. Additionally, folks using the library would need to learn both forms of sinks/channels. That's a high price to pay so there needs to be large benefits of doing this.

Some comments on the motivations you listed:

> 1. make interop with 0.8 code easier (they are in fact same signature as 0.8 sink, and channel)

The change in `Channel`/`Sink` was deliberate in 0.9, allowing stateful channels/sinks to be represented and unifying the concept with pipes.

> 2. allow for sinks that are allocating resources and after sink // process is done to releasing them

Can you provide an example here? Seems like we have this already via the pattern: `val mySink: Sink[F,A] = (s: Stream[F,A]) => Stream.bracket(acquire)(r => s.evalMap(use(r)), release)`

> 3. I think they may be generally more understandable than just using that diamond versions

Can you elaborate on this?
 
> 4. We sort of missing good story on serial effects like we had in 0.8

Can you elaborate on this?

**Comment by pchlupacek** [comment]
@mpilquist thanks for this view. In fact I was sort of reluctant to open the issue, but there are some cases which I am not really sure how to effectivelly cover for now. 

In our code we use Writer[F,O,W] a lot. Usually what we do, we write somethink like this 

```scala 

val source: Writer[F,O,W] = ???
val sinkO:Sink[F,O] = ???
val sinkW:Sink[F,W] =???

source.observeW(sinkW).observeO(sinkO) 

```

Now given current sink representation, I am not really sure that there is better approach than something like this (given we will write observeW, observeO combinators) : 

```scala

val source:Stream[F,Either[W,O] = ???
val sinkW:Sink[F,W] =???
val sinkO:Sink[F,O] = ???

def observeW(sink:Sink[F,W]):Channel[F,Either[W,O],Either[W,O]] = ???
def observeO(sink:Sink[F,O]):Channel[F,Either[W,O],Either[W,O]] = ???

source.through(observeW(sinkW)).through(observeO(sinkO))

```

which doesn't look that bad, in fact. However I somehow prefer still the first syntax. But totally agree this is matter of style. 

Now, this sort of works with Either[W,O] where you have just two cases to cover. 

However we also use lot of HList and Coproduct in our code. And here it comes a bit interesting. Lets say  we have this piece of code : 

```scala

type C = String :+: Int :+: Long :+: Byte :+: CNil

val source: Process[F,C] = ???

// now lets say on Process we have pickA[T] that essentially takes `T` from coproduct and returns new Coproduct w/o `T`

source
.pickA[String](stringSink)
.pickA[Int](intSink)
.pickA[Long](longSink)
.pickA[Byte](byteSink)
:Process[F,CNil]

```
Now the previous example can be of course written in new sinks similarly, essentially evaluating each sink step by step untill we match the correct one. 

But lets say we have combinator, that allows us to combine these sinks in "horizontal" way essentially making them that `C` type:

```scala

def appendC[A, B](sinkA:Sink[F,A], sinkB:Sink[F,B)):Sink[F.A :+: B :+: CNil] = ??? //
def appendCcons[A, C <: Coproduct](sinkA:Sink[F,A], sinkB:Sink[F,C)):Sink[F.A :+: C] = ??? 

// below can be written with suggar syntax, this is just to see clearly whats going on ...
val sinkC :Sink[F,C]= appendCcons(stringSink, appendCcons(intSink,appendC(longSink,byteSink))

//then you can 
source.observe(sinkC)

```
I really son't know how to express this in current Sink/Channel 0.9 representation. This is what I meant by `serial` effects (was not able to come with better word for it :-(). Advantage of this approach is that you only take that `F` if you really need it for type coming in. 

We can consider this a specific Coproduct case. But once you start program this way, you start to enjoy it so much. Imagine for example Generic from sealed traits, where you just define sinks for every trait, combine them this way and then you have just a simple combinator to bind them together.  

I still think Sink1, Channel1 makes sense. Probably may not be the first class citizens in fs2.

**Comment by mpilquist** [comment]
@pchlupacek Thanks, this helps a lot. I'd like to think about this some more over next few days.

**Comment by pchlupacek** [comment]
@mpilquist Thanks. After give it more thought I am not sure if `observeW(sinkW)` == `observeW(sinkW)` anymore, as this was the reason for introducing the `diamond` operator. And if you see the complexity of todays observe implementation I am also worried about final performance numbers of observe.

**Comment by mpilquist** [comment]
@pchlupacek One thing to consider regarding performance -- `s.evalMap { a => f(a).map(_ => a) }` will be much faster than using `observe` and it should also be much faster than zipping with a `Sink1` and then using `evalMap`. Today's `observe` implementation isn't particularly fast but it is no worse than `concurrent.join`.

**Comment by pchlupacek** [comment]
@mpilquist fully agree.  In fact, lot of times we were doing this sort of thinks in 0.8 manually essentially recycling the function and getting rid of tee altogether. On other hand the diamond with sync queues, not sure about that. All these reasons are sort of giving me hope we must be able to do it much better, we just don't see it yet :-)

**Comment by pchiusano** [comment]
My feeling is let's not introduce these right now, for pretty much the reasons @mpilquist gave. Nothing stops anyone from defining these aliases in their own code along with any combinators to go with them, but I'm just not sold that they are important enough to put in the core library (which is yet another distinction that people then have to learn about).

It does feel kind of inelegant that even `observe` still requires an `Async[F]` bound, but I'm not sure there's a good fix for that, at least not without totally changing the representation of `Pipe`, etc, which is quite nice IMO.

**Comment by pchlupacek** [comment]
Ok I am surrendering :-)

**Comment by pchiusano** [comment]
Ha okay. Closing for now then.
