### ISSUE TITLE
Stream.bracket acquires cleanup eagerly 

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#649]
Stream.bracket acquires cleanup action eagerly, instead invoking it after the process terminated. this causes strict `F` cleanup to be ewaluated before stream terminates.
So 

```scala

 
    bracket(Task.delay{resource.actions = resource.actions :+ "ACQUIRED"; resource })(
          { r => r.actions = r.actions :+ "USED"; emit(r) }
          , { r => r.actions = r.actions :+ "RELEASE INVOKED"; Task.delay{ r.actions = r.actions :+ "RELEASED" } }
        )

      p.flatMap { r =>
        r.actions = r.actions :+ "FLATMAP" 
        emit(r)
      }.run.unsafeRun

      resource.actions.foreach(println)


```

will output

```
ACQUIRED
RELEASE INVOKED
USED
FLATMAP
RELEASED
```

whereas correct shall be 

```
ACQUIRED 
USED
FLATMAP
RELEASE INVOKED
RELEASED
```

**Comment by mpilquist** [comment]
We could fix easily enough (by wrapping cleanup action with an `F.suspend`). I'm not certain whether we should do so or not. With that change, I suppose the API is more intuitive, though the only observable difference is in side effects. I think we should change it though.

**Comment by pchlupacek** [comment]
@mpilquist not sure if that works. The issue is that some F's are eager too, so one that cleanup is invoked they start to run. I think we may be required to  pass cleanups in form of R => F[Unit] . Not sure if that is possible though. If not we have to perhaps just clearly state that cleanup is computed once the resource is allocated and not when it is released. Which I agree is very very confusing.

**Comment by mpilquist** [comment]
@pchlupacek Sorry, I shouldn't have said `F.suspend` -- we can use `Free.suspend` in this case, which allows this to work for all `F`. For example, I think this is all we'd need to change:
```
iff --git a/core/src/main/scala/fs2/StreamCore.scala b/core/src/main/scala/fs2/StreamCore.scala
index 41043a2..89fd69b 100644
--- a/core/src/main/scala/fs2/StreamCore.scala
+++ b/core/src/main/scala/fs2/StreamCore.scala
@@ -326,7 +326,7 @@ object StreamCore {
       StreamCore.attemptEval(r).flatMap {
         case Left(e) => StreamCore.evalScope(Scope.cancelAcquire(token)) flatMap { _ => StreamCore.fail(e) }
         case Right(r) =>
-          StreamCore.evalScope(Scope.finishAcquire(token, cleanup(r).attempt))
+          StreamCore.evalScope(Scope.finishAcquire(token, Free.suspend(cleanup(r).attempt)))
                     .flatMap { _ => StreamCore.emit(r).onComplete(StreamCore.release(List(token)).drain) }
       }
     }
```

**Comment by pchlupacek** [comment]
mpilquis +1 that will work :-) Cool
