### ISSUE TITLE
text.lines leaves a \r when an \r\n pair spans a chunk boundary 

### ISSUE THREAD

**Issue by martijnhoekstra** [functional-streams-for-scala/fs2#660]
text.lines leaves a \r if a chunk ends with a string that ends in \r and the next chunk starts with \n

```
Stream("foo\r", "\nbar")
    .throughPure(text.lines)
    .toList
    .head == "foo\r"
```

evaluates to false, but

```
Stream("foo\r", "\nbar")
    .unchunk
    .throughPure(text.lines)
    .toList
    .head == "foo\r"
```

evaluates to true

**Comment by mpilquist** [comment]
@martijnhoekstra I took a quick look at this bug and noticed the `pendingLineFeed` flag wasn't preserved over chunk boundaries. Sorry if you were already working this in parallel. If you want to do some performance work on the implementation, please feel free. :)
