### ISSUE TITLE
Queue does not implement dequeueAvailable

### ISSUE THREAD

**Issue by djspiewak** [functional-streams-for-scala/fs2#682]
The `dequeueAvailable` and `dequeueBatch` functions are *really* important features of the 0.8-era `Queue`, as they are the only mechanism which allows for variable batching catch-up based on timing.  They aren't all that difficult to implement, and given the way that `Queue` is used in practice, should be a high priority for 0.9 if at all possible.

**Comment by pchiusano** [comment]
@djspiewak these seem like they could be easily implemented as combinators on a `Queue[F,Chunk[A]]` (by design the 0.9 queues do not bake in chunking). Using [`Pull.awaitLimit`](https://github.com/functional-streams-for-scala/fs2/blob/series/0.9/core/src/main/scala/fs2/pull1.scala#L23), for instance.

```Scala
// q : Queue[F,Chunk[A]]
Stream.repeatEval(q.dequeue1).unchunk.pull { h => /* use awaitLimit/awaitN */ }.close
```

I don't have strong feelings about whether this functionality should be included in FS2 core. If it were in core, I'm not sure where I'd put it. Could just be an `implicit class` in `Queue` companion object? Maybe other folks could weigh in here.

**Comment by djspiewak** [comment]
@pchiusano I believe that implementing `dequeueBatch` in the fashion you suggest will always result in chunk sizes of 1.  This is basically the problem with doing these combinators in "user land" rather than making them primitive and implementing `dequeue1` in user land: you don't know how much more the queue can offer you.  The queue knows.  You don't.

Also, I additionally do not believe it is possible to (sanely) implement `dequeueAvailable`, which is the combinator you *actually* want in about 99% of real cases (at least in my experience).  `dequeueBatch` is not actually as helpful as it seems if you can't get the unbounded variant.

**Comment by pchiusano** [comment]
Ah, I get it. You want to be able to dequeue the maximum possible without
blocking. How about adding tryDequeue1 as a primitive - it would return an
Option and would be generally useful, in addition to making
dequeueAvailable easy to write.

**Comment by djspiewak** [comment]
That would work, but would be absurdly inefficient.  I frequently do this in batches in the thousands or tens of thousands.  A better approach would be to implement dequeue1 in terms of dequeueAvailable, as it is in 0.8.

**Comment by pchlupacek** [comment]
@djspiewak @pchiusano I don't think for the queue there is big deal in having the queue to support chunking natively. Only we have sort of agree on behaviour of what will happen when we will have multiple de-queuers (i.e would they get fair share of chunk elements, or would just first of them receive the whole chunk etc..). Before going into details any ideas on how this could be expressed?

**Comment by pchiusano** [comment]
You can't implement dequeue1 in terms of dequeueAvailable since you'd have
to put back the extra elements and there's no way to do that (don't
really want to add an un-dequeue operation).

But, yeah I see your point. I am okay with adding tryDequeue1 and
dequeueAvailable, which I'd maybe give a default implementation in terms of
tryDequeue1 (or have a defaultDequeueAvailable so you have to explicitly
opt-in to using it in your impl). Then you can have your optimized
implementation.

If no one has any objections, perhaps you'd like to do a PR? 😀 Change
should be simple.

**Comment by pchlupacek** [comment]
so 
- dequeueAvailable -> get AllChunks available, drain queue to be empty 
- tryDequeue1 -> what that shall exactly do?

**Comment by pchiusano** [comment]
It always returns immediately, None if queue is currently empty, otherwise
same result as a dequeue1

**Comment by pchlupacek** [comment]
cool, thanks fine with both. @djspiewak lmk if you want pr these or I gonna do them over weekend..

**Comment by djspiewak** [comment]
@pchlupacek I almost certainly won't have time to do it until this weekend, so you should go ahead.

@pchiusano I slightly misspoke.  `dequeue1` can be implemented in terms of `dequeueBatch: Option[Int] => Stream[F, Chunk[A]]`, and `dequeueAvailable` can be done in the same way.  0.8 does this, except instead of `None` it uses a batch size of `0` to indicate unbounded.

In general, `dequeueAvailable` is vastly more useful than `dequeueBatch`, so I wouldn't be averse to only seeing the former rather than the latter.  I *strongly* disagree with @pchlupacek's assertion that it isn't really needed behavior.  It would not be an exaggeration to say that 70-80% of my real-world use of 0.8 `async.boundedQueue` involves `dequeueAvailable` in some form, and it remains the only viable mechanism for doing variable bounded catch-up batching.

I will also fall back on the argument I made when we implemented `dequeueAvailable` in the first place (a year-ish ago), which is that multiple dequeuers is undefined behavior (namely, who gets what data), and I don't see an issue with that undefined behavior being magnified by batching and error recovery (which is an important follow-up to `dequeueAvailable`).

**Comment by pchlupacek** [comment]
@djspiewak ok, so are we on the same page to implement 
- dequeueAvailable -> get AllChunks available, drain queue to be empty, blocks (async) if queue is empty
- tryDequeue1 -> returns immediately if queue is dry
to resolve this issue?

**Comment by pchiusano** [comment]
Assuming @djspiewak is cool with that resolution, let's let him implement the PR. 😀 He proposed the change and implementing the PR will give him more exposure to the new async stuff.

**Comment by pchlupacek** [comment]
:-) ok

**Comment by mpilquist** [comment]
Ping @djspiewak

**Comment by mpilquist** [comment]
Since this impacts API, I'd like to get this in before 0.9.0-RC1. Anyone have time to implement in the coming week?

**Comment by fiadliel** [comment]
Is anybody else working on this? I can submit a PR this week, and have some working code.

**Comment by mpilquist** [comment]
Not that I've heard - have at it. :)
