### ISSUE TITLE
0.8 release causes process failures to be swallowed

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#684]
In 0.8 release any process using receive1Or  or similar is subject of swallowing any failure or an early termination.

i.e.:

``` scala

@ val dbQuery:Process[Task,Int] = time.sleep(1.second) ++ Process.fail(new Throwable("query failed")) 
dbQuery: Process[Task, Int] = Append(Halt(End), Vector(<function1>, <function1>))

@ val sendResult:Sink[Task,Int] = scalaz.stream.sink.lift { x => Task.now(println("RESULT IS ", x)) } 
sendResult: Sink[Task, Int] = Append(Emit(Vector(<function1>)), Vector(<function1>))

@ dbQuery.pipe(process1.sum).through(sendResult).run.run 
(RESULT IS ,0)
java.lang.Throwable: query failed
  ammonite.session.cmd19$$anonfun$1.apply(cmd19.scala:1)
...

```

Perhaps this didn't seem too drastic, but imagine that our query to database has failed, and still we have received that sum of whatever we have in db is "0". Finally, the stream crashes, but may not so, for example if sink is replaced with flatMap that may attach whatever process (perhaps even recursion)

I think this behaviour may lead in current 0.8 code to non-deterministic program states, may cause a whole of hard-to-debug issues and wrong code behaviour assumptions. 

@pchiusano, @mpilquist what are your thoughts on this? Worth of fixing ?

**Comment by djspiewak** [comment]
This is a partial out-growth of the fact that we never got around to really making `pipe` and `tee` error propagation sane in any realistic way.  The proposal was there, but I don't think it was ever implemented.  So there are actually quite a few cases like this.

**Comment by pchlupacek** [comment]
Closing as per #1091.
