### ISSUE TITLE
stateless effectful unfold?

### ISSUE THREAD

**Issue by tpolecat** [functional-streams-for-scala/fs2#690]
`StreamDerived.unfoldEval` provides for unfolding with passed state, but effectful computations can have their own state, which allows for a simpler "unfold", equivalent to `unfoldEval` with unit state.

```scala
def unroll[F[_], T](f: F[Option[T]]): Process[F,T] = {
  def go: Process[F, T] =
    eval(f).flatMap {
      case Some(a) => emit(a) ++ go
      case None    => empty
    }
  suspend(go)
}
```

If this seems reasonable (I'm using it with doobie where my `f` is "read the next thing from the resultset, if any") I can do a PR, or feel free to copy/paste.

**Comment by mpilquist** [comment]
Closing per discussion on #691
