### ISSUE TITLE
Problematic TCP Spec (SocketSpec)

### ISSUE THREAD

**Issue by NightRa** [functional-streams-for-scala/fs2#699]
In the TCP spec, SocketSpec, it is asserted that all chunks contained the whole message `fs2.rocks`.
TCP semantics don't assure this, the OS and the network may fragment and frame differently, resulting in partial messages.

**Comment by pchlupacek** [comment]
@NightRa Are you experiencing a failure? Because spec is reading constant 1024 bytes chunks which is well above the size of the message and shall guard agains different os'es and buffers.

**Comment by NightRa** [comment]
@pchlupacek read(maxBytes) is documented to read up to maxBytes, not forcing to read that amount if available.
Should it behave differently?
(No, did not experience failure, but I imagine it could happen over the network, but not locally)

**Comment by pchlupacek** [comment]
hm, Also it states 
"Evaluates to None, if there are no more bytes to be read in future, due stream reached End-Of-Stream state" so I think this is consistent isn't it?

**Comment by pchlupacek** [comment]
Ah I know what do you mean

**Comment by pchlupacek** [comment]
well feel free to fix the test.

**Comment by NightRa** [comment]
A reproducable failing case would be sending a message of over 15k bytes with a buffer bigger than 15k over ethernet.

**Comment by NightRa** [comment]
@pchlupacek Sure, I'll give it a go :)

**Comment by pchlupacek** [comment]
@NightRa Exactly what I thought this is the reason why the test is using few bytes to be always below the buffer size so we won't experience that. That's why I have asked you if you experience this test to fail. I think under reasonable OS setting it should never be the cause, but perhaps I am wrong. If you want to enhance this test please feel free :-)

**Comment by pchlupacek** [comment]
@NightRa are you going to touch this?

**Comment by NightRa** [comment]
@pchlupacek No, I'm busy with other things

**Comment by pchlupacek** [comment]
@mpilquist me feeling to this is that this is corner case and test proves today enough functionality, what do you think?

**Comment by mpilquist** [comment]
👍
