### ISSUE TITLE
Broken example in guide returns null

### ISSUE THREAD

**Issue by chuwy** [functional-streams-for-scala/fs2#700]
I'm trying to implement [Asynchronous effects (callbacks invoked once)](https://github.com/functional-streams-for-scala/fs2/blob/series/0.9/docs/guide.md#talking-to-the-external-world) with imitation of async computation:

```scala
import fs2._
import fs2.util.Async

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.Future
import scala.util.{ Try, Success, Failure }

object Test {
  implicit val S = fs2.Strategy.fromFixedDaemonPool(8, threadName = "worker")
  val T = implicitly[Async[Task]]
  val f = Future { Thread.sleep(5000); 42 }  // Imitate async computation

  def run(onComplete: Either[Throwable, Int] => Unit): Unit = {
    f.onComplete { t => onComplete(tryToEither(t)) }
  }

  val answer = T.async[Int] {
    (cb: Either[Throwable, Int] => Unit) => T.delay.run(cb))
  }
}
```

In the end my `Test.answer` is `fs2.Task[Int] = null`.

I think even if I'm doing something very stupid (which is likely) there still shouldn't be such an easy way to receive `null`.

I'm working with fs2 0.9.0-M6 and Scala 2.11.8. Above example was executed in sbt console.

**Comment by chuwy** [comment]
Wow! That is interesting. Above example works as expected. But originally I had two objects:

```scala
object Watcher {
  val f = Future { Thread.sleep(5000); 42 }
  def run(onComplete: Either[Throwable, Int] => Unit): Unit = {
    f.onComplete { t => onComplete(tryToEither(t)) }
  }
}

object Main extends App {
  implicit val S = fs2.Strategy.fromFixedDaemonPool(8, threadName = "worker")
  val T = implicitly[Async[Task]]
  val answer = T.async[Int] {
    (cb: Either[Throwable, Int] => Unit) => T.delay(Watcher.run(cb))
  }
```

And above really returns `null`. Could it be caused by `App` trait? I have no other explanations.

**Comment by mpilquist** [comment]
Weird! I've seen things like this when you end up with a null strategy or null `Async` instance. For example:

```
@ object Foo { implicit val T: Async[Task] = implicitly[Async[Task]] }
defined object Foo
@ Foo.T
res4: Async[Task] = null
```

I don't see that happening in your case but maybe something with the `App` trait is causing initialization order issues or something?

**Comment by chuwy** [comment]
`App` trait is `scala.App`. Do I need to retry with `main` method instead?

**Comment by mpilquist** [comment]
Not sure -- I tried the `Watcher/Main` example in a REPL and everything works fine. Note that I had to call `Main.main(Array.empty)` first.

**Comment by mpilquist** [comment]
```
@ Main.answer
res17: Task[Int] = null
@ Main.main(Array.empty)

@ Main.answer
res19: Task[Int] = Task
```

I think this explains the behavior you are seeing -- namely, that the code that looks like it runs in the constructor of the `Main` is really deferred until the `main` function is invoked, via the magic of the `App` trait.

**Comment by chuwy** [comment]
Thank you! That solves problem for me. Not sure if we need to add some warning about it or it is a supposed behavior.

**Comment by mpilquist** [comment]
I don't think we should mention anything in FS2 docs -- rather, I think `App` should be avoided altogether because it leads to these types of unexpected behaviors. For example, here's a super simple program with the same issue:
```
@ object Main extends App { val msg = "Hello, world!"; println(msg) }
defined object Main
@ Main.msg
res2: String = null
@ Main.main(Array.empty)
Hello, world!

@ Main.msg
res4: String = "Hello, world!"
```
