### ISSUE TITLE
Check if usage mapValues is sensible

### ISSUE THREAD

**Issue by yilinwei** [functional-streams-for-scala/fs2#705]
We recently had an issue with our own code where `mapValues` caused degrading performance over time due to the fact that `mapValues` isn't [eager](http://stackoverflow.com/questions/25450887/scala-map-mapvalues-stackoverflowerror) where we used a `Map` as a accumulation on `Stream`.

The only usage of `mapValues` in the codebase is [here](https://github.com/functional-streams-for-scala/fs2/blob/53037409e7225193bfebba30881ae02b8acc7894/core/shared/src/main/scala/fs2/internal/LinkedMap.scala). I'm not too familiar with the usage of `LinkedMap` here, so I can't say whether it looks sensible or not at first glance.

**Comment by mpilquist** [comment]
Thanks -- I opened #706 to remove this method. It wasn't called from anywhere.
