### ISSUE TITLE
Decide how empty chunks are handled

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#708]
Currently, empty chunks are elided by the `StreamCore` interpreter. As a result, I believe that an empty chunk will never be passed to `await`, which makes the various non-empty variants of `await` and `receive` redundant.

Assuming I'm right in this belief, I think we should do one of the following:
1. Remove the non-empty variants of `await` and `receive`
2. Remove the elision of empty chunks from `StreamCore`

Alternatively, can anyone come up with an example where empty chunks would get passed to an `h.await` in the current implementation?

I'm going to release RC1 anyway - we can remove the non-empty variants in RC2 or final.

**Comment by mpilquist** [comment]
@pchiusano Any thoughts on this?

**Comment by pchiusano** [comment]
I'm cool with removing the nonEmpty variants for now. I wouldn't start emitting empty chunks in StreamCore as that might have performance or even productivity implications.

Something I've thought about is encoding at the type level the information about whether a chunk is possibly empty. Straw man:

```Scala
trait Chunk[+A] { 
  def uncons: Option[(A, Chunk[A])]
  def toNonEmpty: Option[NonEmptyChunk[A]]
  ...
}

trait NonEmptyChunk[+A] extends Chunk[A] { 
   def unconsNonEmpty: (A, Chunk[A]) // no Option here, notice
   ...
}
```

Then the nonemptiness of the various pull operations is reflected in the types, and the scala compiler will enforce that the interpreter is indeed constructing nonempty chunks everywhere.

I'm not sure how well this would work out. It might complicate a lot of signatures. If going to try it, my feeling would be don't try to preserve the property across lots of code. Basically just the various await functions would return `NonEmptyChunk`, everything else would just assume `Chunk`. So it's more useful when writing a `Pull`, so you don't have to handle the `None` case.

I think for now, I would just get rid of the nonEmpty versions and then possibly experiment with re-adding them with better types later.

In practice what this means is that @mpilquist will have it done tomorrow, haha.
