### ISSUE TITLE
FlatMap evaluation shall be lazy

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#712]
Current flatMap implementation is essentially eager on chunking so it essentially works internally as map on chunk `A => Stream[F.B]` before the Stream is evaluated (first the chunk is iterated for chunk of streams, then chunks are evaluated). Essentially internally this works like `Chunk[A] => Chunk[Stream[F,B]]`

Instead my belief is that `f` in flatMap has to be evaluated once the `A` is really processed (lazy). Current implementation will cause performance to be downgraded when `f` is expensive to compute and user perhaps only care about subset of the chunk used as input. i.e. 
```scala

val source: Stream[F,A] = chunkOf10k
def expensiveComputation: A => Stream[B] = ???

// we only need 10 of items, but we had to evaluate 10k to produce these 10. 
// take10 may be for example takeWhile or anything dependable on `B` values computed
source.flatMap(expensiveComputation).take(10)

```

Therefore I would suggest to change internal evaluation of flatMap as Chunk[A] => Chunk[Suspend[Stream[A]] if possible. 

@pchiusano @mpilquist  any comments on that?

**Comment by mpilquist** [comment]
@pchlupacek One thing to note is that you can do this already:

```scala
val source: Stream[F,A] = chunkOf10k
def expensiveComputation: A => Stream[B] = ???
source.flatMap(a => Stream.suspend(expensiveComputation)).take(10
```

This has the semantics you want. I think the current behavior is the right tradeoff, because suspending on every element of the input is very expensive in its own right.

**Comment by pchiusano** [comment]
Agree with Mike on this one, just use suspend if you want the function to
be cheap. You can also unchunk the stream before calling flatMap with
similar effects.

**Comment by pchlupacek** [comment]
@mpilquist @pchiusano I am ok with explicit suspend definition. You think that lazy by default will have that much negative performance impact? We do anyhow boxing to Stream in flatMap, so why would Suspend be so much an issue?

**Comment by mpilquist** [comment]
In general, the performance of FS2 is limited by the overhead of the trampoline. The more work we can do on each bounce, the faster we execute. By forcing a suspend on each element, we end up bouncing much more frequently. Or at least that's my theory / vague fear of making such a change. :)

**Comment by pchlupacek** [comment]
@mpilquist was just curious hence we have that new Suspend stuff you have been working on if that will still be issue. But ok, lets close this as there are reasonable workarounds and we'll see going onward if this will have some ground to discuss it further.
