### ISSUE TITLE
How to ScalaDoc built-in pipes

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#726]
Does anyone have any opinions on how we should add ScalaDoc comments to the built-in pipes? Specifically, the ones that are defined in `pipe` and `pipe2` and also have aliases defined directly on `Stream`. Right now, we add docs to the implementations in the objects and then we add a comment on forwarder that links to the definition.

Example: https://oss.sonatype.org/service/local/repositories/releases/archive/co/fs2/fs2-core_2.12.0-M5/0.9.0-RC2/fs2-core_2.12.0-M5-0.9.0-RC2-javadoc.jar/!/fs2/Stream.html#chunkLimit(n:Int):fs2.Stream[F,fs2.NonEmptyChunk[O]]

I'm wondering if we should reverse this -- i.e., the forwarders would get the full documentation and the pipes in `pipe` and `pipe2` would get a comment along the lines of `Implementation of [[Stream.chunkLimit]].`.

**Comment by pchiusano** [comment]
No strong feelings but kind of prefer it as is, especially since there's a
link you can follow easily. It also emphasizes that the provided functions
aren't magic - they are just sugar for piping through various transducers,
which you could do yourself if you write new transducers.

**Comment by mpilquist** [comment]
Sounds good.
