### ISSUE TITLE
Add + publish laws for FS2 type classes

### ISSUE THREAD

**Issue by adelbertc** [functional-streams-for-scala/fs2#750]
Since FS2 allows users to plug in their own effects via the `Async` and related type classes it would be helpful to have laws to test implementations to make sure things behave as expected.

**Comment by mpilquist** [comment]
I think we should specify the laws of the type classes that are unique to FS2 -- `Catchable`, `Suspendable`, `Effect`, and `Async`. At a minimum, those laws should be in ScalaDoc.

I'm not sure we should mechanize the laws in to code. That's a bit of a rabbit hole that leads to test frameworks, equality type classes, etc. Plus, I feel that is more the territory of Scalaz and Cats than FS2. Just my 2 cents though. Happy to hear other opinions.

**Comment by adelbertc** [comment]
That's fair I think, with the addendum that FS2 encodes the laws in its own
tests showing that Task passes, as a sort of reference implementation.

**Comment by mpilquist** [comment]
Closing since FS2 no longer defines any type classes.
