### ISSUE TITLE
Scala 2.12.0 support/release to Maven

### ISSUE THREAD

**Issue by ScalaWilliam** [functional-streams-for-scala/fs2#757]

**Comment by mpilquist** [comment]
Waiting on ScalaCheck and ScalaTest currently. I'll publish as soon as they are up. :)

**Comment by xuwei-k** [comment]
- https://oss.sonatype.org/content/repositories/releases/org/scalacheck/scalacheck_2.12/
- https://oss.sonatype.org/content/repositories/releases/org/scalatest/scalatest_2.12/

**Comment by mpilquist** [comment]
FS2 0.9.2 and FS2-Scalaz 0.2.0 are published now. :)
