### ISSUE TITLE
concurrent.join deletes backpressure

### ISSUE THREAD

**Issue by djspiewak** [functional-streams-for-scala/fs2#762]
`join` provides a `maxOpen` parameter, but not a `limit` on the number of elements (or at the very least, chunks) which may be outstanding.  The result is a function which actually removes any backpressure from the constituent streams.  If the output stream is slow to process, the input streams will continue unaffected due to the unbounded queue(s) involved.

**Comment by mpilquist** [comment]
@djspiewak Can you elaborate more? `join` uses a synchronous queue -- an exchanger -- such that there's never more than 1 outstanding enqueue from each inner stream.

**Comment by djspiewak** [comment]
@mpilquist Maybe I simply misunderstood the underlying code…  So you're saying that [outputQueue](https://github.com/functional-streams-for-scala/fs2/blob/cc641da92977c15519c853ee9a749bbb7fe97dc4/core/shared/src/main/scala/fs2/concurrent.scala#L84) is effectively functioning as a size 1 queue?

**Comment by mpilquist** [comment]
Yeah -- the trick is that `enqueue1` decrements a semaphore that's initialized to 1 but *doesn't* increment it. The increment is only down on a corresponding dequeue.

**Comment by mpilquist** [comment]
Correction: semaphore is initialized to 0 so the first enqueue blocks until something attempts to dequeue.

**Comment by djspiewak** [comment]
Yeah, found that now.  Was also just about to mention the same correction.  So effectively what's happening here is that streams cannot "run ahead" under any circumstances?  Each of them has an outstanding interpreter that is running in magic fork land (via `start`), but only a single chunk may be enqueued at once.

That definitely preserves backpressure (contrary to my perhaps-hasty bug report), though it doesn't manage fairness very well.  Is that functionality in `Semaphore`?

**Comment by mpilquist** [comment]
That sounds right to me -- could always add run-ahead by sticking a bounded queue on the output side of `concurrent.join` or perhaps using one of the buffering combinators like `prefetch`.

Looks like `Semaphore` unblocks decrements in FIFO order (though I only looked briefly).

**Comment by djspiewak** [comment]
Yeah I was just looking at that as well.  It is entirely round-robin in the one-decrement case.  I'll close this report.  Sorry for the noise.

**Comment by mpilquist** [comment]
No problem -- glad you are looking! :)
