### ISSUE TITLE
Suggestion: Async.set shall be sequential by default

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#782]
Even when this is noted correctly in documentation (asynchronous behaviour of set), I would suggest rename the current asynchronous set to be setAsync to explicitly note that the set is asynchronous and not sequential and spawn to another thread. 

When writing programs using the ref, the behaviour of set leads to not easily trackable race conditions, and I would trade performance gains here for correctness and safety. 

@pchiusano @mpilquist any thoughts?

**Comment by djspiewak** [comment]
I don't really have a horse in this game, but it's worth noting that the current behavior of `set` violates its only law: `r.set(t) flatMap { _ => r.get } == t`.  If the async `set` runs slowly enough, this identity does not hold beyond the first `set`.

**Comment by pchlupacek** [comment]
@djspiewak agree. This is another reason why we should rename it to async. I think based on your comment we shall not perhaps guarantee any laws of the setAsync

**Comment by mpilquist** [comment]
No strong opinions on the name. I have made the mistake of forgetting `set` is async before. It's inconsistent with `set` on `Signal` too. If we were to make a change, I'd say rename `set` to `setAsync` and then separately consider whether there's a need for a synchronous `set`.

**Comment by pchlupacek** [comment]
@mpilquist  thanks. Agree.
I would like to stay behind synchronous set, as I think this shall be the default.
