### ISSUE TITLE
Bounded/Unbounded queues behaviour

### ISSUE THREAD

**Issue by clayrat** [functional-streams-for-scala/fs2#788]
I have a pipelined app where I want to parallelize each step (which has a blocking call) via `njoin` and connect these with queues. Here's a simplified version:

https://gist.github.com/clayrat/14803205242e142f1475eb364c99ec1d

If you replace the line 12 with an `unboundedQueue`, everything works as expected, and the stages seem to run in parallel. However if you run this with a bounded queue (like now), the consumers seem to be sequential - the next one starts to work strictly after the previous one is finished. This doesn't seem to depend on the queue size.

Also if you uncomment the `watchSize` parts, with unbounded queues you get the queue sizes in the output, whereas there's none with `boundedQueue`.

**Comment by pchlupacek** [comment]
@clayrat not sure on status of this. Are you experiencing this still with 0.10 series?

**Comment by clayrat** [comment]
Hey, I haven't done anything with fs2 since, since the behaviour described above was a showstopper for me. I can try again some time soon with 0.10.

**Comment by pchlupacek** [comment]
ok I gonna close this for now, and lets talk about this when you will have chance to try with newer releases.

**Comment by clayrat** [comment]
Ok, this seems to no longer manifest in 0.10.6, thanks!
