### ISSUE TITLE
RFC: 1.0.0-M1 build

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#796]
Any objections to a 1.0.0-M1 build?

The current 1.0.0 snapshot build is significantly faster than 0.9 for many workloads (see https://github.com/rossabaker/benchmarks/tree/master/results for details).

I'd like to publish a stable version of this for folks to experiment with. Usual caveats on milestones apply -- no guarantees of any kind with respect to source or binary compatibility.

Longer term, I'd like to start thinking about what all we want to get in to 1.0.0. Theme wise, 1.0.0 is focused on increasing runtime performance of the 0.9 API. We can make selective API changes as necessary but I'd like the overall API to remain the same -- certainly nothing like the 0.8 -> 0.9 change. :)

**Comment by pchlupacek** [comment]
Are we 100% sure there will be no drastic changes to internals related to performance? If yes, lets do it if not, I would rather do 0.10.0-M1 :-)

**Comment by mpilquist** [comment]
My gut feeling is that the well-trodden parts of the API will remain relatively unchanged (modulo very minor things). Less frequently used parts of the API might need some minor changes -- e.g., changing some of the concurrency primitives. Internals may/will be drastically different -- `StreamCore` could be rewritten perhaps (we got it right, now we need to get it fast), `StreamCore` could be elided in favor of putting everything in the `Pull` algebra and optimizing the interpreter, etc.

**Comment by pchlupacek** [comment]
Ok, lets say if we leave Pull as is then lets do 1.0

**Comment by pchiusano** [comment]
👍
