### ISSUE TITLE
performance of this match vs polymorphic dispatch

### ISSUE THREAD

**Issue by fommil** [functional-streams-for-scala/fs2#819]
I was just looking at the impl of `Task` and seen that you use `this match` to implement dynamic dispatch of methods.

Conceptually this is nice if it is important to see all the impls together, but is there a performance overhead? The JVM is very fast at polymorphic dispatch, how does it compare to an `isInstanceOf` call? (or is the JIT smart enough to optimise this away)

**Comment by mpilquist** [comment]
@fommil We've tried both in various benchmarks and haven't seen an appreciable difference. I think @non did some explicit micro benchmarking of match vs polymorphic dispatch in Cats and found the results surprising. Before those results, I had assumed polymorphic dispatch would always beat a pattern match, but that wasn't the case.

**Comment by fommil** [comment]
That's extremely interesting and could guide how I write similar code. I look forward to seeing what @non has come up with!

FYI (and now I'm going totally off-topic) I am moving on from my current role in about a month and I'm taking a real close look at cats and fs2 as I hope to use it as the base for my next gig. For now, my main interest in FS2 is to help me convert this simple business logic into something that takes the `ddd` in https://github.com/fommil/drone-dynamic-agents/blob/master/src/main/scala/logic.scala as push input (e.g. over websockets) rather than pull input. I would need some way of managing my view of the state of the world, and some way to initially build up that state, plus all the business-layer error handling surrounding it. Are there any examples that take a Free monad style computation and rewrite it to be async? Or is this more like taking something Pull and writing it to be "push"?

I also want to create a `@data` co-simulacrum to allow for highly optimised JVM representations of data types (and severely limit what can be written in a class, for KISS). I'll probably ping you about that at some point. e.g. imagine the ability to memoize the construction of instances, with reference based equality, and de-boxing of Option in the heap representation... in the extreme case something like FastInfoSet planned to do for XML (going so far as using a corpus of data to provide a compression dictionary for fields). I plan to implement it with scala.meta, although I have the beginnings of a scala compiler implementation.

**Comment by fommil** [comment]
Btw, this *does*  have a performance overhead. However, check out 47 degrees iota for a way to make that go away, and stalagmite for a way to get that perf everywhere ;-)

**Comment by mpilquist** [comment]
In general I agree. I wasn't able to come up with a benchmark that showed the difference with `Task` though. `Task` is gone now but maybe `FreeC` could benefit from polymorphic dispatch instead of pattern matches.

**Comment by fommil** [comment]
You don't need polymorphic dispatch, when you can have `@switch` ;-)
