### ISSUE TITLE
Timed API for Queue 

### ISSUE THREAD

**Issue by 13h3r** [functional-streams-for-scala/fs2#829]
It will be nice to have timeouts in API for `Queue`. 

```scala
val q: Queue[Task, Int] = ???
val result = q.enqueue1(1, 1 second)
```

If last statement will fail to enqueue for one second then result fails and no element will be enqueued. 

Same extension may be applicable for `dequeue1`.

WDYT?

**Comment by pchlupacek** [comment]
Just a quick remark the actual `enqueue` operation cannot really timeout (at least I don't see how). Its source of the data that may not be available for enq. operation, so I am not sure if the signature proposed is valid.

**Comment by pchlupacek** [comment]
Obviously it may timeout if queue has bounds, its what you have in mind?

**Comment by 13h3r** [comment]
> Just a quick remark the actual enqueue operation cannot really timeout (at least I don't see how)

Yes, I am talking about `enqueue1`, `dequeue1` and `offer1`. 

> Obviously it may timeout if queue has bounds, its what you have in mind?

Yes

**Comment by mpilquist** [comment]
Addressed in #924 via addition of `timedEnqueue1` and `timedDequeue1`.

**Comment by dmgcodevil** [comment]
where is this code ? can't find timed methods in `fs2.concurrent.Enqueue`

**Comment by mpilquist** [comment]
@dmgcodevil Use `q.enqueue1(a).timeout(duration)`

**Comment by dmgcodevil** [comment]
@mpilquist  if you talking about `IO.timeout` then it doesn't  guarantee that the element wont added  if `enqueue1` timed  out. take a look at the code below:

```scala
object RaceSpec extends IOApp {

  val counter = new AtomicInteger()

  val inc1 = IO.sleep(100.millis) >> IO(counter.incrementAndGet())
  val inc2 = IO.sleep(100.millis) >> IO(counter.incrementAndGet())

  val n = 100

  override def run(args: List[String]): IO[ExitCode] = {

    (0 until n).map(_ => IO.race(inc1, inc2)).toList.sequence_ >> IO(println(counter.get)) >> IO(ExitCode.Success)

  }

}
```

prints to the console: `168`

cats-effect  contributors saying that:

> so you might have a different printed value every time, but from looking at the code I reckon it'll always be between 100 and 200
> because sometimes both IOs will complete at around the same time and cancelation won't hit either

> because the race might cancel the loser after incrementAndGet executes

**Comment by SystemFw** [comment]
I replied on the newer issue, let's keep the discussion there
