### ISSUE TITLE
Debounce

### ISSUE THREAD

**Issue by yilinwei** [functional-streams-for-scala/fs2#832]
It would be useful to have some way to debounce a stream.

I think it ought to be a variant of a `Signal` rather than on the `Stream` itself.

**Comment by mpilquist** [comment]
@yilinwei Could you elaborate a little on expected behavior?

**Comment by yilinwei** [comment]
Yes.

fs2 currently has several tools when working across stream boundaries, `Signal` and `Queue`. However, it's a relatively common use case that you want to throttle the amount the updates to a reasonable rate. Adding extra facilities utility functions for that would be quite useful.

The marble diagram for [debounce](http://reactivex.io/documentation/operators/debounce.html) shows best.

Ideally, it would a a `Signal` which you would set and when calling `.discrete` debounced the updates.

**Comment by zainab-ali** [comment]
The marble diagram seems to describe the following:

Let's say you have a `Stream[F, A]` and a debounce period `dt`.
If `a1` arrives at `t1` and no events arrive over `t1 + dt`, emit `a1`
If `a1` arrives at `t1` and `a2` arrives at `t2`, such that `t2 - t1 < dt`, ignore `a1`.

You could have a custom pipe which pulls from `Stream[F, A]`.  
 - On receiving an `a`, create an `F[Unit]` which emits after `dt`.
 - `awaitAsync` on the next handle and race the resulting future with `F[Unit]`.
 - If `F[Unit]` finishes first, emit `a` and repeat
 - If the next handle finishes first, create another `F[Unit]` and race again

I'm not sure if this is a good approach - it would be worth getting feedback on it.

**Comment by yilinwei** [comment]
I'll give that approach a go next week and see how it's performance is.

**Comment by yilinwei** [comment]
@zainab-ali  `race` is only on the `Task` and relies on `setRace` of the `Ref` of the task.

@mpilquist could it be moved to an arbitrary `Async[F]`? It doesn't seem a good idea to require people to implement it.

**Comment by mpilquist** [comment]
Can we implement in terms of `merge` and `time.sleep` instead?

**Comment by yilinwei** [comment]
I think so,

something like,

`time.sleep[Task](1 second).map(Left(_)).merge(Stream.eval(fa.map(Right(_)))).head`

should be technically the same as a race I think.

**Comment by yilinwei** [comment]
Addressedin #861
