### ISSUE TITLE
[Help request] Migrating some code from scalaz-streams

### ISSUE THREAD

**Issue by Daenyth** [functional-streams-for-scala/fs2#863]
I was trying to migrate https://github.com/runarorama/ircz to fs2 streams to familiarize myself with the library and how to structure an application with it, since I have a fairly similar problem to that snippet.

My modifications are here: https://github.com/runarorama/ircz/compare/master...Daenyth:master

It runs, but when I `runMain Client` with my version, I get a "Connection Refused" error, while the original version works and serves responses.

I'm not sure exactly where I went wrong, and I'd appreciate some guidance since I haven't been able to figure it out with any fs2 documentation I've read.

**Comment by Daenyth** [comment]
So far I've also tried
- Removing `Stream.bracket` and using the same `onError` pattern of signal removal as the original scalaz-streams example
- Making a second separate executor for `AsynchronousChannelGroup` instead of reusing the Strategy pool.
- Changing `concurrent.join(n)(connections map ..` to `connections flatMap ..`

Still no luck so far. When I add a `.through(log("x"))` to the `tcp.server` stream, I never see that log (using the `log` from one of the tutorials around). Likewise putting `connections map { client => println("x"); ... }` I don't see the line.

The server side sits there running but it doesn't seem that it's bound a socket at all.

**Comment by Daenyth** [comment]
My problem was that I had

```scala
  val mainTask: Task[Unit] =
    for {
      mq <- messageQueueT
      clientSignal <- clientsT
    } yield mainStream(mq, clientSignal).run
```

when I needed
```scala
  val mainTask: Task[Unit] =
    for {
      mq <- messageQueueT
      clientSignal <- clientsT
      stream <- mainStream(mq, clientSignal).run
    } yield stream
```

The reason that it compiled was because I had warnings turned off. When I added my usual set of compiler warnings, the old code gives me:
```
[error] /Users/daenyth/Code/ircz/src/main/scala/Server.scala:93: discarded non-Unit value
[error]     } yield mainStream(mq, clientSignal).run
[error]                                          ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```

So it was actually a `Task[Task[Unit]]` that I was running - and then just discarding the resulting task.

**Comment by Daenyth** [comment]
OK, so I've still done something wrong - the clients can connect, but nothing they send through gets sent to the other clients

**Comment by Daenyth** [comment]
It seems like I do get the output, once, but only once the client has sent as many bytes as `reads` was asking for. Though, I tried setting it lower - to `maxBytes=1` and then I didn't seem to get anything.

**Comment by mpilquist** [comment]
@Daenyth Did you get this working?

**Comment by Daenyth** [comment]
No, I wasn't able to get it working and haven't had time to keep looking at it yet. If you have pointers I'd appreciate it.

**Comment by Daenyth** [comment]
I suspect now that I have more production experience under my belt, I'll be able to resolve this down the line when I come back to it.
