### ISSUE TITLE
Make Pipe into a newtype and add instances

### ISSUE THREAD

**Issue by SystemFw** [functional-streams-for-scala/fs2#870]
Hello :) 

Currently `Pipe` is defined as:
```scala
type Pipe[F[_],-I,+O] = Stream[F,I] => Stream[F,O]
```
This is very simple to use, but suffers from a few limitations when designing Stream topologies.
Although you can always use `flatMap` to design arbitrary topologies, there are a lot of cases of static graphs that only require the power of `Arrow` (rather than `Monad`) to define. 

The `Pipe[F,A,B]` type seems like a perfect fit to implement `Arrow` and\or the `Profunctor` hierarchy, but trying to use the functions defined in those typeclasses directly will not give the expected result, because the instances for `=>` will be selected. 

Example: having a `Stream[F,(A,B)]` through a `Pipe[F,A,C]` seems like a good fit for `first` (from `Strong`), and having `myPipe.first` will compile, but return a `(Stream[F,A], B) => (Stream[F,C],B)` rather than the expected `Stream[F,(A,B)] => Stream[F,(C,B)]`. The same happens for most of the other operations (`split`, `second`, and so on).

Given that fs2 1.0 will depend on cats, I propose we take advantage of the instances we can define for `Pipe`, by making it into a newtype, or making a newtype for it. I'm also up for doing the necessary work, should it be required/deemed useful.

**Comment by pchiusano** [comment]
Very unlikely we'll go in this direction. Also, something you will run into
with trying to make some sort of arrow is what to do about two streams that
produce data at totally different rates.

There are some known issues with making pipe an opaque stream function, but
overall it's a nice simple choice. It might be interesting to play with
other representations that compile down to pipe or stream. If you end up
doing this and come up with anything cool let us know.

**Comment by SystemFw** [comment]
Thanks for the quick response @pchiusano!

A couple comments (not for the sake of reopening it, just interested in your thoughts) :

- Opaque vs type synonym representation: this is a crucial bit of the library so I understand wanting to keep the representation as is, but what do you think about adding a few functions as extensions to `Pipe` (e.g. first?)
- I'm not sure I get the point about two different `Streams`. I'm proposing to make `Pipe` into an `Arrow` in such a way that it'll work on `Stream` of tuples, rather than tuple of `Stream` (very poorly worded in the original issue upon rereading, since I mention topologies)

**Comment by yilinwei** [comment]
I'm not entirely certain that I follow this conversation.

If I recall correctly a newtype is simply a wrapper around a type which selects a different valid typeclass instance.

In this particular case, our newtype would be,

```
  case class Pipe[F[_], I, O](value: Stream[F, I] => Stream[F, O])
```

In which case, we should be able to do things like,

```
implicit def fs2PipeOutputFunctor[F, I]: Functor[Pipe[F, I, ?]] = ...
implicit def fs2PipeInputContravariant[F, O]: Contravariant[Pipe[F, ?, O]] = ...
```

without conflicting with the function typeclass instances. I'm not entirely certain why any of the operations would cause any more problems than the current pipes work currently?

**Comment by kryptt** [comment]
I don't see too much conflict with : 
```
  implicit def fs2PipeArrow[F[_]] = new Arrow[Pipe[F, ?, ?]] {
    override def id[A] = identity
    override def dimap[A, B, C, D](p: Pipe[F, A, B])(f: C => A)(g: B => D): Pipe[F, C, D] = _.map(f).through(p).map(g)
    override def lmap[A, B, C](p: Pipe[F, A, B])(f: C => A): Pipe[F, C, B] = _.map(f).through(p)
    override def rmap[A, B, D](p: Pipe[F, A, B])(g: B => D): Pipe[F, A, D] = _.through(p).map(g)
    def lift[A, B](f: A => B): Pipe[F, A, B] = _.map(f)
    def compose[A, B, C](f: Pipe[F, B, C], g: Pipe[F, A, B]): Pipe[F, A, C] = _.through(g).through(f)
    def first[A, B, C](fa: Pipe[F, A, B]): Pipe[F, (A, C), (B, C)] = _.flatMap {
      case (a, c) => Stream.emit(a).covary[F].through(fa).map((_, c))
    }
    override def second[A, B, C](fa: Pipe[F, A, B]): Pipe[F, (C, A), (C, B)] = _.flatMap {
      case (c, a) => Stream.emit(a).covary[F].through(fa).map((c, _))
    }
  }
```
Each method reads idiomatic and correct..

**Comment by lJoublanc** [comment]
@SystemFw Is it worth revisiting this?

> Example: having a Stream[F,(A,B)] through a Pipe[F,A,C] seems like a good fit for first (from Strong), and having myPipe.first will compile, but return a (Stream[F,A], B) => (Stream[F,C],B) rather than the expected Stream[F,(A,B)] => Stream[F,(C,B)]. The same happens for most of the other operations (split, second, and so on).

This doesn't seem to be the case on v1.0.0 with cats-core 1.4.0. I would only expect the `Arrow[Function1]` instance to be picked up if it is explicitly in scope i.e. `import cats.instances.function1._`.

For instance:

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

import cats.arrow.Arrow
import fs2._
import cats.syntax.all._

implicit def arrowInstance[F[_]] = new Arrow[({ type S[a,b] = Pipe[F,a,b] })#S] {
  def lift[A, B](f: A => B): Pipe[F,A,B] =
    _ map f

  def compose[A, B, C](f: Pipe[F,B,C],g: Pipe[F,A,B]): Pipe[F,A,C] =
    s => f(g(s))

  def first[A, B, C](fa: Pipe[F,A,B]): Pipe[F,(A, C),(B, C)] =
    _ flatMap { case (a,c) => fa(Stream[F,A](a)) map (_ -> c) }
}

type P[a,b] = Pipe[Pure,a,b]

val x = Stream range (42,54)

val y = x map (_.toChar)

val triple = Arrow[P] lift { (_ : Int) * 3 }

val addTwo = Arrow[P] lift { (_ : Int) + 2 }

val f = (triple >>> addTwo).first[Char]

(x zip y) through f toVector

// Exiting paste mode, now interpreting.

import cats.arrow.Arrow
import fs2._
import cats.syntax.all._
arrowInstance: [F[_]]=> cats.arrow.Arrow[[a, b]fs2.Stream[F,a] => fs2.Stream[F,b]]
defined type alias P
x: fs2.Stream[[x]fs2.Pure[x],Int] = Stream(..)
y: fs2.Stream[[x]fs2.Pure[x],Char] = Stream(..)
triple: P[Int,Int] = $anon$1$$Lambda$11694/1077813928@36779b87
addTwo: P[Int,Int] = $anon$1$$Lambda$11694/1077813928@1959ec8b
f: P[(Int, Char),(Int, Char)] = $anon$1$$Lambda$11697/134537394@55c85ab0
res0: Vector[(Int, Char)] = Vector((128,*), (131,+), (134,,), (137,-), (140,.), (143,/), (
146,0), (149,1), (152,2), (155,3), (158,4), (161,5))
```
