### ISSUE TITLE
Param of onFinalize clould be non-strict

### ISSUE THREAD

**Issue by jilen** [functional-streams-for-scala/fs2#871]
For currently version
```scala
def onFinalize(f: F[Unit])
```

It is impossible to use  Effect like scala `Future` .

Because it will eval immediately after create. 

And had to use `Stream.bracket` instead

**Comment by mpilquist** [comment]
You could do something like `onFinalize(F.suspend(f))` where `F: Suspend[F]` for effect type `F[_]`.

Are you using `scala.concurrent.Future` as the effect type? Any reason to use `Future` over `Task` or `IO`?

**Comment by jilen** [comment]
@mpilquist Actually  our stack are based on scala `Future`(Play! Framework), 
Maybe I shall use `Task` and convert it to `Future` at last.

**Comment by djspiewak** [comment]
Note that `Future` does not have a lawful `Sync` instance, so you're already in a situation where it is impossible to use it with fs2.  I would definitely recommend using `IO` or `Task` (or really any other lawful `Sync`).

**Comment by jilen** [comment]
@djspiewak  I agree, the standard `Future` is very problematic while working with fp library.
