### ISSUE TITLE
Race condition failing outer stream in concurrent.join

### ISSUE THREAD

**Issue by fiadliel** [functional-streams-for-scala/fs2#876]
It seems like there is a race condition in `concurrent.join`:

if `runOuter` fails, then `decrementRunning` is called before enqueuing `Some(Left(failure))`. This will race (and maybe lose) against `doneMonitor` which will enqueue `None`.

As a result, a failure of the outer stream may not be detected.

@mpilquist WDYT?

**Comment by pchlupacek** [comment]
@filadel you on 0.9.6 right?

**Comment by fiadliel** [comment]
Yes, it's 0.9.6.

The current code is:
```scala
def runOuter: F[Unit] = {
  (outer.interruptWhen(killSignal) flatMap runInner onFinalize decrementRunning run).attempt flatMap {
    case Right(_) => F.pure(())
    case Left(err) => outputQ.enqueue1(Some(Left(err)))
  }
}
```

I think the issue is that `decrementRunning` is called before the enqueue. My first thought was something like this, but I don't think it's necessarily safe (e.g. `imap` on `Queue` could throw an exception):

```scala
def runOuter: F[Unit] = {
  (outer.interruptWhen(killSignal) flatMap runInner run).attempt flatMap {
    case Right(_) => F.pure(())
    case Left(err) => outputQ.enqueue1(Some(Left(err)))
  } flatMap { _ => decrementRunning }
}
```

**Comment by pchlupacek** [comment]
@fiadliel you are right. I think I know how to fix this. Thanks for diagnosing it.

**Comment by mpilquist** [comment]
@fiadliel Would you mind trying 0.9.0-SNAPSHOT now that #880 has been merged?

**Comment by kalak451** [comment]
This: https://gist.github.com/kalak451/58701a62dc360984de719e8642c934ec  used to fail ~80% of the time in 0.9.6,  with a local build of 0.9.7-SNAPSHOT I can no longer get it to fail.

**Comment by mpilquist** [comment]
@kalak451 Awesome, thanks very much for testing!
