### ISSUE TITLE
Monad for Pull

### ISSUE THREAD

**Issue by djspiewak** [functional-streams-for-scala/fs2#877]
If `Pull` forms a `Monad`, then there should exist a `[F[_], A]Monad[Pull[F, ?, A]]` instance, so that we can abstract over it.  On a related note, it would be a lot better if the second and third type parameters were reversed, since it would then be amenable to `-Ypartial-unification`.

**Comment by mpilquist** [comment]
Pull forms a monad in R so param order is correct. Agree that there should be a Monad instance - lack of one is an oversight.

**Comment by djspiewak** [comment]
Ooooooh, you're right. Reading the `flatMap` signature was hard. :-/

**Comment by mpilquist** [comment]
0.11's signature is so much nicer -- no type-computed lubbing to obfuscate things :)

**Comment by mpilquist** [comment]
Fixed in the 0.10 backport PR: 605f419356e68ac9bf75eb0c60996fdc0a26ee8a

**Comment by mpilquist** [comment]
Closing since this is fixed -- note that the `Sync` instances for `Stream` and `Pull` are not implicit to avoid syntax conflicts.
