### ISSUE TITLE
wrong inferred type

### ISSUE THREAD

**Issue by oskoi** [functional-streams-for-scala/fs2#884]
```
@ val s0 = Stream.empty 
s0: Stream[Nothing, Nothing] = Segment(Emit(Chunk()))
```
but in guide
```
val s0 = Stream.empty
s0: fs2.Stream[fs2.Pure,Nothing] = Stream(..)
```
Is this a bug or feature? :)

**Comment by mpilquist** [comment]
Looks like you're using FS2 0.9.x but reading the guide for 0.10.x. Find the 0.9 guide here: https://github.com/functional-streams-for-scala/fs2/blob/series/0.9/docs/guide.md

**Comment by oskoi** [comment]
You're right. In README there is a reference to the last guide. Sorry)

**Comment by oskoi** [comment]
Thanks!
