### ISSUE TITLE
Future in Stream makes app never terminate

### ISSUE THREAD

**Issue by visox** [functional-streams-for-scala/fs2#894]
Hi,

i am using fs2 streams and it all works fine but at some point i need to make a call to database where i have to deal with a future (slick).

I made a plain example:

```
import java.util.concurrent.Executors
import fs2._
import scala.concurrent.{Future, ExecutionContext}

object TestApp2 extends App {
  implicit val strategy: Strategy = Strategy.fromFixedDaemonPool(3)
  implicit val ec: ExecutionContext = ExecutionContext.fromExecutor(Executors.newFixedThreadPool(3))

  val stream: Stream[Task, Int] =
    Stream.emits[Task, Int](Seq(1, 2, 3, 4, 5))
    .flatMap{num =>
      val fut = Future{
        num * 2
      }

      val task = Task.fromFuture(fut)

      Stream.eval(task)
    }

  val executed = stream.runLog.unsafeRun()

  println(executed)
  println("done")
}
```
The program prints out the result as expected but never terminates, like this:
https://ibb.co/e4XGpa

I did run java visualVM, but i am not sure if it has any usefull info:
https://ibb.co/ieGWNv

sbt stuff:
```
val scalaV = "2.12.2"
"co.fs2" %% "fs2-core" % "0.9.7"
```

Of course i can terminate the program by hand but that is not a solution.
What i am missing, what is the problem ?

also:

```
//works (terminates)
//      val fut = Future{
//        num * 2
//      }

val task = Task.now(num * 2)
```

```
//does not terminate
      val fut = Future{
        num * 2
      }

val task = Task.now(num * 2)
```

```
//does not terminate
//      val fut = Future{
//        num * 2
//      }

val task = Task.fromFuture(Future.successful(num * 2))
```

Thanks upfront for any help/suggestion

**Comment by mpilquist** [comment]
Just a guess but I think the ExecutionContext is keeping the JVM running because it is creating 3 non-daemon threads. Try either manually terminating the ExecutorService backing the ExecutionContext or using a thread factory that calls setDaemon(true).

**Comment by visox** [comment]
Thx a lot, it works!
Maybe this should be in some docs, i wasted quite some time :D

**Comment by mpilquist** [comment]
No problem. One thing I noticed - wrap the creation of the Future with Task.fromFuture instead of assigning the future to a val first. Alternatively, define the fut val as a lazy val. General idea is that kicking off a future is not pure so it should be controlled/managed by a Task wrapper.

**Comment by visox** [comment]
Yes for sure, i just wanted to have one line == one thing in my minimalistic example
