### ISSUE TITLE
Laws for nondeterministic combinators

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#911]
Currently we have few non deterministic operators in fs2
 - `pipe2`, i.e. merge, either ...
 - `join`

It seems that behaviour of these combinators subtle changed from 0.9 to 0.10 release that may cause some programs to compile under 0.10 but not work properly. Furthermore, there is difference now in 0.9 and 0.10 how `join(Stream(streamA1, streamA2))` works and how `streamA1 merge streamA2` will work (specifically for drained streams) 

I would like in this thread to settle on laws for these combinators. My ideas for the laws would be in areas: 

- how drained streams (ones that produce no values) are run
- if either of the streams fails, how that affects downstream 

@mpilquist @djspiewak @SystemFw @pchiusano @AdamChlupacek can you please share some thoughts here? 

This is continuation of discussion in #907

**Comment by mpilquist** [comment]
@pchlupacek Could you describe the differences in error propagation between `merge` and `join`? I'm aware of the differences in drained stream handling.

**Comment by pchlupacek** [comment]
@mpilquist lets say have these programs: 

```scala

val streamA: Stream[F, Int] = Stream.range(0, Int.MaxValue) onError { err => Stream.eval_(dumError(err)) }

val streamB: Stream[F, Nothing] = time.sleep_(1.second) ++ Stream.fail(new Throwable("BOOM"))


val program1 = (concurrent.join(Int.MaxValue)(Stream(streamA, streamB))) zip time.awakeEvery(20.seconds)

val program2 = (streamA merge streamB) zip time.awakeEvery(10.seconds)

```

then program1 will behave as follows: 

when StreamB fails (after 1s) then StreamA is killed, cleanups run and program will terminate after 20s with failure.  

however program2 will behave as follows: 

When StreamB fails (after 1s) then nothing will happen, however after 20s, when next element is requested, then cleanups for StreamA are run, and then program terminates with failure

Note the different time when cleanups on StreamA are called in both scenarios. 

This was observed on 0.9.6.

**Comment by mpilquist** [comment]
@pchlupacek Ah yes, okay. And that behavior is the same in 0.9 and 0.10, right?

**Comment by pchlupacek** [comment]
@mpilquist cannot confirm that 100% unfortunately.  I would assume however that yes, given 0.10 merge difference and fact that join has same code as 0.9, the behaviour shall be the same.

**Comment by pchlupacek** [comment]
@mpilquist to add some more context here, the merge + drain pattern also has bevaiour to "hold" the exception // failure that may happen on the drained stream. 

i.e. 
```scala

val s1 = Stream.eval(resource)

val s2 = time.sleep(1.second) ++ Stream.fail(boom)

(s1 mergeDrainR s2) flatMap { resource => 
resource.discrete  
}
```
This may deadlock, for example if resource is signal and s2 instead just sleep will be feeding values to signal.

**Comment by mpilquist** [comment]
@pchlupacek In 0.10 currently, yes. In 0.9, the exception would propagate out. Agreed?

**Comment by pchlupacek** [comment]
nope, in 0.9 this holds too. in 0.8 that teared down the Process.

**Comment by mpilquist** [comment]
Oh because `sleep` emits a value. In 0.9, it would raise the exception if you used `sleep_` though?

**Comment by pchlupacek** [comment]
I am sort of not sure which path to take here, but I would sort of like to interrupt any merge and its downstream if there will be any unhandled failure in any upstream. That's to me most user friendly and most expected behaviour. Also you can avoid that when you handle your exceptions in upstreams. However to introduce interruption of downstream based on upstream failure, is not that easy.

**Comment by pchlupacek** [comment]
@mpilquist I think it is in fact irrelevant whether you use sleep or sleep_. The failure will be hold until downstream asks for next element, which it will never do.

**Comment by mpilquist** [comment]
Overall, I think the behavior of merge in 0.10 is correct. It is simply "get the next available segment from either of these 2 streams". If you then `flatMap` on the result of that and return an infinite stream, the upstream streams are correctly never consulted again. I don't know of a principled change we could make to `merge` to give the desired behavior. For example, modifying `merge` to pull upstream until first non-empty segment is totally adhoc.

I'm not sure where that leaves us though. Should `async.hold` be implemented with `join` instead?

**Comment by pchlupacek** [comment]
@mpilquist the async.hold can be implemented with join or simply with start(). That is not really concenring me. What concenrs me is that `join` and `merge` have different laws. and that is very confusing in larger programs imho

**Comment by mpilquist** [comment]
I'm OK with `merge` and `join` having different behavior here as long as we document it very clearly.

**Comment by SystemFw** [comment]
Small data point: at work I have a working version of `hold` implemented with `start` because I stumbled into this exact problem> Although I didn't understand _why_ back then, what @mpilquist says about the behaviour of `merge` makes sense. However, that (imho) means that `merge` is not a good fit for `hold`, cause I would expect `hold.flatMap(_.discrete)` to work

**Comment by mpilquist** [comment]
BTW, if we implement with `start`, then there's no way to interrupt the publisher stream from downstream.

**Comment by SystemFw** [comment]
@mpilquist that's very true, in my case I also return an `F[Unit]` to interrupt, but I wouldn't like that in fs2. It it works with `join`, `join` is preferable. My main point is more that `merge` is not a great fit, given this discussion :)

**Comment by pchlupacek** [comment]
@mpilquist there is a way, if you use a signal + start. This is common pattern we use.

**Comment by pchlupacek** [comment]
Ok if we say the 0.10 merge behaviour is correct one, then I would suggest remove any mergeDrainX alltogether. As I do not see any use for them

**Comment by mpilquist** [comment]
The `mergeDrainX` methods still useful as long as you don't emit an infinite stream afterwards.

**Comment by pchlupacek** [comment]
@mpilquist not sure if I follow. Any example pls?

**Comment by SystemFw** [comment]
I think that, if your inner stream terminates, then flatMap "returns control" to `merge` so to speak, so the overall stream can proceed.
If instead you `flatMap` and the inner stream is infinite, `merge` has no change of pulling any more elements from the drained stream.

**Comment by pchlupacek** [comment]
I am really confused here, I am not sure if empty segemtnshall be taken as an alement, because thats what causing 0.10 and 0.9 difference right?

**Comment by mpilquist** [comment]
```
Stream.eval(async.signalOf[F,A]).flatMap { signal =>
  source.evalMap(signal.set) mergeDrainL signal.discrete
}
```

This is totally safe in both 0.9 and 0.10. The key difference between this and the way `hold` is implemented is that the merged stream is reconsulted after each downstream element is emitted, providing the drained left stream an opportunity to enqueue another segment.

**Comment by pchlupacek** [comment]
@mpilquist I see what you mean, but that is brings us to quite a tricky world.  we are suggesting that both streams can run, but in fact this: 

```scala
Stream.eval(async.signalOf[F,A]).flatMap { signal =>
  source.evalMap(signal.set) mergeDrainL signal.discrete
} zip time.awakeEvery(1.second)
```
will cause metronome to be applied not only on result of merge, but also to source itself, effectivelly breaking any concurrency in the program, introducing 1s metronome to whole graph. 

The problem is that that `zip` is affecting the `merge` and author of `merge` does not have any idea, of the downstream being zipped and metronomed. This may lead to very hard trackable bugs. 
I think this goes to same bag of issue like why we don't have `unset` signal anymore in API

**Comment by pchlupacek** [comment]
Also, not sure that 100% now, but, hence you taking discrete from that merge won't the next set be blocked until that discrete element will be processed?

**Comment by mpilquist** [comment]
> The problem is that that zip is affecting the merge and author of merge does not have any idea, of the downstream being zipped and metronomed.

Yes precisely. IMO, this is a *feature* of `merge`. 

> Also, not sure that 100% now, but, hence you taking discrete from that merge won't the next set be blocked until that discrete element will be processed?

Yes -- which is desirable in this case. I think what we are really getting at here is that `merge` is much different than a 2-way `join` and there are use cases for both.

**Comment by pchlupacek** [comment]
I see. I am still concerned about the fact that we take empty segment as element. What you would suggest is the correct definition of drain now? Because clearly is not that stream emits nothing. Is more like it emits empty chunks now?

**Comment by pchlupacek** [comment]
could we do so, that drain will not emit empty chunks? That will allow us to have both no? 0.10 an 0.9 behaviour....

**Comment by pchlupacek** [comment]
Then to have the bevaiour correct, perhaps we can introduce some combinator like (naming is terrible...): 

```scala

// on Stream[F, A]
def runWith(other: Stream[F, Unit]): Stream[F, A] = ???


```

That will in fact cause the `other` to be run in parallel with `stream` and also will terminate stream if the `other` fails. 

WDYT?

**Comment by mpilquist** [comment]
Right, drain emits empty chunks. It's implementation is:

```scala
  def drain: Stream[F, Nothing] = this.mapSegments(_ => Segment.empty)
```

It's still correct to say that the resulting stream emits no elements though. We had to allow the interpreter to emit empty chunks so that it can make progress in various scenarios introduced by `Segment` allowing infinite number of elements.

**Comment by pchlupacek** [comment]
@mpilquist yeah, thought so. I still thingk that 0.10 imlementation of drains is dangerous and some `runWith` alterantive shall be clear enough + it shall improve curren 0.9 behaviour too. 
Also I think in that case the join shall perhaps follow the `runWith` laws if it won't complicate it too much.

**Comment by mpilquist** [comment]
The new combinator would basically be a more efficient version of `Stream(l.drain, r).join(2)`, right? That makes sense to me. Not sure what we shoudl call it.

**Comment by pchlupacek** [comment]
@mpilquist yes. And I think still mergeDrainL / R shall be removed.

**Comment by pchlupacek** [comment]
we can call it `mergeWith` ?

**Comment by pchlupacek** [comment]
or we can keep mergeDrainL/R and define them with laws of join.(2) :-)

**Comment by mpilquist** [comment]
How about `l.concurrently(r)`? I could live with `mergeWith` but its similarity in name with `merge` is confusing I think.

I'm fine with removing `mergeDrainL/R`.

**Comment by pchlupacek** [comment]
but that will be perhaps even more confusing hence (a.drain merge b) will have completely different results than (a mergeDrainL b)

**Comment by pchlupacek** [comment]
@mpilquist sounds perfect

**Comment by pchlupacek** [comment]
ok will do a PR over weekend unless anyone else volunteers :-)

**Comment by mpilquist** [comment]
Want me to open a PR this afternoon?

**Comment by pchlupacek** [comment]
yes :-)

**Comment by pchlupacek** [comment]
ok to sum:
- mergeDrainL/R will get removed
- new `def concurrently(other: Stream[F, Unit]): Stream[F, A]' will live on stream, with laws : 
  - when `other` terminates `stream` continues to run
  - when `other` fails, `stream` fails too
  - when `stream` termiantes, `other` gets killed 
  - when `stream` fails, `other` gets killed 
- Stream(stream, other).join(2) will have same laws as `concurrently`
did I forgot something?

**Comment by pchlupacek** [comment]
@mpilquist sorry did a couple of edits, hope is clear now what i meant above

**Comment by pchiusano** [comment]
Haven't been following this too closely but `concurrently` semantics @pchlupacek gave above make sense. No objections to getting rid of `mergeDrainL/R` if that's what y'all want to do.

**Comment by mpilquist** [comment]
Closing b/c `concurrently` was merged a few weeks ago. Also, I added a note about `interruptWhen` behavior in 6306212ae6a516e61b0acb4f334311bc458cbe75.
