### ISSUE TITLE
Intermittent failure in join

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#913]
I noticed a very rare failure in `join (3)` test in `MergeJoinSpec` where `runLog` hangs. To reproduce, change the scalacheck config in `Fs2Spec` to `PropertyCheckConfiguration(minSuccessful = 2500, workers = 1)` and then run `testOnly *MergeJoinSpec -- -z "join (3"`. On my machine, I encountered the hang after about 9 minutes.

@pchlupacek Could you look at this?

**Comment by pchlupacek** [comment]
@mpilquist 0.9?

**Comment by mpilquist** [comment]
0.10 HEAD -- I haven't tried it with 0.9

**Comment by pchlupacek** [comment]
@mpilquist ok thanks

**Comment by mpilquist** [comment]
@pchlupacek Friendly reminder on this one.

**Comment by pchlupacek** [comment]
@AdamChlupacek please can you take a  quick look on this ?

**Comment by AdamChlupacek** [comment]
Just tested this with the new scope and asyncUncons, I do not see any hanging anymore.

**Comment by mpilquist** [comment]
Also confirmed this no longer fails :)
