### ISSUE TITLE
Should Signal have a setSyncPure?

### ISSUE THREAD

**Issue by zainab-ali** [functional-streams-for-scala/fs2#923]
I have a case where a value needs to be set synchronously for an arbitrary effect type.  
In 0.10, this can be achieved by using the `setSyncPure` function on `Ref`:
```scala
F.runAsync(ref.setSyncPure(value))(_ => IO.unit).unsafeRunSync()
```

~~It's not possible to call this in 0.9 where the private `fs2.internal.Ref` is modeled very differently.~~ 

**EDIT**: fs2 exposes an `Async.Ref` which has an asynchronous set method.

This logic is much better described using a `Signal` with a synchronous set method.

Are there any thoughts on having a `setSync` and `setSyncPure` method on `Signal`, which defer to the methods on the underlying ref?  

I'd be happy to add this, if desired.

**Comment by SystemFw** [comment]
Have you checked the right `Ref`? There's a `Ref` in `Task` which is roughly equivalent to the `Ref` in 0.10

**Comment by SystemFw** [comment]
@zainab-ali do you still need this, or is `Async.Ref` enough?

**Comment by zainab-ali** [comment]
You're right!  I was looking at the wrong `Ref`.  fs2 exposes an `Async.Ref` which is public.

However, this doesn't have a synchronous set method - I do still need this behavior.

**Comment by mpilquist** [comment]
@zainab-ali Porting `setSyncPure` from 0.10's `fs2.async.Ref` to 0.9's `fs2.util.Async.Ref` should be straightforward. If you want to give it a shot, I'd be happy to merge a PR and answer any questions that arise.

**Comment by zainab-ali** [comment]
That would be great!  I shall give it a go

**Comment by zainab-ali** [comment]
As discussed in https://github.com/zainab-ali/fs2-reactive-streams/pull/31, this change is no longer necessary
