### ISSUE TITLE
[Help Request] convert fs2 to monix and monix to fs2

### ISSUE THREAD

**Issue by andykais** [functional-streams-for-scala/fs2#929]
Hi, I am uncertain of the 'proper' way to convert an `fs2.Task` to a `monix.eval.Task`. The one solution I know for fs2->monix is to convert the `fs2.Task`  to a future (`task.unsafeRunAsyncFuture`) and then let monix convert from a future with `monix.eval.Task.fromFuture`. This feels messy and possibly slow, is there a better method?

I am hoping there is a solution for converting from monix to fs2 as well that doesnt involve futures

**Comment by DavidGregory084** [comment]
It would be worth looking at the excellent [fs2-reactive-streams](https://github.com/zainab-ali/fs2-reactive-streams) project. I can provide a snippet but I haven't updated it for 0.10:
```
import fs2.interop.reactivestreams._
import fs2.{ Strategy, Stream, Task => Fs2Task }
import fs2.Async
import monix.eval.{ Task => MonixTask }
import monix.execution.Scheduler
import monix.reactive.Observable

  implicit class Fs2TaskOps[A](task: Fs2Task[A])(implicit strategy: Strategy) {
    def toMonixTask: MonixTask[A] = Stream.eval(task).toMonixObservable.firstL
  }

  implicit class Fs2StreamOps[F[_]: Async, A](stream: Stream[F, A])(implicit strategy: Strategy) {
    def toMonixObservable: Observable[A] = Observable.fromReactivePublisher(stream.toUnicastPublisher)
  }

  implicit class MonixTaskOps[A](task: MonixTask[A])(implicit strategy: Strategy, scheduler: Scheduler) {
    def toFs2Stream: Stream[Fs2Task, A] = task.toReactivePublisher(scheduler).toStream[Fs2Task]
  }
```

**Comment by DavidGregory084** [comment]
As of fs2 0.10 and Monix 3.0.0 both projects will be using [cats-effect](https://github.com/typelevel/cats-effect/) so this kind of interop should get a lot easier

**Comment by andykais** [comment]
very helpful, thank you. For clarification, were you suggesting the `fs2-reactive-streams` as a stand in for monix Observables or just for the conversion you have in that snippet

**Comment by DavidGregory084** [comment]
The latter; the `.toStream` and `toUnicastPublisher` methods in that snippet are provided by fs2-reactive-streams

**Comment by mpilquist** [comment]
Closing as this seems to be resolved but feel free to reopen on discuss on Gitter if there's something outstanding here.
