### ISSUE TITLE
Add yip/yipWith/yipAll - non-deterministic versions of zip/zipWith/zipAll

### ISSUE THREAD

**Issue by avakhrenev** [functional-streams-for-scala/fs2#936]
In the context of `PipeSpec`:
```scala
"zipWith termination" in {
  val never = Stream.eval(IO.async[Int](_ => ()))
  val s = Stream(1, 2, 3)
  // works:
  runLog(s.zipWith(s ++ never)(_ == _), timeout = 1 second) shouldBe Vector(true, true, true)
  // hangs:
  runLog((s ++ never).zipWith(s)(_ == _), timeout = 1 second) shouldBe Vector(true, true, true)
}
```

**Comment by mpilquist** [comment]
This is an inherent limitation in deterministic zipping. Because the various zip functions are all deterministic, they are biased to the left stream when pull. In the example that hangs, the pull on the left stream evaluates the never stream, which causes the hang.

To fix, we need a non-deterministic version of zip, historically known as yip (afaik, the name is a play on "zip implemented with a wye"). I vaguely recall discussing this for 0.9 - @pchlupacek any thoughts?

**Comment by pchlupacek** [comment]
@mpilquist I think yip will be usefull. 

However as for the example above, `s` has three elements, and then terminates, so my guess is the right stream (`s ++ never`) shall not hold the stream, as he is able to supply exactly three elements, and then for the fourth which is not coming it shall not be consulted at all, so essentially append (`++`) shall never be invoked in this case ?

**Comment by mpilquist** [comment]
@pchlupacek The above example but with `yipWith` would intermittently hang I guess, depending on whether the second pull on `s ++ never` is evaluated before or after the end of `s` is reached.

**Comment by pchiusano** [comment]
If end up writing yip, a version where you supply a bound on the number of
elements ahead either side is allowed to get would be more general.
(Unbounded is like a "product" version of merge)

**Comment by pchlupacek** [comment]
@mpilquist I think correct behaviour of yipWith is like you describe, and it shall perhaps _always_ halt. However still zipWith shall be Left biased and as such shall not hung if the right side hangs. So I think current zipWith implementation is broken, and perhaps we have introduce yipWith? As regards the eagerness @pchiusano suggest, not sure if that shall not be generic feature on stream (and I think we already have some kind of pre-fetch)?

**Comment by mpilquist** [comment]
@pchlupacek I don't agree that `zipWith` is broken -- inappropriate for this use case but fine overall. After more thought, I do agree that `(s ++ never).yip(s)` and `s.yip(s ++ never)` will both always terminate.

**Comment by pchlupacek** [comment]
:-) @mpilquist ok, I have generally no problem if yipWith and zipWith will have same behaviour, that means they will stuck in this case. My point was just we could perhaps do better with zipWith.... Do you see any issues when zipWith will be left biased and will always terminate once left side terminates, interrupting the right side ? 

Essentially I would say this shall hold : 
```scala
val s1 = Stream(1)
val s2 = Stream(1, 2)
val never: Stream[F, Int] =  Stream.repeatEval(...)

(s1 zip s1).runLog == (s1 zip s2).runLog == (s1 zip (s2 ++ never)).runLog 

// as I understand now we have 

(s1 zip s1).runLog == (s1 zip s2).runLog  
//but 
(s1 zip s2).runLog != (s1 zip (s2 ++ never)).runLog 

```

**Comment by pchlupacek** [comment]
I think this could be closed. I believe I will be able to come up with Wye for post 0.10, that would bring back yip. any thoughts?

**Comment by avakhrenev** [comment]
I'm not familiar with Wye, @pchlupacek, could you post some links?

**Comment by pchlupacek** [comment]
@avakhrenev this concepts comes from scalaz-stream 0.8 and essentially it introduces special algebra to construct streams where you can decide whether you want to read from Left, Right or terminate. 

I am still unsure, if we really need this, as we would like to avoid cluttering api with unfamiliar concepts to users. 

If you want to see some samples how that worked, go to 0.8 branch and see some wye tests.

**Comment by avakhrenev** [comment]
Thanks! Looks similar to `uncons` and `unconsAsync` + `race` with max 2 streams at a time. I like it.

**Comment by pchlupacek** [comment]
@avakhrenev yes, exactly.

**Comment by mpilquist** [comment]
@pchlupacek Thoughts on this one for 1.0?

**Comment by pchlupacek** [comment]
I think this will be solely new combinator we don't need to block 1.0

**Comment by SystemFw** [comment]
What's the status of this?
Note that we almost have it already implemented in the `Applicative[Signal[F, ?]]` instance

**Comment by pchlupacek** [comment]
@SystemFw I am not sure If we could manage wye-style combinators before 1.0 final

**Comment by SystemFw** [comment]
what is this then?

https://github.com/functional-streams-for-scala/fs2/blob/series/1.0/core/shared/src/main/scala/fs2/concurrent/Signal.scala#L66

Anyway just looking for a status update, we can delay it if needed :)

**Comment by pchlupacek** [comment]
ok I didn't get in detail on this combinator. I was sort of addressing the generic wye, so perhpas we could make this public and that it is, not sure 100% though.

**Comment by SystemFw** [comment]
yeah, not sure either. @mpilquist ideas?

**Comment by mpilquist** [comment]
No strong opinions. If we promoted that to API, would we need all the variants like yipWith, yipAll, etc?

**Comment by SystemFw** [comment]
mm true. Maybe we can hold off until we decide about a more general solution
