### ISSUE TITLE
Public constructor of Ref allows breaking referential transparency

### ISSUE THREAD

**Issue by durban** [functional-streams-for-scala/fs2#951]
The expression `new Ref[IO, Int]` is not pure. Making the constructor private would force users to use the pure "equivalent": `Ref.uninitialized[IO, Int]`.

**Comment by SystemFw** [comment]
mm true, I'll fix this. Just fyi, you can construct `Ref`s using `async.ref` and `async.refOf`

**Comment by durban** [comment]
Thanks for the fix and the suggestion!
