### ISSUE TITLE
Socket.readN yields more data than requested

### ISSUE THREAD

**Issue by tpolecat** [functional-streams-for-scala/fs2#957]
`Socket.readN(n)` does not in fact read "exactly N bytes" but rather *at least* `n` bytes because the backing buffer is never shrunk; it is only embiggened as necessary. So `readN` will read as many bytes as in the biggest chunk requested thus far on that `Socket`. A quick fix is to change `<` to `!=` [here](https://github.com/functional-streams-for-scala/fs2/blob/series/0.10/io/src/main/scala/fs2/io/tcp/Socket.scala#L205). but that may have an unacceptable performance impact so shrinking may need to be special-cased; or the `readN0` method may need to be modified pull only the requested number of bytes.

**Comment by mpilquist** [comment]
@pchlupacek Any thoughts on this?

**Comment by pchlupacek** [comment]
The fix shall be quite straightforward. Essentially we need to add another guard except the side of buffer to `readChunk` implementation. @tpolecat Any chance you can write test for this ?

**Comment by tpolecat** [comment]
Yep, will do.

**Comment by pchlupacek** [comment]
Excellent thanks a lot.
