### ISSUE TITLE
>> vs *>

### ISSUE THREAD

**Issue by mpilquist** [functional-streams-for-scala/fs2#961]
`>>` is deprecated in Cats 1.0 in favor of `*>` (https://github.com/typelevel/cats/pull/1955). Should we follow suit on `Stream`, `Pull`, etc?

**Comment by ChristopherDavenport** [comment]
I have already started switching to those semantics where available. So I would be all for consistent syntax.

**Comment by mpilquist** [comment]
Fixed by #963
