### ISSUE TITLE
Create `StreamApp` to allow creation of an app which is built around a `Stream`

### ISSUE THREAD

**Issue by agustafson** [functional-streams-for-scala/fs2#973]
I recently built an app which consumes results from a kafka topic but it seemed like there was a reasonable amount of work to perform cleanup on shutdown. The `StreamApp` in http4s works perfectly for this use case, and there is nothing in it which is directly related to http4s. Is it worthwhile porting across? Happy to do the PR if you want.

**Comment by aeons** [comment]
I think it makes sense, and after so many rewrites, I'm actually happy with `StreamApp` at the moment :)

**Comment by rossabaker** [comment]
Nobody has complained about the current iteration. :+1:  http4s can deprecate theirs if and when it moves into fs2.

**Comment by mpilquist** [comment]
👍 from me. I'd like to avoid the dependency on log4s.

**Comment by rossabaker** [comment]
I think that logger call could be a `t.printStackTrace()` without any regret.

**Comment by ChristopherDavenport** [comment]
👍  On this. Http4s never seemed like the right home. If I were to build a PR where would you like it located?

**Comment by mpilquist** [comment]
`fs2.StreamApp` works for me.
