### ISSUE TITLE
Streaming of very large documents is (relatively) slow

### ISSUE THREAD

**Issue by lukestephenson** [functional-streams-for-scala/fs2#977]
I originally raised this against http4s, but on further investigation narrowed it down to fs2.  The original issue is https://github.com/http4s/http4s/issues/1555#issuecomment-344463931.

Note the issue I'm presenting here is a bit contrived as I've narrowed it down to the smallest possible piece of code which highlights the issue.  My actual application is streaming results from the DB.

I've got the following code to copy a large (2GB) file.
```
 def copyFile(): Unit = {
    val file = new File(s"largefile.txt")

    val process = fs2.io.file.readAll[IO](file.toPath, DefaultBufferSize)
      .through(fs2.io.file.writeAll(Paths.get("copy.txt")))
      .run

    val start = System.currentTimeMillis()
    process.unsafeRunSync()
    val end = System.currentTimeMillis()
    println(s"Took ${end - start}ms")
  }
```

This code takes 45 seconds to run (macbook pro) and is rather CPU intensive for an IO activity.

If it helps at all, jvisualvm sampler snapshot looks like:
![image](https://user-images.githubusercontent.com/395523/32813064-62c6e7c6-c9fc-11e7-9793-f92b7d0d5be6.png)

As a comparison, the equivalent commons-io example completes in 5 seconds.
```
import org.apache.commons.io.IOUtils;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;

public class Test {
    public static void main(String[] args) throws Exception {
        File file = new File("/Users/luke.stephenson/projects/listings/listing-publisher-api/results4.txt");
        File out = new File("/Users/luke.stephenson/projects/listings/listing-publisher-api/results3.txt");

        long start = System.currentTimeMillis();
        IOUtils.copyLarge(new FileInputStream(file), new FileOutputStream(out));
        long end = System.currentTimeMillis();
        System.out.println("Took " + (end - start) + "ms");
    }
}
```

Curious to hear thoughts on this. Is it a bad idea to be working with large response streams with fs2?

Thanks!

**Comment by mpilquist** [comment]
Thanks for reporting this.

> Is it a bad idea to be working with large response streams with fs2?

No, quite the contrary! Large streams are a primary use case of fs2.

I'll investigate this some and get back to you soon.

**Comment by rossabaker** [comment]
* @jmcardon posted an [interesting benchmark](https://gitter.im/http4s/http4s?at=5a0c5b03ba39a53f1aa27d7a) in Gitter.
* IOUtils recycles the byte buffer.  On the original ticket, @lukestephenson also got [poor results from fs2.io.unsafeReadInputStream](https://github.com/http4s/http4s/issues/1555#issuecomment-344471466), which has a bit more in common with the `IOUtils` approach.

**Comment by jmcardon** [comment]
Hi all.
[Here](https://gist.github.com/jmcardon/7eb351c1c3dc2d15e838d60671bf352f) is an updated benchmark.

@lukestephenson created a project [here](https://github.com/lukestephenson/stream-benchmarks) using sbt-jmh. I ran it on my own machine, but changed the chunk size twice.

His results were different than mine (appreciably less extreme),  but there was still a 4x slowdown compared to commons-io and monix, which seem to perform in a similar fashion.

**Comment by fiadliel** [comment]
This is because `toArray` does a lot of work for an array-backed chunk. With a specialized `toArray` for each chunk type (using `Array.slice`), these particular benchmarks change a bit (I found NIO to actually be faster than `InputStream`):

*Before*:
```
[info] Benchmark                                              Mode  Cnt   Score   Error  Units
[info] LargeStreamBenchmark.commonsIo                         avgt    3   3.290 ± 5.899   s/op
[info] LargeStreamBenchmark.fs2IoStream                       avgt    3  39.473 ± 4.400   s/op
[info] LargeStreamBenchmark.fs2NioStream                      avgt    3  20.189 ± 2.503   s/op
[info] LargeStreamBenchmark.monixObservable                   avgt    3   4.062 ± 3.204   s/op
[info] LargeStreamBenchmark.monixObservableWithAsyncBoundary  avgt    3   2.727 ± 1.002   s/op
```

*After*:
```
[info] Benchmark                                              Mode  Cnt  Score   Error  Units
[info] LargeStreamBenchmark.commonsIo                         avgt    3  3.130 ± 1.660   s/op
[info] LargeStreamBenchmark.fs2IoStream                       avgt    3  5.489 ± 5.185   s/op
[info] LargeStreamBenchmark.fs2NioStream                      avgt    3  2.994 ± 0.864   s/op
[info] LargeStreamBenchmark.monixObservable                   avgt    3  3.957 ± 1.024   s/op
[info] LargeStreamBenchmark.monixObservableWithAsyncBoundary  avgt    3  2.718 ± 0.858   s/op
```

However, a naïve implementation only works for a basic chunk, not for a segment, so perhaps the right solution should operate at that level?

**Comment by pchlupacek** [comment]
@fiadliel excellent finding. I think we shall review all chunks in 0.10 fs2. Also I am not sure, but in my recent work I found that pipe.chunkN at all seems to not preserve optimized chunks (i.e. Bytes).

**Comment by lukestephenson** [comment]
Thanks for fixing @mpilquist
