### ISSUE TITLE
Queue#peek

### ISSUE THREAD

**Issue by durban** [functional-streams-for-scala/fs2#983]
I think a `Queue#peek` method would be useful with the following signature:
```scala
def peek: F[A]
```
Its semantics would be like `dequeue1`, but without removing the element. It could have a `timedPeek` variant too.

If it's determined, that this indeed would be useful, I'm willing to work on a PR.

**Comment by mpilquist** [comment]
Generally in favor of this. Have any example use cases? Name wise, how about `peek1` / `timedPeek1`?

**Comment by durban** [comment]
Use case: I needed an [MVar](https://hackage.haskell.org/package/base-4.10.0.0/docs/Control-Concurrent-MVar.html), and a queue with size limit = 1 is basically that. But for that, I needed a way to read without removing the element. (Maybe I should've proposed adding an MVar instead, I'm not sure...)

Regarding names: sure, I don't feel strongly about them.

**Comment by SystemFw** [comment]
@durban I went through this road (went as far as creating a prototype for one). 
Have you explored using `Ref` directly?

**Comment by durban** [comment]
@SystemFw Sure, but AFAICT a `Ref` cannot be cleared (emptied), and I needed that functionality.

**Comment by SystemFw** [comment]
Fair enough then :)

During my exploration I came to the conclusion that it's a feature, but ofc your use case might be different.

**Comment by AdamChlupacek** [comment]
@durban Is having a `Ref[Option[A]]` not enough? you can empty it by setting it to `None`.

**Comment by SystemFw** [comment]
you can define an `MVar` on top of  `Ref[Option[A]]`, but that on it's own won't (semantically) block on the empty case (you can have a blocking architecture mimicking the one in queue though).
The only thing I'm not sure about wrt `MVar` and `Ref` is `modifyF`, there's an issue for that if you want more background #888

**Comment by SystemFw** [comment]
@durban 

> Its semantics would be like dequeue1

What about when there are concurrent peakers? Do you want FIFO semantics, or do they all get notified at once?

**Comment by durban** [comment]
@AdamChlupacek As @SystemFw already said, a simple `Ref[F, Option[A]]` is not enough due to `get` in the empty case.

@SystemFw I think they would all get notified at once. (Even if there are takers queued up.)

**Comment by SystemFw** [comment]
@durban Cool, it shouldn't be too hard to implement then (you need to change the state held by the queue though)

I'm generally in favour of just adding `peek1` to Queue, not sure if we should add MVar or not though (if you have a use case/datastructure that `Ref` wasn't able to implement, curious to know the details, regardless of this PR)
