### ISSUE TITLE
Memory leak when reading files with a small buffer size

### ISSUE THREAD

**Issue by lukestephenson** [functional-streams-for-scala/fs2#987]
This is running against `"co.fs2" %% "fs2-io" % "0.10.0-SNAPSHOT"` containing the fix to #977 

I noticed a memory leak when using http4s which I raised https://github.com/http4s/http4s/issues/1561.  This may be related, or may not.  I was trying to track down a minimal test to reproduce and ended up here.

I ended up using the same code as what I was using for the file copy performance test before, but changed the read buffer size to 1.

https://github.com/lukestephenson/stream-benchmarks/blob/master/src/main/scala/benchmarks/CompressTest.scala
```
package benchmarks

import java.io.File
import java.nio.file.Paths

import cats.effect.IO
/**
 * results4.txt is a 4GB file.
 * run this with -Xmx56m
 **/
object CompressTest {
  val DefaultBufferSize = 1
  val src = "/Users/luke.stephenson/projects/listings/results4.txt"
  val target = "/Users/luke.stephenson/projects/listings/results3.txt"

  def main(args: Array[String]): Unit = {
    val file = new File(src)

    val start = System.currentTimeMillis()

    def process = fs2.io.file.readAll[IO](file.toPath, DefaultBufferSize)
      .through(fs2.io.file.writeAll(Paths.get(target)))
      .run

    process.unsafeRunSync()

    val end = System.currentTimeMillis()

    println(s"took ${end - start}ms")
  }
}
```
When running with a large buffer size, the code runs fine.  However when running with a small buffer  size it runs out of memory.  I'd expect it to be slower, but not impact memory usage.

The heap dump shows it holding onto a lot of `FreeC` instances.

**Comment by lukestephenson** [comment]
It seems all that is required for reproduce is:
```
def process = fs2.io.file.readAll[IO](file.toPath, DefaultBufferSize)
      .run
```

**Comment by mpilquist** [comment]
I confirmed the leak when using `readAll`. I've also confirmed that the following program does *not* leak:

```scala
scala> def loop: Pull[IO,Int,Unit] = Pull.eval(IO(0)).flatMap(r => loop)
loop: fs2.Pull[cats.effect.IO,Int,Unit]

scala> loop.stream.run.unsafeRunSync
```

**Comment by mpilquist** [comment]
Alright, found the issue. It was due to use of `for/yield` in `io.file.pulls.readAllFromFileHandle`. Each loop through this function would result in an extra `map(identity)` call being pushed to right of `FreeC` stack due to the `yield next`.
