### ISSUE TITLE
`pull` and `++` causes stream to lost its output

### ISSUE THREAD

**Issue by pchlupacek** [functional-streams-for-scala/fs2#995]
I have discovered this when testing the new interruption mechanics, and seems somehow the current pull and apeend in certain scenarios do not work as expected. 

given this code 
```scala

val s1: Stream[IO, Int] = PureStream.singleChunk(Arbitrary(Gen.const(4))).sample.get.get.covary[IO]
 
s1.pull.unconsAsync.flatMap { asyncPull =>
  Pull.getScope[F, O, Unit] flatMap { scope =>
          asyncPull.pull.flatMap {
            case Some((h, t)) =>
              Pull.segment(h) //*> Pull.echo(t)

            case None => Pull.done

          }
}}.stream ++ Stream.eval(F.delay(())) flatMap { _ =>
    Stream.empty
 }.runLog.unsafeRunSync

```

this is supposed to return Vector with elements, 

However this always return empty. 

Suprisingly, when the `++ Stream.eval ...` part is removed, then this will behave as expected. 

Any ideas @mpilquist ?

**Comment by AdamChlupacek** [comment]
I do not think this is a bug. Your last `flatMap` returns an `Stream.empty`. Since you are using the space instead of dot, this `flatMap` will be applied to the whole `Stream` not just the part after `++`.

**Comment by pchlupacek** [comment]
yes you right
