### ISSUE TITLE
Queue.synchronousNoneTerminated is missing from the async package object

### ISSUE THREAD

**Issue by durban** [functional-streams-for-scala/fs2#997]
Most queue types seem to be exposed on the `async` package object (e.g., `async.boundedQueue`). `Queue.synchronousNoneTerminated` is not. Is this intentional?

**Comment by mpilquist** [comment]
`synchronousNoneTerminated` was added for a specific use case in the implementation of `diamond` or `join` or one of the other async combinators. I don't think we expected folks would want to use it but I have no issue with it having a constructor in the `async` package object.

**Comment by durban** [comment]
Yes, it seems quite specialized, I just wasn't sure if it was an oversight. I'm fine with it as it is.
